### ISSUE TITLE
Al dar los resultados de las encuestas enviadas, no se tiene en cuenta los datos de la encuesta final (la del usuario ve estadisticas)

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/gusite#10]
Numero: 14
Creació: 2016-02-16 07:58:16.833000
Al dar los resultados de las encuestas enviadas, no se tiene en cuenta los datos de la encuesta final (la del usuario ve estadisticas)

**Comment by episano-dgtic** [comment]
Comprobado el correcto funcionamiento en caibter
