### ISSUE TITLE
Adaptacions nou servidor traductor automàtic

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#100]
Es sol·licita replicar les actuacions fetes en https://github.com/GovernIB/rolsac/issues/415 per tal que el servei de traducció automàtica integrat a GUSITE s'adapti als canvis del nou servidor de traducció (scatwnt2).

**Comment by slromero-indra** [comment]
buenas, 
Hemos actualizado la aplicación, y comprobado que funciona con ambos servidores.
