### ISSUE TITLE
Incorporar utilitat presentació menú horitzontal

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#101]
En sol·licita incorporar en el mení Configuració/General una utilitat que permiti la presentació multinivell del menú principal de l'aplicació.
A diferència del menú vertical, l'horitzontal estirà sempre plegat i no mantindrà l'opció seleccionada.

**Comment by slromero-indra** [comment]
Buenas, 
Entendemos que esta opción solo tiene sentido para la plantilla 2017, ¿correcto? ¿o queréis que también se maquete para la actual plantilla por defecto?
Prepararemos un diseño para que podáis validarlo.

**Comment by sgelabert-dgtic** [comment]
El que perseguim és que la plantilla per defecte passi a ser la plantilla 2017 (aquest era el requeriment inicial i que per "seguretat" deixàrem per una segona fase). No crec que valgui la pena doncs fer adaptacions a una plantilla que després no utilitzarem.
Ok, a la validació del disseny

**Comment by slromero-indra** [comment]
Visualización del resultado final.

Frontal por defecto:
http://caibter.indra.es/sites/indra/ca/demo_listado_y_botones_mic/

Tema 2017
http://caibter.indra.es/sites/indra2018/ca/demo_listado_y_botones_mic/

**Comment by bgarcia-dgtic** [comment]
El menú horitzontal funciona correctament, però si a la configuració/general/aparença es marca que no es vol cercador, canvia la visualització del menú. Adjunt captures de pantalla
![captura1](https://user-images.githubusercontent.com/26536678/36299145-fab7920e-12fb-11e8-9b48-6227c1e74cb2.jpg)
![captura2](https://user-images.githubusercontent.com/26536678/36299154-0556b17c-12fc-11e8-883a-8db61521bccf.jpg)

**Comment by bgarcia-dgtic** [comment]
El menú funciona correctament, però hauria de sortir a l'apartat Configuració/General/Aparença. En aquests moments apareix a l'apartat Configuració/General just davall de l'opció "Selecciona la versió", i els usuaris no la veuen ja que només veuen fins a la opció "Idioma".

**Comment by bgarcia-dgtic** [comment]
Hem detectat un mal funcionamet al backoffice. 
Quan un usuari amb rol GUS_SUPER fa qualsevol canvi a l'apartat "Configuració/General/Aparença/Tipus de menú", i l'orientació del menú és horitzontal, automàticament aquest passa a ser clàssic. Adjunt captures de pantalla.
Captura1.jpg -> L'orientació del menú és horitzontal.
![captura1](https://user-images.githubusercontent.com/26536678/36530309-06a0ff88-17bb-11e8-8342-15d4cd951e7d.JPG)

Captura2.jpg -> Es fa un canvi a l'apartat Configuració/General/Aparença/Tipus de menú
![captura2](https://user-images.githubusercontent.com/26536678/36530328-14d8c7ac-17bb-11e8-895a-95dced27031c.jpg)

Captura3.jpg -> Es canvia l'orientació del menú a Clàssic
![captura3](https://user-images.githubusercontent.com/26536678/36530347-1a2cdafe-17bb-11e8-9851-fb35872106c9.JPG)

**Comment by bgarcia-dgtic** [comment]
Pareix que el canvi de menú horitzontal a clàssic afecta a qualsevol canvi que es faci a la Configuració ja sigui a l'apartat General, Campanya, Serveis Oferits o Aparença. Només passa amb rol GUS_SUPER.

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la aplicación, ¿Lo podeis validar?

**Comment by bgarcia-dgtic** [comment]
Hem detectat que quan es selecciona el "Tipus de Menú -> Sense Menú" i l'orientació del menú és horitzontal, el menú es mostra igualment cara al públic i no s'hauria de mostrar, com és el cas del menú clàssic (si es selecciona el "Tipus de Menú -> Sense Menú" i l'orientació del menú és clàssic, el menú no es mostra cara al públic)

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos revisado este problema en el commit 5c68c4ffb8693b13f0a657bebf17ba8a3f69dd4e

**Comment by bgarcia-dgtic** [comment]
Hola,
Hem detectat que quan es desplega una opció del menú horitzontal, hi ha un solapament amb el contingut de la pàgina. Pareix que passa quan el contingut de la pàgina és un llistat, formulari, FAQS o mapa. Adjunt captures de pantalla i la url del Microsite amb el que estic fent proves.
URL: https://appproves.caib.es/sacmicroback/index.do?idsite=5985#

Captura1.jpg: el contingut de la pàgina és un llistat
![captura1](https://user-images.githubusercontent.com/26536678/37151014-2fd786a0-22d4-11e8-88f5-f707fe3364fa.JPG)

Captura2.jpg: el contingut de la pàgina és un formulari
![captura2](https://user-images.githubusercontent.com/26536678/37151040-44e69eaa-22d4-11e8-9670-33a02d012d53.JPG)

Captura3.jpg: el contingut de la pàgina conté el component mapa
![captura3](https://user-images.githubusercontent.com/26536678/37151073-61f4d7b4-22d4-11e8-99c2-e98251113f2c.JPG)

Captura4.jpg: el contingut de la pàgina es una FAQ
![captura4](https://user-images.githubusercontent.com/26536678/37151112-905f6f1a-22d4-11e8-8583-bcbc6239d848.JPG)

**Comment by bgarcia-dgtic** [comment]
Hola,
Hem detectat que quan una carpeta del menú horitzontal conté moltes pàgines, no es mostren totes, es a dir, només mostra opcions fins al final del contingut central de la pàgina. Hauria d'haver un scroll com el que apareix a webcaib. 
Cas concret: La primera carpeta "Home" té 20 pàgines. Adjunt captures de pantalla.
https://appsproves.caib.es/sacmicroback/index.do?idsite=5985#
Captura1.jpg
![captura1](https://user-images.githubusercontent.com/26536678/37388190-c14f3012-275f-11e8-90a5-deb695306503.JPG)

Captura2.jpg: mostra més opcions ja que el el contingut central de la pàgina és més llarg
![captura2](https://user-images.githubusercontent.com/26536678/37388209-dfa8967a-275f-11e8-8e02-f14edcc14821.JPG)

Captura3.jpg: exemple de menú amb scroll
![captura3](https://user-images.githubusercontent.com/26536678/37388378-803c38bc-2760-11e8-82df-45a782400b48.JPG)

**Comment by dmadronal-indra** [comment]
Buenas,
Este problema lo detectamos con las últimas pruebas y ya lo estabamos tratando, a priori la solución que el diseñador propuso y que estabamos aplicando era la de que se vieran todas las opciones aumentando el scroll de la página si era necesario, ya que, al tener submenus, si se aplica un scroll directamente al menu, puede producir problemas de accesibilidad. 

Quereis que apliquemos la solución del scroll en el menú? o preferís que sigamos con la solución que estabamos aplicando?

**Comment by dmadronal-indra** [comment]
Buenos días,
Hemos incluido la solucion inicial que teniamos ya implementada para que podais validarla.

La opción que comentáis en la incidencia (añadir un scroll en el segundo nivel del menú al estilo webcaib), implica multitud de cambios, por lo que, si queréis, podemos estimar la tarea . A priori requiere modificar la estructura HTML. Actualmente se usan listas anidadas para los diferentes niveles, lo que hace que el menú tenga una estructura clara (se puede identificar el padre de  cada subnivel), pero para montar el scroll vertical dentro del submenú se debería modificar esta estructura haciendo que los niveles no dependan unos de otros. Esto puede ser un inconveniente tanto a nivel de accesibilidad como a nivel de indexación por parte de buscadores externos ya que la estructura del menú no identificará los padres de los hijos.
Estas modificaciones HTML implicaran también cambios a nivel de css y js para adaptarse a la nueva estructura y habrá que definir diferentes incógnitas a nivel de diseño (ubicación del scroll, número de elementos por submenú fijo o modificable, definir si el submenú nivel 3 también dispondrá de scroll, …) también hay que tener en cuenta todas las posibles opciones que dispone gusite para visualizar el menú, (horizontal/vertical, con o sin iconos, con o sin buscador, etc…), lo que lo dota de mucha funcionalidad, pero dificulta el desarrollo.
 
¿Queréis que revisemos más a fondo esta opción y os enviemos un documento de estimación?

**Comment by sgelabert-dgtic** [comment]
OK, finalitzau doncs l'opció d'scroll a nivell de pantalla que ja teniu desenvolupada.
De moment, no fa falta que faceu estimació per l'scroll a nivell de menú
