### ISSUE TITLE
Incorporació botó MIC

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#102]
Es sol·licita incorporar a l'editor TinyMCE una utilitat per incorporar un botó (text, enllaç i icona) amb estil MIC.
Valorar si es pot afegir com a pluggin Tiny o bé s'ha de modelar com a component

**Comment by slromero-indra** [comment]
## Visualización en el frontal
Frontal nuevo sin tema: http://caibter.indra.es/sites/indra2017/ca/introduccion/
Fronta nuevo con tema: http://caibter.indra.es/sites/indra/ca/pag_bb/

## Inclusión botón en tinymce
Respecto a tinymce, se ha incluido un nuevo elemento en el toolbar:

![image](https://user-images.githubusercontent.com/17451407/33900008-771373d0-df6d-11e7-97a7-d3c4c89d4570.png)

Tras pulsarlo, se puede rellenar un formulario con los datos necesarios (se ha incluido un botón de borrar para poder borrar cómodamente un botón incluido de manera errónea):
![image](https://user-images.githubusercontent.com/17451407/33900057-94187af2-df6d-11e7-89c6-7b4028e6bdba.png)

Resultado:
![image](https://user-images.githubusercontent.com/17451407/33900083-a4b2a75c-df6d-11e7-97d0-3d6f92b0d855.png)

**Comment by slromero-indra** [comment]
Visualización del resultado final.

Frontal por defecto:
http://caibter.indra.es/sites/indra/ca/demo_listado_y_botones_mic/

Tema 2017
http://caibter.indra.es/sites/indra2018/ca/demo_listado_y_botones_mic/

**Comment by sgelabert-dgtic** [comment]
Al desar la pàgina que té incoporada el botó no s'actualitzen els canvis en el camp URL o icona, és a dir, una vegada inserit el valor inicial no emmagatzema canvis sobre aquests dos camps
