### ISSUE TITLE
Incorporació llistes de valors MIC

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#103]
Es sol·licita incorporar utilitat a l'editor TinyMCE per presentar una llista de valors amb l'estil MIC.
Valorar si es pot afegir com a pluggin Tiny o bé s'ha de modelar com a component

**Comment by slromero-indra** [comment]
Visualización del resultado final.

Frontal por defecto:
http://caibter.indra.es/sites/indra/ca/demo_listado_y_botones_mic/

Tema 2017
http://caibter.indra.es/sites/indra2018/ca/demo_listado_y_botones_mic/

**Comment by slromero-indra** [comment]
Hemos mejorado el código por un problema que habíamos detectado por solapamiento.
