### ISSUE TITLE
Mal funcionament amb les etiquetes <iframe>

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#104]
Hem detectat un mal funcionament amb les etiquetes <iframe>.
Al Microsite "Retribucions legistlatura 2015-2019" (id_microsite=6965), té uns pdf's incrustats mitjançants <iframe> i quan accadeixes a la web es veuen correctament, es a dir, es visualitzen els pdf's.
Aquest Microsite utilitza la versió "Microsites públic, segona versió". Quan actualitz a la darrera versió (Microsite versió 2015) i accedeixo a la web, ja no es mostren els pdf's i demana si els vols descarregar.
Si aplic el tema2017, tampoc ho mostra.
Adjunt captures de pantalla.
captura1.jpg (versió microsite: Microsites públic, segona versió )
![captura1](https://user-images.githubusercontent.com/26536678/35389956-fd73ff24-01d9-11e8-97cf-91797542e49b.jpg)

captura2.jpg (versió microsite: Microsite versió 2015, tema per defecte)
![captura2](https://user-images.githubusercontent.com/26536678/35389982-1754a8bc-01da-11e8-9a81-540439b4e7c5.jpg)
 
captura3.jpg (versió microsite: Microsite versió 2015, tema 2017)
![captura3](https://user-images.githubusercontent.com/26536678/35389995-2a33b54a-01da-11e8-8f91-9747f549d25d.jpg)

**Comment by dmadronal-indra** [comment]
Buenas se ha actualizado la aplicación para solventar esta problemática.
