### ISSUE TITLE
Varis bugs amb el tema 2017

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#105]
Microsite: iea.caib.es

1 Llistats de fitxes:

	- Quan cerques un element del llistat i accedeixes a ell, a la part de dalt surt el texte "Volver al listado de noticias" (adjunt captura de pantalla captura1.jpg) tant en Català com en Castellà. 
	url: http://www.caib.es/sites/institutestudisautonomics/ca/n/decret_252013_de_24_de_maig_de_modificacio_del_decret_542002_de_12_dabril_pel_qual_es_regulen_les_indemnitzacions_per_rao_del_servei_del_personal_al_servei_de_ladministracio_autonomica_de_les_illes_balears_i_del_decret_872012_de_16_de_novembre_davaluacio_i_certificacio_de_coneixements_de_llengua_catalana-57292/

	- Quan accedeixes al llistat de normatives, el títol és "Normativa Tots " y a la dreta posa tots els anys. Pero si poses l'idioma en castellà, et posa per defect quan no hauria de posar res, ja que no hi ha normatives. (captura12.jpg i captura13.jpg)

	- Hi ha fitxes que duen un document pdf adjunt i en alguns casos es veu la icona i en uns altres no (captura2.jpg i captura3.jpg) .
	url de la captura2.jpg: http://www.caib.es/sites/institutestudisautonomics/ca/n/decret_3-2017/
	url de la caputra3.jpg: http://www.caib.es/sites/institutestudisautonomics/ca/n/llei_51996_de_18_de_desembre_de_diverses_mesures_tributaries_i_administratives-63172/

	- Al cercador de la Normativa autonòmica quan cerques tot un any, per exemple 2017, i passes a la pàgina següent no es veu la normativa que toca de l'any en qüestió, passa automàticament a l'any 1983. Pareix que no funciona el botó de "següent".
	url: http://www.caib.es/sites/institutestudisautonomics/ca/l/normativa-8165/

2 Lletra capital:
	- Quan  poses en texte que va en les etiquetes <h2></h2>, la primera lletra de cada paraula la posa amb majúscules. (captura4.jpg i captura5.jpg)
	url: http://www.caib.es/sites/institutestudisautonomics/ca/colleccio_legislativa-49119/

3 Pàgines amb taules: 
	- Quan utilitzes taules, al backoffice queda tot ben quadrat, es a dir, els espais entre files són tots iguals. Però al front office no. (captura6.jpg i captura7.jpg)
	url: http://www.caib.es/sites/institutestudisautonomics/ca/colleccio_legislativa-49119/

4 Espais entre paràgrafs:
	- Quan poses una sèrie de paràgrags un darrera l'altra, els espais entre ells són inexistents. En canvi, al backoffice es veu bé. (captura8.jpg i captura9.jpg)
	url: http://www.caib.es/sites/institutestudisautonomics/ca/n/llei_72010_de_21_de_juliol_del_sector_public_instrumental_de_la_comunitat_autonoma_de_les_illes_balears-58891/

5 Enllaços:
	- Quan es posen textes amb enllaços, no es pot distingir del que és enllaç o texte. (captura10.jpt i captura11.jpg)
	url: http://www.caib.es/sites/institutestudisautonomics/ca/n/llei_72010_de_21_de_juliol_del_sector_public_instrumental_de_la_comunitat_autonoma_de_les_illes_balears-58891/

Microsite jcca.caib.es

1- Llistats de documents:
	- Passa el mateix amb els icones pdf dels documents. Tots aurien de dur l'icona. (captura14.jp)
	- Els títols els posa amb majúscules. (captura15.jpg i captura16.jpg)

	url: http://www.caib.es/sites/jcca/ca/l/recursos_especiales_indice_anual-1180/2017/
[captures.zip](https://github.com/GovernIB/gusite/files/1736004/captures.zip)

**Comment by dmadronal-indra** [comment]
Hemos revisado los puntos 1.1, 1.2,1.4,2,4,5,6.2.

Referente al punto 1.3 y 6.1 (tema de los iconos), la imagen que se muestra corresponde con el mime type almacenado en la aplicación. hemos estado revisando y haciendo pruebas y al subir el documento se almacena el mime type correspondiente, y no logramos reproducir que se almacene con el formato application-x-download, que es el correspondiente al icono que se muestra.

Referente al punto 3 (tema de las tablas) no es un problema de la tabla sino del tamaño del texto de dentro de cada celda., en el Backoffice no se están usando los estilos de la web, y el tamaño del texto es inferior, en la web se aplica el tema correspondiente y para el tema2017 el tamaño es ligeramente superior, lo que provoca que los altos de fila sean superiores, y aparezcan márgenes.  Para solucionarlo, deberían fijar el estilo del texto de dentro de cada celda.

**Comment by slromero-indra** [comment]
Respecto al problema que un documento pdf, en algunos caso se vea el icono y en otros no, depende del campo 'dcm_tipo' de la tabla 'gus_docus. Ese campo indica el tipo 'mimetype' del fichero y, a partir de dicho valor, cambia el icono a uno predefinido (icono pdf, word, etc..) o genérico (el fichero en blanco). Podéis realizar la siguiente consulta para ver un resumen rápido de los ficheros con terminación pdf que les afecta este problema (y ya de paso podemos observar otros ficheros que pudieran tener el mismo problema)? 

> 
> select distinct reverse(substr ( reverse (dcm_nombre),0, 4)) terminacion, dcm_tipo, count(*) cuantos
>  from gus_docus
>  group by reverse(substr ( reverse (dcm_nombre),0, 4)), dcm_tipo
>  order by  reverse(substr ( reverse (dcm_nombre),0, 4));

**Comment by bgarcia-dgtic** [comment]
Hola,
Ens hem adonat que els microsites es veuen desconfigurats. Els continguts centrals de d'informació apareixen després del llistat de pàgines. També apareixen uns punts a l'esquerra del llistat de pàgines. Adjunt captura.

![captura 3](https://user-images.githubusercontent.com/26536678/37595741-35eb4bea-2b7a-11e8-85a4-6cd439646c2d.PNG)
![captura 2](https://user-images.githubusercontent.com/26536678/37595924-c64b449c-2b7a-11e8-9de5-9d98c049c4bc.PNG)

div#info {
    float: right;
    width: calc(100% - 17em);
}

**Comment by dmadronal-indra** [comment]
Buenas,
El cambio del menú (puntos a la izquierda )está corregido en el ultimo commit,  hemos compilado el tema para que lo podais subir.

el otro punto lo revisamos, parece que afecta solo a determinados tamaños de pantalla.

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado y probado el tema, ya no se reproducen los errores indicados.

**Comment by bgarcia-dgtic** [comment]
Hola,

Referent al punt 1.2 i 5, veig que encara no estan resolts.
El punt 1.2:  Quan accedeixes al llistat de normatives en català, el títol és "Normativa Tots " y a la dreta posa tots els anys (captura1.jpg. Però si poses l'idioma en castellà, et posa per defecta l'any 2015, quan no hauria de posar res ja que no hi ha normatives (captura2.jpg).
Captura1.jpg
![captura1](https://user-images.githubusercontent.com/26536678/37951121-98847980-319b-11e8-9a96-97d736b9eb08.jpg)
captura2.jpg
![captura2](https://user-images.githubusercontent.com/26536678/37951129-9fb6750a-319b-11e8-91c3-3c59c0f240ec.JPG)

Referent al punt 5, els enllaços segueixen sense destacar.
![captura3](https://user-images.githubusercontent.com/26536678/37951275-2c636f08-319c-11e8-8d80-48263620ace6.JPG)

**Comment by dmadronal-indra** [comment]
Buenas, 
Hemos actualizado el tema para que el estilo de los enlaces de las noticias afecte a cualquier resolución.

Referente al tema del listado de noticias, la corrección anterior conseguimos reproducirla  modificando la fecha de caducidad de la noticia, lo que provocaba que apareciese en el listado de años, y aplicamos una solucion a la misma. Al parecer existe otra casuística relacionada con traducciones sin título que provocaba un comportamiento similar.
 
Hemos detectado y corregido el problema con las traducciones sin título, y hemos estado realizando más pruebas para verificar el funcionamiento, pero esta casuística solo es posible reproducirla modificando directamente la BBDD ya que actualmente no se permiten registros de idioma sin título (estos son eliminados), por lo que es posible que se trate de un caso con datos antiguos.

Con esta última corrección no hemos podido reproducir el problema, Podéis verificar si se ha solucionado  o enviarnos una exportación del microsite para verificar si se ha solventado el problema o se trata de otra problemática?
