### ISSUE TITLE
Problemes amb els enllaços interns

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#106]
Bon dia,

Hem detectat que els enllaços a pàgines del mateix microsite no estan funcionant. Fins ahir funcionaven correctament.
Hem importat el microsite a l'entorn de proves i dona el mateix error. ID microsite a proves: 6405
Adjunt error del log a proves: 

https://proves.caib.es/sites/permisosivacances/ca/contenido.do?idsite=6405&cont=69119

2018-03-20 09:00:09,306 ERROR [es.caib.gusite.front.home.HomeController] (http-10.215.9.207-18080-1)  [Configuracion microsite]: Se debe indicar algún microsite
2018-03-20 09:00:09,312 ERROR [es.caib.gusite.front.general.BaseViewController] (http-10.215.9.207-18080-1) java.lang.NullPointerExceptionError intentando obtener el microsite a partir de su key
2018-03-20 09:00:16,714 ERROR [es.caib.gusite.front.contenido.ContenidoController] (http-10.215.9.207-18080-8) Contenido no encontrado: contenido.do

Adjunt captura de pantalla:
![captura1](https://user-images.githubusercontent.com/26536678/37642603-0f61ebc4-2c1e-11e8-84b8-ca15e5dd1457.JPG)
![captura2](https://user-images.githubusercontent.com/26536678/37642606-1178e7a0-2c1e-11e8-8e0b-60cc083f37f6.JPG)

**Comment by dmadronal-indra** [comment]
estamos evaluando posible solución

**Comment by dmadronal-indra** [comment]
Buenas,
Estamos tratando de localizar el origen del problema, a priori hemos detectado que parece reproducirse solo cuando se accede a la raiz del site (https://proves.caib.es/sites/permisosivacances/) y estos enlaces estan ubicados en la página de inicio configurada en Congiguració general-->pagina d'inici. si se accede al contenido a través de la uri no se reproduce el problema(https://proves.caib.es/sites/permisosivacances/ca/pagina_dinici-58537/).
os mantendremos informados.

**Comment by dmadronal-indra** [comment]
Buenas, hemos localizado lo que parece el origen del problema.

El desarrollo para evitar que en las url que tuvieran parámetros se eliminase la ultima / ej:
.../sites/mapatema2017/ca/ **n/2018/?** mcont=1661 -->.../sites/mapatema2017/ca/ **n/2018?** mcont=1661

Un efecto colateral que no se tuvo en cuenta es que al eliminar la última barra, las url relativas dejan de formarse igual, y pasan de tener la estructura …./n/2018/ a …/n/ , por lo que luego el controlador no sabe interpretarlas.

Existe un parche de fácil aplicación que consiste en “volver atrás el cambio” en teoría en unas 3  horas debería estar (incluyendo pruebas y demás), pero las url volverán a tener la misma estructura que antes.

para el caso de que se quiera mantener el desarrollo y encontrar una solución que contemple el borrado de la ultima barra cuando se añaden parametros, habria que revisarlo más en profundidad, a priori no le vemos facil solución.

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos realizado las modificaciones para añadir nuevamente la barra en la url. Hemos realizado multiples pruebas y parece funcionar correctamente.

**Comment by dmadronal-indra** [comment]
Buenas, 
además hemos actualizado el tema2017 para evitar que el texto de las noticias aparezca en 3 columnas.
