### ISSUE TITLE
Visiualització llistats de documents

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#107]
Hola,

Quan es cree un llistat de documents amb informació adicional a cada element de la llista (Captura1.jpg), aquesta informació no es veu quan el llistat s'insereix mitjançant l'element "Component" (Captura2.jpg i Captura3.jpg).
No obstant si enllaçam una pàgina dirèctament amb el llistat si que es veu correctament (Captura4.jpg i Captura5.jpg)
![captura1](https://user-images.githubusercontent.com/26536678/37713420-33931348-2d17-11e8-92f4-5a426bec589b.JPG)
![captura2](https://user-images.githubusercontent.com/26536678/37713423-359f81b2-2d17-11e8-9c04-adc4121e1a39.JPG)
![captura3](https://user-images.githubusercontent.com/26536678/37713424-37c9a4e0-2d17-11e8-9097-1bad33a15264.JPG)
![captura4](https://user-images.githubusercontent.com/26536678/37713427-3981ea2c-2d17-11e8-901d-f3b08cd0cc99.JPG)
![captura5](https://user-images.githubusercontent.com/26536678/37713430-3b4da09e-2d17-11e8-8fed-30ab66239d4d.JPG)

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos modificado el tema 2017 para permitir que se visualice el texto de los documentos.
