### ISSUE TITLE
Eliminar adreça "Govern" del peu de pàgina 

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#108]
Es sol·licita eliminar l'adreça que apareix en el peu de pàgina " C/ de la Llotja, 3 - 07012 Palma" que surt per defecte quan no estàs en una UA determinada. Adjunt captura de pantalla. ![microsite](https://user-images.githubusercontent.com/17268396/38012315-3e26afa0-3261-11e8-8441-4a8d6985f568.jpg)

**Comment by dmadronal-indra** [comment]
buenas ,
hemos actualizado el tema para que no aparezca el enlace.
