### ISSUE TITLE
Visualització llistat tipus Mapa

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#109]
Hola,

Ens hem adonat d'un mal funcionament amb els llistats tipus mapa. Quan crees una pàgina a l'arbre de menú i l'enllaces directament amb el llistat mapa, no mostra el mapa correctament.
![captura1](https://user-images.githubusercontent.com/26536678/38483672-18b853b4-3bd4-11e8-9dbf-6bd7e775fef6.JPG)
![captura2](https://user-images.githubusercontent.com/26536678/38483680-210d73e6-3bd4-11e8-8c1b-f5732898835a.JPG)

No obstant, si afegeixes el llistat de mapa com a component, sí que mostra el contingut correctament.
![captura3](https://user-images.githubusercontent.com/26536678/38483717-3c3ea1f8-3bd4-11e8-8bfc-3bf67c0add77.JPG)

**Comment by dmadronal-indra** [comment]
Buenas, hemos detectado que también afecta a la visualización de las ubicaciones concretas, y que parece afectar solo al tema 2017, lo estamos investigando.

**Comment by dmadronal-indra** [comment]
Buenas hemos actualizado el tema2017 con las modificaciones.
