### ISSUE TITLE
No es mostra el mapa web

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#110]
Hola,

Quan es crea una pàgina i s'enllaça amb el mapa web, aquest no es mostra, no fa res. Adjunt captures de pantalla.
url microsite: https://proves.caib.es/sacmicroback/index.do?idsite=5985#
![captura1](https://user-images.githubusercontent.com/26536678/39348939-6aebdaba-49f9-11e8-835c-144fd0242f74.JPG)

Quan premeu sobre "Mapa", no fa rés.
![captura2](https://user-images.githubusercontent.com/26536678/39349539-93ec2990-49fb-11e8-8596-06b995f98097.JPG)

**Comment by sgelabert-dgtic** [comment]
Ens demanen per l'estat d'aquesta incidència. Heu pogut avançar?

**Comment by dmadronal-indra** [comment]
Bones, 
Encara no hem pogut avançar, li donem prioritat i us informem.

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos realizado una actualización en los temas que solventa esta problemática. 
Para verificarlo es suficiente con actualizar el tema2017.
