### ISSUE TITLE
Problema amb els apòstrofs en els títols dels components

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#113]
Bon dia,
Hem creat un component de tipus "enllaç" i visualització "Botó". Si en el títol del component es posa algun apòstrof, la pàgina on es troba aquest component no es visualitza. No obstant, si la visualització és "Llistat", la pàgina es mostra correctament.
Adjunt captura de pantalla.
![captura](https://user-images.githubusercontent.com/26536678/40839664-d168a708-65a3-11e8-9aaf-119f6ea1fa83.JPG)

**Comment by dmadronal-indra** [comment]
Buenas, 
Hemos actualizado la aplicaión, ¿lo podeis revisar?

**Comment by bgarcia-dgtic** [comment]
Bon dia,
Funciona correctament però ara hem detectat uns altres errors.
1- Si el nom del component porta apòstrof i la visualització és "llistat", la pàgina on es troba el component no es visualitza.
![captura1](https://user-images.githubusercontent.com/26536678/41226478-e2aa0dd8-6d71-11e8-928c-c80ee1ad51f0.JPG)

2- També, quan el nom del component porta apòstrof, no deixa vincular-lo al contingut d'una pàgina.
![captura2](https://user-images.githubusercontent.com/26536678/41226684-83f000bc-6d72-11e8-8197-a98c6bc9a85b.jpg)

**Comment by dmadronal-indra** [comment]
Buenas, 
hemos actualizado la aplicación, ¿lo podeis verificar?
