### ISSUE TITLE
Problema títol formulari de contace

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#114]
Hola,
Hem detectat un problema amb els títols dels formularis de contacte.
Quan la orientació del menú és horitzontal i a l'arbre de contingut no hi ha cap carpeta de primer nivell (captura1.jpg) visible, el títol dels formularis de contacte no es mostren (captura2.jpg)

Captura1.jpg
![captura1](https://user-images.githubusercontent.com/26536678/41035562-524ba9f0-698d-11e8-83f4-6ad4cfa89ccc.JPG)

Captura2.jpg
![captura2](https://user-images.githubusercontent.com/26536678/41035575-60820a1e-698d-11e8-8439-81f5ea17a1bb.JPG)

**Comment by dmadronal-indra** [comment]
Buenas hemos modificado el tema 2017. ¿Lo podeis verificar en vuestros entornos?
