### ISSUE TITLE
Efecte estrany muntatge menú horitzontal

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#115]
Es decteta un comportament estrany a l'hora de presentar el menú horitzonal de GUISTE. Pareix que primer es presenta en vertical per, a continuació, maquetar-se en horitzontal.
Es sol·licita revisar la presentació per evitar o en tot cas, ocultar aquest efecte.

**Comment by sgelabert-dgtic** [comment]
S'envia per correu exportació d'un microsite d'exmple a fi de reproduir el problema

**Comment by dmadronal-indra** [comment]
Buenas, 
Hemos añadido unos cambios al tema2017 y a los resources de la aplicación y ya no se muestra el menú vertical. referente al microsite en cuestion, comentar que tienen sobrescritas algunas páginas del tema 2017, por lo que deberán editar la plantilla general/menu para incorporar los cambios.
