### ISSUE TITLE
Problema amb els idiomes dels titols dels components

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#116]
Hola,
He creat un llistat de tipus "Enllaç" i he emplenat la part catalana i castellana. A continuació he creat un component d'aquest llistat i també he emplenat els dos idiomes. Quan la visualització del component es "Botó", de cara al públic sempre mostra el títol del component en català (captura1.jpg)
![captura1](https://user-images.githubusercontent.com/26536678/41911471-00ad7c34-794d-11e8-86da-98ea8d9f3ea3.JPG)

Quan la visualització és "Llistat", de cara al públic sempre mostra el nom del component (captura2.jpg)
![captura2](https://user-images.githubusercontent.com/26536678/41911569-4e2cce38-794d-11e8-865d-b5146dc68b3f.JPG)

Ambdós casos hauria de mostrar el títol del component amb l'idioma corresponent.

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos revisado esta casuistica, y solventado un problema al desplegar la aplicación. Lo podeis validar?

**Comment by episano-dgtic** [comment]
Lucia me acaba de comentar que el problema persiste en el caso de componentes configurado de tipo botón. Y lo he revisado en tipo de listado y no me cambia a castellano.

**Comment by episano-dgtic** [comment]
Perdón l aincidencia hacía referencia título, y el uso del nombre ó título.
