### ISSUE TITLE
Canvi url Google Analytics

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#117]
Bon dia,
Hem detectat que la url de Google Analytics ha canviat. Quan prems el botó "Analytics" del gestor (captura1.jpg) et redirecciona a una nova pàgina (captura2.jpg).
![captura1](https://user-images.githubusercontent.com/26536678/43199322-db6d581e-9011-11e8-9914-051cd777f243.JPG)
![captura2](https://user-images.githubusercontent.com/26536678/43199325-de70f8e0-9011-11e8-90cd-c48e81a9c1d3.JPG)

Quan prems el botó "Analytics", hauria de redireccionar a url "https://marketingplatform.google.com/about/analytics/"
![captura3](https://user-images.githubusercontent.com/26536678/43199398-1547b200-9012-11e8-9fd6-ae1973f7cd3b.JPG)

**Comment by dmadronal-indra** [comment]
lo revisamos

**Comment by dmadronal-indra** [comment]
buenas, se ha modificado la url.
