### ISSUE TITLE
Iconografia: Incluir nueva iconografia de archivo (LibreOffice). Tb. se indique dicha iconografia el tipo fichero al incluirlos backoffice o en la página. 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#118]
Se debería incluir nueva iconografia de archivo (LibreOffice y openoffice) como opción pantalla: Calc, writer, impress. Para la gestión de páginas de contenidos. Adjunto imagen
![iconos_archivo](https://user-images.githubusercontent.com/17451683/43383340-fd68128e-93da-11e8-93b3-cc9a14a96570.gif)

No olvidar tener en cuenta que se pueden introducir estos nuevos tipos de ficheros, en el backoffice tanto en ficheros comunes, específicos de página, en los listados, agenda para que se tenga en cuenta la nueva iconografía tanto en el back como en el front. Actualmente al introducirse aparece un icono vacío en blanco, o del equivalente de office.

**Comment by dmadronal-indra** [comment]
Lo revisamos

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la aplicación, lo podeis validar?

**Comment by sgelabert-dgtic** [comment]
Els icones pujat tenen molt poca qualitat i no es veu pràcticament res. S'haurien de canviar.
![image](https://user-images.githubusercontent.com/17268396/44512653-92fdc580-a6bb-11e8-8e2d-8dac9b763ede.png)

**Comment by dmadronal-indra** [comment]
Hemos actualizado los iconos indicados, lo podeis validar?

**Comment by episano-dgtic** [comment]
En general que va bien, sólo un par de puntualizaciónes. 

Al visualizar la página aparecen los iconos "baja calidad" pese a que en el backoffice están los "buenos"
![visualizacion_nuevaiconografia](https://user-images.githubusercontent.com/17451683/44983646-2a93cb80-af7a-11e8-8a06-5bcf72180892.gif)
En la visualización de los eventos de la agenda y listados no aparece iconografía nueva. 
![agenda_iconografia](https://user-images.githubusercontent.com/17451683/44983963-6713f700-af7b-11e8-9971-cf5162036c33.gif)
![listado_tipowriter](https://user-images.githubusercontent.com/17451683/44984074-c114bc80-af7b-11e8-9951-3df1df2745dd.gif)

**Comment by slromero-indra** [comment]
Buenas, hemos subido los siguientes cambios. Actualizado la resolución en el frontal nuevo: 

URL: http://caibter.indra.es/sites/indra/ca/iconos/
![imagen](https://user-images.githubusercontent.com/17451407/45145994-396cbf00-b1c2-11e8-9480-6bc94421e883.png)

Hemos actualizado los 2 temas para que reflejen en agenda los archivos de tipo odt, ods y odp (hay que generar de nuevo el zip, y volver a subirlo para que se vean reflejados los cambios):

![imagen](https://user-images.githubusercontent.com/17451407/45146520-5655c200-b1c3-11e8-90da-ef9adf65af37.png)
![imagen](https://user-images.githubusercontent.com/17451407/45146558-6f5e7300-b1c3-11e8-9242-4e613a0f8f28.png)
![imagen](https://user-images.githubusercontent.com/17451407/45146577-771e1780-b1c3-11e8-8c82-05a82a141ad2.png)

URL Eventos: 
http://caibter.indra.es/sites/indra/ca/agenda/20180908
http://caibter.indra.es/sites/indra/ca/agenda/20180907
http://caibter.indra.es/sites/indra/ca/agenda/20180906
