### ISSUE TITLE
Problema incluir un enlace a un icono incluido en una página de contenido. 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#119]
Si se trata de incluir un enlace a un icono incluido previamente en una página de contenido, no se activa en enlace pese a que se acepte en en multiples ocasiones. Sólo funciona en el caso de tener seleccionado un icono y algo de texto. 
![enlace_icono](https://user-images.githubusercontent.com/17451683/43384067-25c445f2-93dd-11e8-9a43-e836bf28ce39.gif)

**Comment by dmadronal-indra** [comment]
Lo revisamos.

**Comment by dmadronal-indra** [comment]
Buenas, 
Hemos revisado esta casuística, parece que se trata de un bug del tiny mce, hemos revisado si existía un parche para solventarlo con la versión actual, pero no lo localizamos. 

Para poder solventarlo es necesario actualizar la versión del Tinymce, hemos realizado varias pruebas, actualizando la versión del tiny a la 4.8.1(la más reciente) en gusite y por lo que parece  ya no se reproduce el problema, pero tiene el inconveniente que ha dejado de ser compatible con navegadores  IE8,IE9 y IE10.  (https://www.tiny.cloud/docs/get-started/system-requirements/)

Según la documentación del TinyMCE, si es necesaria la compatibilidad con estos navegadores se debería usar  una versión 4.5.X, hemos probado a actualizar el Tinymce a la última versión disponible de esta rama (4.5.9), y ya se podían asignar links a las imágenes, hemos realizado una batería de pruebas y a priori no se han detectado problemas con los diferentes plugins del tiny (inserción de archivos, iconos, componentes etc..).

¿Quereis que actualicemos la versión del tinymce a la versión 4.5.9?

**Comment by sgelabert-dgtic** [comment]
Ok, em pareix correcte. Passeu a la versió 4.5.9

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la versión del tiny a la 4.5.9, lo podeis validar?

**Comment by episano-dgtic** [comment]
Buenas hemos detectado que al cambiar el tiny han desaparecido 2 opciones del botón del editor avanzado y básico. Concretamente lo relacionado con la creación de listas(numeradas y no numeradas).

**Comment by dmadronal-indra** [comment]
Lo estamos revisando.

**Comment by dmadronal-indra** [comment]
Buenas, 
Hemos revisado este tema, ¿Lo podéis validar?

**Comment by episano-dgtic** [comment]
okey
