### ISSUE TITLE
En el arbol de menu, no funciona el cambio de orden de las subcarpetas.

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/gusite#12]
Numero: 12
Creació: 2016-02-16 07:55:28.713000
En el arbol de menu, no funciona el cambio de orden de las subcarpetas. Si tratas de moverlas siembre se colocan como última opción ó primera, no en medio de dos páginas en el mismo nivel.

**Comment by episano-dgtic** [comment]
Lo he testeado y peor que antes.
Si trato de mover la carpeta con sus contenidos desplegados, entre otra carpeta desplegada no me deja. Y si plego las carpetas al cambiar el orden desparece con sus páginas.  
Si las subcarpetas no tienen páginas deja moverlo sin problemas.

**Comment by dmadronal-indra** [comment]
Probado en  caibter: "Prueba URI estela."

**Comment by episano-dgtic** [comment]
PErfecto

**Comment by sgelabert-dgtic** [comment]
Quan les carpetes principals ("vermelles") que tenen continguts i estan plegades, no funciona correctament el canvi d'ordre. Desapareixen de l'arbre.

**Comment by episano-dgtic** [comment]
No funciona el cambio de subcarpetas.. sencillamente no se mueven

**Comment by slromero-indra** [comment]
Buenas, está resuelta todas las incidencias cuando se mueve las carpetas de nivel 2 (marcadas con el color amarillo) y también los siguientes errores:
- Mover sobre sí misma.
- Mover sobre un div erróneo o invalido (fuera del árbol).
- Al hacer un doble click rápido (que en verdad, intentaba moverse sobre sí misma).
  Se ha tenido que reescribir gran parte del código javascript que era un desastre para cuando se mueven las carpetas amarillas.

Saludos!
