### ISSUE TITLE
No existe correspondencia archivopub.do?name=Funcions_mapa.js en el entorno sites

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#120]
Archivopub.do funciona sin problemas  pasando como parámetros microsite e id del fichero:
https://www.caib.es/sacmicrofront/archivopub.do?ctrl=MCRST145ZI21584&id=21584
https://www.caib.es/sites/carchivopub.do?ctrl=MCRST145ZI21584&id=21584
De hecho en sites funciona en varios caso
https://www.caib.es/sites/ca/archivopub.do?ctrl=MCRST145ZI21584&id=21584
https://www.caib.es/sites/ca/xxxxxx/archivopub.do?ctrl=MCRST145ZI21584&id=21584

Pero no existe ese comportamiento pasando como parámetro el nombre del fichero. 

Un ejemplo que usa esta funcionalidad en sacmicrofront:  https://www.caib.es/sacmicrofront/contenido.do?mkey=M145&lang=CA&cont=53106
         Concretamente va bien la carga de : https://www.caib.es/sacmicrofront/archivopub.do?name=Funcions_mapa.js

En cambio pasando al entorno sites:
       http://www.caib.es/sites/atmosfera/ca/previsio_de_la_qualitat_de_laire-53106/
       No se carga http://www.caib.es/sites/atmosfera/ca/previsio_de_la_qualitat_de_laire-53106/archivopub.do?name=Funcions_mapa.js
![carga_archivopub](https://user-images.githubusercontent.com/17451683/44783255-0c008f80-ab8a-11e8-8d19-973ed05fc49f.gif)

**Comment by dmadronal-indra** [comment]
Buenas, 
por lo que estamos viendo hay una funcionalidad parecida ya implementada, pero requiere que se le pase el idsite, ej: 

http://www.caib.es/sites/archivopub.do?name=Funcions_mapa.js&idsite=145,  
o 
http://www.caib.es/sites/atmosfera/ca/previsio_de_la_qualitat_de_laire-53106/archivopub.do?name=Funcions_mapa.js&idsite=145 
Si se añade el parámetro idsite si que retorna el fichero, ¿esto es lo que necesitais?

**Comment by episano-dgtic** [comment]
No era exactamente lo que pedíamos.. pero la verdad es que con la opción que me das salgo del paso. Así que cierro la petición.
