### ISSUE TITLE
Bug accés Microsite versió "Microsite versió 2015" i accés "Restringit"

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#121]
Bon dia,
Hem detectat un mal funcionament a l'hora d'accedir a un Microsite que té la versió "Microsite versió 2015" i l'accés és "Restringit". Exemple:
 url pública: https://intranet.caib.es/sites/portaldelpersonal/   
Backoffice: https://intranet.caib.es/sacmicroback/index.do?idsite=2405 
![captura](https://user-images.githubusercontent.com/26536678/45217422-43ff8500-b2a4-11e8-8b3c-4efc22d0a243.JPG)

Hi ha usuaris que quan accedeixen a la url pública i introdueixen l'usuari i contrasenya, els dóna el següent error..
![microsite_fun-fad_01](https://user-images.githubusercontent.com/26536678/45217147-48776e00-b2a3-11e8-9519-e824b64cc5a1.png)

No obstant, si tornen a rere i després tornen a accedir, no mostra l'error i poden veure el contingut del Microsite.
He consultat els logs del servidor però no he pogut esbrinar rés
L'usuari en qüestió és u139636 i la prova ha estat entre les 10:05 i 10:07 aproximadament.
Us adjunt els logs per veure si vosaltres podeu esbrinar rés.
[server.log](https://github.com/GovernIB/gusite/files/2360914/server.log)
[stdout-stderr.log](https://github.com/GovernIB/gusite/files/2360915/stdout-stderr.log)

**Comment by dmadronal-indra** [comment]
Buenas, nos podeis dar más información?
Hemos realizado varias pruebas y no conseguimos reproducirlo, hemos probado a acceder al microsite y nos ha ido bien, además en el log no se aprecia demasiado. hay algunos errores del login module, pero estos no pertenecen a la la aplicación.
- ¿Os ocurre solo con algunos usuarios? 
- ¿A estos usuarios siempre les ocurre lo mismo, o son problemas intermitentes?
- ¿Que roles tienen los usuarios?

**Comment by bgarcia-dgtic** [comment]
Hola,
Pareix que només passa amb els usuaris que no tenen cap rol relacionat amb GUSITE. Hem fet vàries proves amb usuaris que no tenen rol de GUSITE i sempre passa el mateix, la primera vegada que entren dona error però quan entren per segona vegada no hi ha cap problema.
Els usuaris que tenen rol de GUSITE poden accedir sense problemes.

**Comment by dmadronal-indra** [comment]
buenas,
Por lo que hemos visto, es debido a que esos usuarios no tienen un rol definido en gusite.
Si cualquier usuario identificado en seycon puede tener acceso a los microistes restringidos, podríamos hacer uso del rol "tothom", de esta manera se resolvería el problema ¿Podemos hacer uso del rol tothom, o disponéis de un rol para indicar que una persona tiene acceso a los microsites restringidos?

**Comment by bgarcia-dgtic** [comment]
Hola,
Hem fet una prova de tornar a posar el microsite com estava abans, es a dir, versió "Microsite intranet" i accés "Restringit". (aquesta configuració el sistema utilitza "/sacmicrofront").
![imatge](https://user-images.githubusercontent.com/26536678/45475053-89580280-b73b-11e8-8b50-0aace9bc003e.png)
Amb aquesta configuració, els usuaris que estan identificats a seycon (tant si tenen algun rol de GUSITE com si no) poden accedir, es a dir, introdueixen el seu usuari i contrasenya i poden veure el contingut a la primera.

En canvi, si la configuració del microsite la canviam a versió "Microsite versió 2015" i accés "Restringit" (aquesta configuració el sistema utilitza "/sites"), és quan es produeix el problema abans esmentat.
![imatge](https://user-images.githubusercontent.com/26536678/45478104-78ab8a80-b743-11e8-93ce-46a1c6eda518.png)

**Comment by dmadronal-indra** [comment]
Buenas, es lo que os comentabamos, en esa configuracion se usa el rol "tothom". Entendemos pues que debemos usar este rol para permitir el acceso. actualizamos sites para que permita el acceso con este rol.

**Comment by bgarcia-dgtic** [comment]
Hola,
Disculpau-me, no havia entès bé. Podeu procedir a utilitzar el rol "tothom" a sites.

**Comment by dmadronal-indra** [comment]
buenas, hemos actualizado la aplicación, ¿lo podeis validar?
