### ISSUE TITLE
Error al incluir enlaces a páginas del microsite en los eventos de la agenda usando el pop-up contenidos

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#122]
Si en el evento de la agenda se incluye un enlace a un contenido del microsite, tanto en el campo descripción como en la url, usando el pop-up de navegación da problemas. 
![inclusion_enlacepagina](https://user-images.githubusercontent.com/17451683/45345211-ec179580-b5a5-11e8-857a-337df806cd01.gif)

![error_enlace](https://user-images.githubusercontent.com/17451683/45345028-73b0d480-b5a5-11e8-9491-62136194a32b.gif)

La url que se monta en ambos casos es:
https://intranet.caib.es/sites/eines/ca/agenda/contenido.do?idsite=157&cont=17186

Funciona si en lugar de agenda pone cualquier otra palabra
https://intranet.caib.es/sites/eines/ca/agendax/contenido.do?idsite=157&cont=17186

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos realizaro una actualización, ¿podeis verificarlo?
