### ISSUE TITLE
Incluir la política de cookies en los microsites

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#123]
Se debe incluir la política de cookies en los microsites con el mismo funcionamiento que web caib. De hecho si desean ir a más información debería remitir a la misma página de debería ir a la informacion(http://www.caib.es/govern/external/cookies.do)

Adicionalmente he incluido esta misma tarea en la sede. Por otro lado comentaros que deseamos que sea la misma cookie para todos los entornos de la caib. Con lo que si alguien acepta la política entrando en la sede no se lo vuelva a solicitar en web caib ó en algun microsite.

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la aplicación y el tema 2017 para poder mostrar la política de cookies.
¿Lo podéis validar?

**Comment by episano-dgtic** [comment]
Efectivamente si aceptas no te la solicita para web caib. Y al revés si la aceptas en caib no te la pide en microsite. Pero en gusite aparece un mensaje de este tipo, podría no tener referencia de la sesión?
![cookies](https://user-images.githubusercontent.com/17451683/48066500-14022e80-e1ce-11e8-9f9d-a2e6927f73e0.gif)

**Comment by dmadronal-indra** [comment]
Buenas,
hemos realizado una modificación para solventar el problema. 
¿lo podeis validar?

**Comment by episano-dgtic** [comment]
A mi me sigue pasando.

**Comment by episano-dgtic** [comment]
ya funciona

**Comment by episano-dgtic** [comment]
Cuando lo he desplegado en producción no me pide acepte las cookies,sin tener ninguna cookie de caib y al ver las que tengo al acceder aparecen varias:
![cookies_gusite](https://user-images.githubusercontent.com/17451683/49722348-d8db9b00-fc64-11e8-8c9c-c84ebedbd258.gif)

Cuando voy a la web caib solicita las cookies y incluye otras.. 
![cookies_webcaib](https://user-images.githubusercontent.com/17451683/49722356-dd07b880-fc64-11e8-8c43-c65b8e2ef468.gif)

Y en sede vuelve a solicitar las cookies y incluir otras locales
![cookies_seu](https://user-images.githubusercontent.com/17451683/49722583-6323ff00-fc65-11e8-8333-c96301d68bf5.gif)

Interesa que una vez aceptado en sede ó microsite o caib.. no vuelva a ser solicitado en la otra localización.

**Comment by dmadronal-indra** [comment]
buenas,
- Para mostrar el mensaje webcaib, y con esta modificación en sede y microsites usan el mismo metodo, si el navegador soporta localstorage, hace uso del almacenamiento local en lugar de las cookies, si no lo soporta utiliza las cookies. 

- Por lo que estamos viendo, parece que hay algun problema con la página de www.caib.es, ya que se está cargando con http en lugar de https, tal como ocurre con la sede. en ambos casos entendemos que deberian ser https. Esto impacta directamente con esta funcionalidad, ya que aunque sean la misma web, al cargarse una con http y otra con https hace que no se compartan ni las cookies ni el almacenamiento local, lo que provoca que vuelva a aparecer el mensaje.

**Comment by episano-dgtic** [comment]
Podéis cambiar el nombre al .js correspondiente para evitar que al no borrar temporales locales salga al usuario la pantalla principal así:
![capturaseu](https://user-images.githubusercontent.com/17451683/49926755-98765a00-febc-11e8-9a3a-1f9c75a120cf.png)

**Comment by dmadronal-indra** [comment]
Buenas, 
Hemos actualizado la sede (Revisión 503) para añadir un parametro en el fichero de propiedades para que podais forzar el refresco sin necesidad de cambios adicionales, unicamente modificando esta propiedad.

La nueva propiedad es "es.caib.seucaib.version.resources".
