### ISSUE TITLE
Migració arxius a FileSystem

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#125]
**Problema:**
- Serveis Web ens ha informat que la finestra de temps per realitzar el backup de les còpies diàries de la BBDD de GUSITE és insuficient. 
- El problema pensam que resideix en la taula GUS_DOCUS, la qual emmagatzema els binaris dels arxius que es gestionen en un microsite
**Objectiu:**
- Efectuar una migració dels arxius a FileSystem i eliminar la informació emmagatzemada en els camps BLOB de la BBDD de GUSITE

**Estat actual:**
- GUSITE té lògica per recuperar els arxius tant de BBDD com de FS. Des de la versió 1.2 i donat els problemes de rendiment (https://github.com/GovernIB/gusite/issues/41) s'optà per emmagatzemar els arxiu de manera duplicada tant a FS com a BBDD.
- No s'està fent backup diari de la taula GUS_DOCUS
- Es realitza un backup complet setmanal aprofitant finestra del cap de setmana

**Es sol·licita:**
- Analitzar si ens convé canviar l'organització dels Arxius a FS, per exemple, prescindint de la carpeta "nomic"
- Revisar consistència del procés de migració a FS
- Efectuar migració completa i configurar sistema perquè el frontal recuperi de FS. Per seguretat seguiria mantenint còpia dels arxius a BBDD per si es repeteixen problemes de rendiment.
- Si tot funciona correctament, llançar script de neteja de blobs a BBDD i eliminar lògica d'emmagatzematge duplicada.

**Comment by dmadronal-indra** [comment]
Buenas,
Estamos analizando este tema, ¿podríais facilitarnos el fichero de configuración jboss-service.xml del entorno de producción?

**Comment by bgarcia-dgtic** [comment]
Ok, demanam el fitxer.

**Comment by bgarcia-dgtic** [comment]
Adjunt arxiu.
[gusite-service.zip](https://github.com/GovernIB/gusite/files/2796199/gusite-service.zip)

**Comment by dmadronal-indra** [comment]
Buenas, hemos estado revisando este tema.
Por lo que hemos visto en la issue 41, los problemas de rendimiento venían de  la no indexación de determinadas tablas, por lo que al añadir los índices a la estructura dejaron de producirse estos problemas. 
 
 
- **1 Analitzar si ens convé canviar l'organització dels Arxius a FS, per exemple, prescindint de la carpeta "nomic"**
Sobre este punto, existen 3 tipos de ficheros, 
-> Los asociados a los microsites (ficheros comunes y ficheros asociados a un contenido) que se almacenan dentro de una carpeta identificada con el id de microsite,
-> Los que provienen de la importación de temas, por ejemplo imágenes y archivos js entre otros (básicamente los contenidos en la carpeta 'files' de cada tema ) que se almacenan en la carpeta "0"
-> Otros ficheros de microsites y archivo css de los temas. Todos los demás ficheros asociados a un microsite que no son archivos comunes y asociados a un contenido, (imágenes, documentos, etc ... asociados a listados, menús, componentes, etc...) además de los ficheros contenidos en la carpeta css de los temas importados, son almacenados en la carpeta nomic.
 
Actualmente este sistema de almacenaje está funcionando, el único posible inconveniente es si existiera alguna restricción con referencia al número máximo de ficheros en  un directorio, ya que en la carpeta nomic, es donde se almacenan la gran mayoría de los ficheros sin ninguna estructura.
 
 
- **2 Revisar consistència del procés de migració a FS**
 
Hemos revisado el proceso de migración, el proceso lanza la copia de los ficheros de BBDD a FS únicamente para aquellos que no existen en FS. Hemos realizado varias pruebas de exportación, y aunque en ocasiones la pantalla del explorador ha dado timeout, el proceso continua en background, en estos casos se puede ir siguiendo la ejecución del proceso a través de los logs.  En caso de que se quedase a medias no tiene un impacto negativo, y se podría volver a lanzar el proceso para exportar a FS los ficheros que no se hayan podido exportar. Si lo veis necesario podríamos revisar el proceso para que trabaje de manera asincrona, y evitar este inconveniente.
 
- **3 Efectuar migració completa i configurar sistema perquè el frontal recuperi de FS. Per seguretat seguiria mantenint còpia dels arxius a BBDD per si es repeteixen problemes de rendiment.**
Sobre este punto, según hemos visto en el fichero de configuración facilitado, ya está activada la opción de recuperar los ficheros de FS. En este caso todos los contenidos ya se están extrayendo de FS, y la BBDD únicamente sirve como respaldo, lo que quiere decir que no se recuperan los contenidos de la BBDD sino de FS. Teóricamente la migración a FS se realizó al pasar a la nueva versión 1.3 por lo que BBDD y FS deberían estar sincronizados y al ejecutarla de nuevo no debería encontrar ficheros a incorporar a FS.
 
- **4 Si tot funciona correctament, llançar script de neteja de blobs a BBDD i eliminar lògica d'emmagatzematge duplicada.**
En este punto, necesitamos saber si queréis que creemos los scrips de limpieza (a priori es setear a null el campo DCM_DATOS de la tabla GUS_DOCUS).
Para eliminar la lógica de almacenamiento, se podría usar el parámetro ya existente (almacenarEnFilesystem) para indicar el método de almacenaje a utilizar. 
En cualquier caso necesitaríamos que nos indiquéis como queréis proceder.
Si queréis podemos comentar telefónicamente los detalles.

**Comment by bgarcia-dgtic** [comment]
Bon dia,

Ahir horabaixa 10/02/2019 a les 17:16:01 n'Estela va llançar l'exportació d'arxius a FileSystem. A les 20:50 aproximadament, va accedir al frontal del Microsite dgtic.caib.es per veure si l'aplicació funcionava però va donar un error de proxy. Va intentar accedir a un parell de Microsites però tots donaven error de proxy.
La cuestió és que el procés de migració dels fitxers seguia funcionant (encara estava comprovant els fitxers que ja estaven a FileSystem). De fet, avui al matí encara estava en marxa, però els Microsites seguien mostrant error de proxy. 
A les 08:38 d'avui, hem reiniciat el servidor perquè els Microsites es poguessin veure. A partir d'aquest moment, el procés de migració s'ha aturat.
Hem sol·licitat els logs d'ahir i avui però no hem vist el motiu perquè els Microsites donaven error de proxy.
Serveis Web ens informen que no és un problema d'espai.
Seria possible poder fer l'exportació dels arxius per blocs o d'una altra forma, en lloc de fer-ho tot de cop?
Què en penseu?

**Comment by dmadronal-indra** [comment]
Comentado por teléfono:
Añadiremos un nuevo campo en la tabla de gusdocus para indicar si ha sido exportado a FS. Modificaremos el proceso de exportación para que solo consulte los ya exportados (teniendo en cuenta este campo). Añadiremos un botón para realizar esta verificación por lotes de N elementos, de manera que no se realice todo al mismo tiempo, evitando  que se sobrecargue la aplicación.

**Comment by dmadronal-indra** [comment]
Buenas, 
Hemos modificado la aplicación para que permita procesar los ficheros por tandas. Para probarlo es necesario actualizar la BBDD mediante el script gusite_update_schema_from_1.5_to_1.5.4.sql
Después de actualizar la aplicación, aparecerá la opción de seleccionar el número de elementos a tratar por el proceso de exportación a file system. 
También hemos tratado de optimizar el proceso, y debería ir más fluido.
¿Podéis verificarlo?
