### ISSUE TITLE
Visualización de los componentes en castellano aparecen en catalán. 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#129]
Al acceder en castellano a una página con componentes de listados con toda la información traduccida aparecen los datos en catalán. 
![sitibsa_pantallazo](https://user-images.githubusercontent.com/17451683/65030825-83919000-d940-11e9-9e3e-26c736abefa5.gif)

Esta incidencia ya se trató en #62

**Comment by episano-dgtic** [comment]
Si se configura el listado como ficha, va bien. El problema surge si es de tipo enlace(titulo y elementos), o lista documentos (título)

**Comment by dmadronal-indra** [comment]
Buenas hemos actualizado tanto el tema por defecto como para la plantilla 2017. 
¿Lo podeis verificar?

**Comment by episano-dgtic** [comment]
Está correcta.
