### ISSUE TITLE
Comentarios del diseño tema para la versión 2015

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/gusite#13]
Numero: 11
Creació: 2016-02-16 07:49:17.728000
Cuando eliges un apartado de una subcarpeta debe mostrarse despleago siempre. Resulta que con la opción A se muestra totalmente desplegado pero con el apartado B, no. (pàginaA.gif, pàginaB.gif)

**Comment by kitanibaladmin** [comment]
sgelabert-dgtic
2016-02-16 07:49:37.770000
- Attachments has changed:

Diff:

```

--- old
+++ new
@@ -1 +1,2 @@
 pàginaA.gif (139.6 kB; image/gif)
+pàginaB.gif (154.0 kB; image/gif)

```

**Comment by kitanibaladmin** [comment]
sgelabert-dgtic
2016-02-16 07:50:50.761000
Hay dos casos 
1) no se muestra desplegada la carpeta a la que pertenece el apartado (bloqueB_2) ó 
2) Se desplegan ambas subcarpetas. (bloqueA_1)

**Comment by kitanibaladmin** [comment]
sgelabert-dgtic
2016-02-16 07:51:41.750000
Para hacer estas pruebas deberéis importar el tema 2015 y al microsite creado indicar que usa dicho tema. Adjunto el tema (tema2015_agosto2015...)

**Comment by kitanibaladmin** [comment]
Attachments:

![](https://sourceforge.net/p/gusite/tickets/11/attachment/p%C3%A0ginaA.gif)

![](https://sourceforge.net/p/gusite/tickets/11/attachment/p%C3%A0ginaB.gif)

**Comment by dmadronal-indra** [comment]
Se adjunta el tema extraido de redmine.
[tema_2015_agosto2015_20160122_12358_tema.zip](https://github.com/GovernIB/gusite/files/146781/tema_2015_agosto2015_20160122_12358_tema.zip)

**Comment by episano-dgtic** [comment]
Tened en cuenta que el arbol tb. funcione con ie

**Comment by slromero-indra** [comment]
El zip con el nuevo estilo necesario para realizar la prueba correctamente:

https://github.com/GovernIB/gusite/blob/master/moduls/front/etc/tema2015.zip

**Comment by episano-dgtic** [comment]
Me he descargado el tema, lo he importado como tema2015INDRA y lo he aplicado al microsite spreesplin4 31/03/2016 y sigo viendo la misma problemática. Me he equivocado en algo?

**Comment by dmadronal-indra** [comment]
Para validar la incidencia es necesario usar el último tema incluido en el repositorio:
[tema2015](https://github.com/GovernIB/gusite/blob/gusite-1.2/moduls/front/etc/temas/zip/tema2015.zip?raw=true)

**Comment by episano-dgtic** [comment]
Hay un pequeño bug. Si se elige la primera opción de una carpeta secundaria (amarilla) no se muestra el apartado del menu desplegado. Si se elige una segunda o tercera opción va bien sin problemas. TAl vez tenga que ver con la incidencia  #33

**Comment by dmadronal-indra** [comment]
Solo era reproducible usando un tipo de menú (con o sin iconos) a  nivel de microsite. No guarda relación con la resolución de #33.
![gestormicrosites](https://cloud.githubusercontent.com/assets/17270582/14648543/1b709a56-0663-11e6-951e-e182cbe6f24b.png)

**Comment by episano-dgtic** [comment]
Adjunto el tema modificado.. que testearé en CAIBTER
[tema2015_20042016.zip](https://github.com/GovernIB/gusite/files/227474/tema2015_20042016.zip)

**Comment by episano-dgtic** [comment]
He querido probarlo en vuestro sistema.. pero voy al front de en el microsite "prueba URI" y quiero visualizar las páginas de la subcarpeta b2 y b1 me da un error 404. 
He asumido que el tema "nuevo" tiene ya actualizado el tema del 2015. 

A modo de mejorar el funcionamiento de las pruebas en caibter.. seria interesante que además que indiquéis que habéis resuelto el problema. Indiquéis donde podemos probarlo en caibter, ya que previamente vosotros lo habéis testeado.

**Comment by episano-dgtic** [comment]
Insertaréis en CAIBTER el último tema y lo aplicais al microsite "Prueba URI estela".
Porque al menos a mi, no me sale bien el arbol.. aparece todo desplegado y los contenidos debajo del árbol.

**Comment by dmadronal-indra** [comment]
Probado en caibter: "Prueba URI estela."

**Comment by episano-dgtic** [comment]
guay...
