### ISSUE TITLE
En el buscador de los listados aparecen elementos marcados como no visibles.

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#130]
Por ejemplo, en este listado:
http://www.caib.es/sites/M170613081930629/ca/l/l10-07-_iniciatives_reglementaries_conselleria_de_salut_i_consum/

Hay una opción que está oculta ("Projecte de decret de modificació del Decret 31/2015..."), y por tanto no aparece. Pero cuando buscas por "gasolines":
http://www.caib.es/sites/M170613081930629/ca/l/l10-07-_iniciatives_reglementaries_conselleria_de_salut_i_consum/?filtro=gasolines&btnSsearch=Cerca#

Verás que sí que aparece. Al clicar da el error de que no se puede acceder. Pero no debería salir tampoco en la búsqueda.

**Comment by dmadronal-indra** [comment]
Buenas,
a priori parece que el contenido se indexó con la opcion visible, y a posteriori se oculto. En estos casos si la opción sigue apareciendo se debería reindixar el microsite. Hemos intentado reproducirlo pero no lo logramos. ¿Podeis indicarnos como reproducirlo?

**Comment by bgarcia-dgtic** [comment]
He creat a PREproducció, el Microsite "Prova Tomeu" (id=10725).
Hi ha la pàgina "llistat fitxes" amb 4 elements. Tots estan visibles menys el número 3. Quan accedeixes a la pàgina "llistat fitxes" et mostre els elements "fitxa 1, fitxa 2 i fitxa 4". Però si al cercador poses la paraula "fitxa" i li dones a cercar, et mostra els 4 elements i si prems sobre l'element "fitxa 3" et dóna error.
He indexat el Microsite però segueix mostrant l'element "fitxa 3" quan fas una cerca.

**Comment by dmadronal-indra** [comment]
Buenas, 
hemos revisador este tema en nuestros entornos y parece ir bien. hemos comentado por teléfono una serie de pruebas y una vez finalizadas habría que revisar los logs para verificar que puede estar pasando.

**Comment by bgarcia-dgtic** [comment]
Hola, a continuació indico les passes que he realitzat.
1. Creo un nou llistat de fitxes amb el nom "llistat fitxes 2".
2. Afegeixo 5 fitxes visibles (primera fitxa, segona fitxa, tercera fitxa, quarta fitxa, cinquena fitxa).
3. Creo la pàgina "llistat fitxes 2" i la relaciona amb el llistat "llistat fitxes 2".
4. Accedeixo a la pàgina i em mostra els cinc elements.
5. Faig una prova per veure si el cercador del llistat troba elements sense haver indexat el microsite. Cerco per la paraula "fitxa" i em retorna els cinc elements.
6. Indexo el microsite. Comprovo si el microsite s'ha indexat correctament consultant el botó "Veure informació de les tasques". El fitxer indica que el microsite s'ha indexat correctament ja que no s'han produït errors.
7. Torno al llistat "llistat fitxes 2" i modifico la visibilitat de "quarta fitxa" a no visible.
8. Torno a la pàgina "llistat fitxes 2" (sense torna a indexar) per veure quants elements em mostra. Ara la pàgina només mostra 4 elements (l'element "quarta fitxa" no apareix). Realitzo una cerca amb la paraula "fitxa" i em retorna els cinc elements inclòs la "quarta fitxa".
9. Realitzo una indexació. Comprovo que no s'han produït errors amb el botó "Veure informació de les tasques".
10. Recarrego la pàgina "llistat fitxes 2", em mostra 4 elements (l'element "quarta fitxa" no apareix).
11. Realitzo una cerca amb la paraula "fitxa" i em torna a mostrar els 5 elements.

**Comment by dmadronal-indra** [comment]
Buenas, hemos realizado una actualización de la aplicación para resolver este tema. ¿lo podéis validar?

**Comment by bgarcia-dgtic** [comment]
Pareix que funciona correctament
