### ISSUE TITLE
las url de previsualización están visibles para internet independientemente visibilidad página y dominio entrada. 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#131]
La url: 
https://intranet.caib.es/sites/atenciociutadania/ca/queixes_i_suggeriments_/?tipo=alfa&previsual=previsual
ó
https://www.caib.es/sites/atenciociutadania/ca/queixes_i_suggeriments_/?tipo=alfa&previsual=previsual
Se puede acceder aunque esté no visible.

**Comment by slromero-indra** [comment]
Hemos revisado la incidencia y, tras analizarlo, hemos visto que la mejor manera de controlar la url de previsualización desde el frontal sea exigir estar autenticado cuando se pasa el parámetro (es decir, si se detecta que se pasa el parámetro previsual=previsual, se redirigirá para que se autentique previamente).

 En caso de estar ya logueado, este paso será totalmente transparente para el usuario.

**Comment by slromero-indra** [comment]
Hemos subido los cambios para forzar el logueado cuando se pasa el parámetro de previsualización. Además, se añaden los parámetros con los que viene desde la url inicial cuando hace la previsualizacion.

**Comment by episano-dgtic** [comment]
Está correcto.
