### ISSUE TITLE
Accediendo en catalán a un elemento de un listado, aparece la etiqueta "Enlaces de interés"

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#132]
Otro problema, accediendo un elemento de un listado al componente en catalán aparece en castellano la etiqueta "Enlaces de interés"
http://www.caib.es/sites/transparenciaperconselleria/ca/n/llei_42011_de_31_de_mara_de_la_bona_administracia_i_del_bon_govern_de_les_illes_balears_0/

**Comment by dmadronal-indra** [comment]
Buenas hemos actualizado la aplicación y la plantilla 2017, para probarlo es necesario actualizar tanto la aplicación como la plantilla.
lo podeis validar?
