### ISSUE TITLE
Accessibilitat, canvis a les plantilles del formulario de contacte i capçalera

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#133]
A la plantilla del formulari de contacte falta l'etiqueta label del camp captcha:
`<label for="captcha">
	<input type="text" id="captchaResp"  name="captchaResp" style="margin: auto;" onchange="habilitarEnviar()"/>
</label>`

A la plantilla de capçalera s'ha d'incloure "lang" a l'enllaç canvi d'idioma (a href=)
`<a th:if="${idiomaLower}!=${idiomaLista.key}" href="#" th:href="@{${#gusuri.traduccionEnlacePie(#ctx.httpServletRequest.contextPath, #httpServletRequest.requestURI, idiomaLista.key,MVS_busquedaBuscador,MVS_tipobeta)}}" th:lang="@{${idiomaLista.key}}" th:utext="${idiomaLista.value}"> Castellano </a>`

**Comment by episano-dgtic** [comment]
Exemple apareix el text centrat a la descripció del esdeveniment: https://proves.caib.es/sites/jornada/ca/agenda/20200601
Per una qüestió estètica trauria del css la característica ! Important. 
div.activitat p {
	text-align: center !important;
}
