### ISSUE TITLE
Impedir l'accés a documents de pàgines "internes / ocultes" caducades o futura publicació.

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#134]
A dia d'avui, si google indexa els continguts, es pot accedir a arxius de pàgines ocultes. No és desitjable. El control per microsite ocult / restringit ja està implementat.

A la taula gusite.GUS_DOCUS, a la columna DCM_pagina està la pàgina de l'microsite.
A la taula GUS_CONTEN a la columna CON_VISIB veureu si és interna / oculta, i en CON_PUBLIC / CON_CADUCA el rang visibilitat.

**Comment by slromero-indra** [comment]
La pauta que seguiremos para permitir descargar o no el documento, será que al menos haya una página que sea visible que tenga enlace con el documento (como no se puede controlar desde que página viene la descarga, es la única manera de controlar el bajar el fichero o no).

**Comment by episano-dgtic** [comment]
perfecto, esa es la idea. Qué la página a la que pertenece el fichero esté visible (sin caducar, o oculta aposta) 
Ojo, que si el fichero es común (arbol de contenidos->archivos comunes), debería actuar como hasta ahora, si el microsite es visible, debería seguir siendo accesible.

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado este tema, ¿lo podeis verificar?

**Comment by episano-dgtic** [comment]
He verificado que habéis ocultado los contenidos caducados, y ocultos. Aunque no los de futura publicación. 
Pero he visto que la previsualización de contenidos ha dejado de funcionar en todos los casos. Lo deseable es que los gestores pueda visualizarlo previamente en cualquier estado para poder publicarlo. 
Aunque en el entorno de dev previsualización pilla: 
https://dev.caib.es/sacmicrofront/contenido.do?lang=ca&mkey=M08092211155013147625&cont=27789&stat=no&tipo=alfa&previsual=previsual
Y en pre: 
https://proves.caib.es/sites/eines/ca/presentacio/?tipo=alfa&previsual=previsual
Con lo que no sé si tiene algo que ver.

**Comment by slromero-indra** [comment]
Ya están los cambios subidos, podéis validarlo?

**Comment by episano-dgtic** [comment]
No está el problema de la previsualización desde el backoffice. 
Pero se continua pudiendo visualizar los documentos de páginas caducadas/futura publicación ó internas.

**Comment by dmadronal-indra** [comment]
Buenas, hemos intentado replicar el error:
_Pero se continua pudiendo visualizar los documentos de páginas caducadas/futura publicación ó internas._
pero no lo logramos, ¿nos podéis facilitar un caso concreto en dev o proves para tratar de reproducirlo?
Debéis tener en cuenta que si se está autenticado y se tiene el uno de los roles de gusite, estos ficheros serán siempre visibles (es como si se estuviera previsualizando), por lo que para probarlo deberéis abrir una pestaña de incognito e intentar acceder a los ficheros.

**Comment by episano-dgtic** [comment]
Cuando lo probé así lo hice. Tanto con ventana en incognito como abriendo chrome sin autentificar. Ahora no puedo testear lo que comentas, ya que en pruebas tenemos la versión anterior al rendimiento, y en dev la configuración de cambio de bd.  
De hecho todas no me funcionó ninguna de las incidencias que comentabais que estaban okey. 
Tal vez hubo algún problema con el paso a pre. Si en vuestro entorno lo veis bien, cuando se suba a pre lo vuelvo a testear.

**Comment by slromero-indra** [comment]
Buenas, para subir una versión a producción con la versión que mejora el rendimiento y las otras issues que son urgentes, hemos punteado el método para que lo marque siempre como visible y podamos subir a producción. La idea es una vez que subamos versión, podamos volver a seguir con la depuración de la incidencia y resolver el problema del front que comentáis.

¿Podéis validarlo para cerrar una versión a subir a producción?

**Comment by slromero-indra** [comment]
Buenas, retomamos la issue. Si os parece bien, volvemos a activar la validación de los documentos.
Además, sin importar si es una imagen (png/jpg/etc...) o un documento (pdf/doc) entra por esta comprobación ralentizando gusite al tener que realizar varias consultas ya que no entran por métodos distintos. 

Si os parece bien, para evitar problemas de rendimiento, creemos que tendría más lógica que sólo se hiciese las comprobaciones cuando el fichero es de tipo documento (pdf/doc/docx/xls/xlsx/odt).

**Comment by episano-dgtic** [comment]
okey.. si así evitamos problemas rendimiento y aún tarde más en cargar las páginas me parece bien. Este ticket viene más por la indexación de contenidos de microsite por google y que luego se pueda acceder a pdf que al gestor le parece no están visibles.

**Comment by slromero-indra** [comment]
Buenas, ya está comiteado el cambio, podéis validarlo?

**Comment by episano-dgtic** [comment]
He comprobado que efectivamente ahora no se puede acceder a documentos caducados, futura publicación o en páginas internas. Pero la página de error no se puede controlar:
![134_pagina_novisible](https://user-images.githubusercontent.com/17451683/124592362-ab2b5280-de5d-11eb-904d-1fd92bddb861.gif)

Algo como ocurre cuando el fichero no tiene referencia: https://intranet.caib.es/sacmicrofront/archivopub.do?ctrl=MCRST299ZI138913&id=138913

**Comment by dmadronal-indra** [comment]
Buenas, hemos realizado una actualización para corregir lo indicado, lo podeis revisar?

**Comment by episano-dgtic** [comment]
Funciona correctamente excepto en los ficheros de la agenda que también los bloquea(pdf, xls..) . Curiosamente en los listados no se presenta el problema.

**Comment by dmadronal-indra** [comment]
Buenas, 
no logramos reproducir el error, os hemos enviado un correo con mas detalle, ¿lo podeis revisar e indicarnos como reproducirlo?

**Comment by episano-dgtic** [comment]
El problema es el acceso  a los documentos pdf,xls de los eventos de la agenda, tanto para eventos pasados como futuros :
https://dev.caib.es/sites/test_noimportant/ca/agenda/20211122/

Crear un evento, incluir como Documento un pdf o ficheros controlais, y veréis que desde el frontal da error (Error: No s' ha trobat el document sol·licitat)

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos comiteado una nueva version que solventa el problema.  ¿Podeis revisarlo?

**Comment by episano-dgtic** [comment]
El tema documentos adjuntos funciona correctamente. Pero he detectado en el entorno de dev fallos en la previsualización desde el backoffice de algunos módulos (encuestas, listados, agenda, faqs, páginas de contenido..) En todos los casos devuelve una página "Not found". 
![prev_listados](https://user-images.githubusercontent.com/17451683/157197023-9791e9e3-81e4-45d5-a9fc-274c9da2cd74.gif)
![prev_encuesta](https://user-images.githubusercontent.com/17451683/157197027-6373b25a-6452-4281-b0a5-7fc58805fe37.gif)
![prev_agenda](https://user-images.githubusercontent.com/17451683/157197030-0ceaa026-7e82-4ac6-995f-8c743a3eb3c9.gif)
![prev_pagina](https://user-images.githubusercontent.com/17451683/157197033-b72f34c3-a45b-442b-910a-b05f81c6b702.gif)

**Comment by dmadronal-indra** [comment]
Buenas, el ultimo comentario se tratará en la #153.
Podeis cerrar esta?
