### ISSUE TITLE
Accessibilitat, problemes a l'hora d'aplicar la propietat !important a alguns css

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#136]
Hay problemas por aplicar !important en alguna propiedades line-height, letter-spacing o word-sapcing, algunos css. Los detectados (linea, columna):
53 5 http://www.caib.es/sites/resources/css/estils.css

835 17 http://www.caib.es/sites/ft/tema2017/css/estils-tema.css
line-height:1.8em !important

2643 9  http://www.caib.es/sites/ft/tema2017/css/estils-tema.css
line-height:1.5em !important

Luego el fichero 0 0   http://www.caib.es/sites/ft/temadgcom/css/estils-tema.css parece que encuentra un caracter erroneo. Found illegal character: !
No veo nada raro.. lo actualizaría, a ver que pasa. 

Hay problemas con la aplicación de h1,h2 etc.. en las plantillas de gusite, y si partimos de h1 el estilo queda demasiado grande. Con lo que habrá que aplicar estilos y quitar algunas referencias de h2 y h3 ocurre con los componentes, encuesta y agenda (servicios). 
En los mapas de ubicaciones habría incluir alternativas textuales, y recordaros que seguimos teniendo google maps, aunque imagino que tiene pocos clicks(peticones) y tal vez no haya problemática. 

Respecto a que detecta descripción del alt de las imágenes por indicar la extensión del fichero, he pensado hacer update de base de datos buscando .jpg" o por estilo, pero es algo ariesgado en el caso haya enlaces a ficheros del servidor web, que alguno habrá. 

[accesibilidad_test_microsite.pdf](https://github.com/GovernIB/gusite/files/4817621/accesibilidad_test_microsite.pdf)

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado algunas actualizaciones lo podéis revisar?

**Comment by episano-dgtic** [comment]
Se han resuelto algunos casos pero sigue dando en el test del observatorio el error: 

53 5 http://www.caib.es/sites/resources/css/estils.css

[lista_de_paginas_202102120918.pdf](https://github.com/GovernIB/gusite/files/5970498/lista_de_paginas_202102120918.pdf)

**Comment by slromero-indra** [comment]
Buenas, ya están los cambios, cuando podáis lo validáis

**Comment by slromero-indra** [comment]
Los cambios asociados al tema2017, tenéis que volver a generar el zip y subirlo de nuevo.

**Comment by slromero-indra** [comment]
Buenas, podéis verificar si están correctos los cambios?

**Comment by episano-dgtic** [comment]
Confirmado no existe la problemática en los ficheros estilos sistema.
