### ISSUE TITLE
Bug accés a fitxers amb accents altra codificació

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#137]
Hem detectat un "Internal Server Error" en l'accés web de fitxers amb accents "estranys ´".
![fichero_acentoraro](https://user-images.githubusercontent.com/17451683/94901780-72f28000-0497-11eb-9443-9ef919dfa1d4.gif)

L'url www.caib.es/sites/archivopub.do?ctrl=MCRST157ZI331934&id=331934 remete a l'url http://www.caib.es/sites/eines/f/331934, i malgrat estar el fitxer no el carrega. 

Si l'accent és ´, dóna el "Internal Server Error" i si és a l'inrevés ` el nom es talla a l'arribar a aquest caràcter encara que no dóna l'error.

Adjunt excel amb fitxers dóna problema, per pogueu veure el sql i xuclar el caràcter.
[casos_Acentos.xlsx](https://github.com/GovernIB/gusite/files/5316708/casos_Acentos.xlsx)

Perquè pugueu reproduir el problema, us passo fitxers amb aquests caràcters.
[arxius.zip](https://github.com/GovernIB/gusite/files/5316721/arxius.zip)

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización para solventar este tema. lo podeis revisar? (https://github.com/GovernIB/gusite/commit/69acd2bfbe2dea405fdb96ebee79188d48695a81)

**Comment by episano-dgtic** [comment]
He incluido los ficheros que remití para testear en pruebas. 
https://proves.caib.es/sites/test/ca/test_codificacion_archivos/

Y se consiguen descargar los ficheros pero los casos con el acento ` se pierde la extensión del fichero. Con lo que puede suponer problemas al ciudadano a desconocer la herramienta con la que puede visualizarlo. Podéis hacer que siga el mismo comportamiento que si tiene acento ´

**Comment by dmadronal-indra** [comment]
Buenas, hemos revisado este tema, para permitir descargar estos ficheros. ¿Lo podeis verificar?

Por otro lado entendemos que una posible mejora seria que al subir los ficheros se normalizaran los nombres de los ficheros, para evitar que se suban con acentos, y espacios, de esta manera se evitarian posibles problemas de codificación. si os parece acertado se podria crear una incidencia nueva para realizar esta mejora.

**Comment by bgarcia-dgtic** [comment]
Hola,
He creat la issue #145 per normalitzar el text dels fitxers a l'hora de pujar-los

**Comment by episano-dgtic** [comment]
No veo ningúin cambio respecto  ` se continua perdiendo la extensión del fichero.

**Comment by episano-dgtic** [comment]
No veo ningúin cambio respecto ` se continua perdiendo la extensión del fichero.

**Comment by slromero-indra** [comment]
Buenas, no habíamos comiteado los dos cambios. Hemos aplicado un filtro para normalizar el filename del fichero (y así evitar caracteres raros), ¿podéis probar ahora a descargar el fichero y ver si ya se descarga con la extensión?

**Comment by bgarcia-dgtic** [comment]
Funciona correctament
