### ISSUE TITLE
El cercador dels llistats, no torna resultats si la paraula a cercar té accents.

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#138]
El cercador dels llistats, no torna resultats si la paraula a cercar té accents. EX:
https://www.caib.es/sites/institutestudisautonomics/ca/l/normativa-8165/

Cercant "organització" ó "ORGANITZACIÓ" retorna 0 resultats, 
Buscant "organitzacio" retorna els casos sense accents (errors ortogràfics)

L'opció més senzilla és que retorni resultats sense tenir en compte si la paraula té o no accents. És a dir que no distingeixi l'accent, i retorni mateixos resultats organitzacio i organització.

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización para solventar este tema. lo podeis revisar?

**Comment by episano-dgtic** [comment]
La veo correcta. En la solución implementada distingue si la palabra tiene o no acento dando resultados diferentes, pero devuelve resultados.
