### ISSUE TITLE
Bug desplegament ear

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#140]
A l'hora de desplegar l'ear al servidor, dóna el següent error:
![imatge](https://user-images.githubusercontent.com/26536678/102059163-cd418280-3df0-11eb-83ee-22b0b5e8f221.png)

Pareix que no troba la llibreria "jersey-bundle-1.19.1.jar"

**Comment by slromero-indra** [comment]
Incorporado la librería en el fileset

**Comment by bgarcia-dgtic** [comment]
Ja no dóna error
