### ISSUE TITLE
Problemàtica en el pas a relatiu https://intranet.caib.es/valibback/ a ../valibback/ des de l'editor simplificat html dels microsites (llistats, agenda)

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#143]
Problemàtica pel pas per defecte a relatiu https://intranet.caib.es/valibback/ a ../valibback/ des de l'editor simplificat html dels microsites (llistats,agenda) si es va entrar al gestor des https://intranet.caib .es/sacmicroback/.
No passa en l'editor principal de les pàgines, ja que que si l'enllaç s'indica específicament http: // o https: // es permet quedi de forma absoluta.

L'editor simplificat hauria de tenir el mateix comportament que el ampliat. I si s'indica http: // o https: //, no canviï l'enllaç a relatiu (encara que coincideixi entorn backoffice i URL interessa incloure). Ja que provoca enllaç no funcioni correctament.

**Comment by slromero-indra** [comment]
Buenas, perdonad, no somos capaces de entender la problemática, podéis pasarnos más info del problema?

**Comment by bgarcia-dgtic** [comment]
Hola, adjunto captura de pantalla
![imatge](https://user-images.githubusercontent.com/26536678/107757592-0e3d1100-6d26-11eb-9d55-254c4068bdb8.png)


Quan estàs a l'editor d'un llistat o notícia (Edició de recursos -> Llistats) i crees un enllaç cap el mateix domini, per exemple "https://intranet.caib.es/valibback/" la url que es forma és "../valibback".
A l'editor de les pàgines normals (Arbre de continguts -> Arbre de menú) si crees l'enllaç "https://intranet.caib.es/valibback/" la url que es forma és "https://intranet.caib.es/valibback/".

Si estàs a l'entorn de proves "https://proves.caib.es/sacmicroback" i a l'editor d'un llistat o notícia crees l'enllaç "https://proves.caib.es/valibback/" la url que es crea és "../valibback".

Esper que us hagi ajudat.

**Comment by dmadronal-indra** [comment]
Buenas hemos revisado este tema, ¿Lo podeis verificar?

**Comment by bgarcia-dgtic** [comment]
Funciona correctament

**Comment by episano-dgtic** [comment]
en producción
