### ISSUE TITLE
Revisió del rendiment a l'hora de recuperar la plantilla quan es carrega una pàgina

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#144]
Hola,
Quan es carrega una pàgina, es realitzen moltes consultes a base de dades per recuperar la plantilla i això fa que el rendiment disminueixi.

**Comment by slromero-indra** [comment]
Buenas, ya hemos comiteado los cambios. Por favor, cuando podáis lo validáis.

**Comment by bgarcia-dgtic** [comment]
Hola,
L'optimització funciona correctament.
