### ISSUE TITLE
Problemas visualización componente en microsite transparencia tras revisión rendimiento

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#146]
En el paso a pro de esta mañana el microsite de transparencia ha tenido problemas de visualización, tanto actualizando lo el tema de plantilla 2017 como sin actualizarlo. 

Antes, con visualización correcta:
![visualizacion_anterior](https://user-images.githubusercontent.com/17451683/110328740-feaaa280-801b-11eb-8f7b-ad69c7793920.gif)
La visualización tras cambio rendimiento:
![visualizacion_masrendimiento](https://user-images.githubusercontent.com/17451683/110328844-24d04280-801c-11eb-9fc1-e25a529e0fc9.gif)

En pruebas:
https://proves.caib.es/sacmicroback/index.do?idsite=9345
https://proves.caib.es/sites/transparencia/ca/normativa_en_tramitacia/

En producción:
https://www.caib.es/sites/transparencia/ca/normativa_autonamica/ 

La personalización del componentes: 
[transparencia.zip](https://github.com/GovernIB/gusite/files/6101651/transparencia.zip)

**Comment by slromero-indra** [comment]
Buenas, ya están subidos los cambios, cuando podáis lo validáis.

Además de lo comentado, hemos subido la librería rolsacAPI de la 1.8.0 a la 1.9.0 (ya que debe ir sincronizado con la subida de rolsac, aunque no implica ningún problema, es lo más correcto)

**Comment by episano-dgtic** [comment]
Correcto en pre.
