### ISSUE TITLE
Migració a ORACLE 19

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#147]
Disposam ja d'una nova BBDD Oracle19 DEV amb un import d'estructura i dades des de des11g6

**Comment by slromero-indra** [comment]
Buenas, hemos probado la conexión a la nueva base de datos y no hemos visto ningún problema asociado a la nueva versión (lo único es un bug con la agenda pero es independiente y que os pasaremos por privado).

Para probar, hemos generado un microsite y contenido de distinto tipo y no hemos visto ningún comportamiento extraño.

**Comment by slromero-indra** [comment]
Buenas, para realizar la prueba hacia Oracle 19, no se actualizó ni el JDBC ni se actualizó el JDK. Nos han comentado que os ha dado problemas actualizando ambos, ¿a que JDBC habéis actualizado? Por eso habéis incrementado la versión de compilación del JDK?

**Comment by bgarcia-dgtic** [comment]
Hola,
Adjunto versions compatibles de OJDBC i JDK amb Oracle 19c que ens ha passat serveis web.

BD Oracle Versiones JDBC y JDK
------------
19c 
ojdbc10.jar con JDK10, JDK11
ojdbc8.jar con JDK8, JDK9 y JDK11

18c 
ojdbc8.jar con JDK8, JDK9, JDK10 y JDK11

12c Release 2 (12.2) 
ojdbc8.jar con JDK8

12c Release 1 (12.1) 
ojdbc7.jar con JDK7 y JDK8
ojdbc6.jar con JDK6

11g Release 2 (11.2)
ojdbc6.jar con JDK6, JDK7 y JDK8 (Nota: JDK7 y JDK8 sólo están soportadas en 11.2.0.3 y 11.2.0.4)
ojdbc5.jar con JDK5


A DEV he pujat el fitxer ojdbc8.jar i he modicat el sites-ds.xml per que apunti a la nova BBDD. L'aplicació funciona, es a dir, funciona amb la compilació JDK 1.7 
He intentat compilar l'aplicació amb el JDK 1.8_152 i em dóna error. Us enviaré els logs per correu.

**Comment by slromero-indra** [comment]
Buenas, en vuestro entorno os daba un error, podéis pasarnos el log?

**Comment by bgarcia-dgtic** [comment]
Hola,
Us he enviat per correu els logs amb els errors que em dóna a l'hora de d'empaquetar amb JDK 1.8.152

**Comment by slromero-indra** [comment]
Se han realizado pruebas de Gusite contra Oracle 19c con los siguientes resultados:
-	Compilación JDK8: 
o	Falla al compilar: el código fuente no está preparado y hay problemas con versiones de librerías (no compatible con Spring3, requeriría pasar a Spring4)
o	Consideramos que no se debería compilar en JDK8 ya que el impacto en la aplicación puede ser enorme
-	Compilación JDK7 / Ejecución JDK7  / OJDBC actual (ojdbc6.jar):  
o	Funciona correctamente sin incidencias
-	Compilación JDK7 / Ejecución JDK8  / OJDBC8:
o	Para ejecutar con JDK8 es necesario actualizar de Spring3.2.0 a Spring3.2.3
o	Al realizar pruebas hemos detectado que existe una incidencia al ejecutar con JDK8 con la compilación de JSP (https://stackoverflow.com/questions/38399796/not-able-to-compile-jsp-files-in-jboss-5-1-with-java-1-8). Cambiando lo que se indica en esta url parece que funciona, pero implica cambiar librerías propias del JBoss y cambios también en librerías de Spring.

Hay que determinar que camino se debe seguir para realizar más pruebas en profundidad. Por nuestra parte vemos menos problemática la 2ª opción ya que no tiene impacto en la aplicación y a nivel de OJDBC no hay problema en usar la versión actual ya que el uso que se hace a nivel de JPA es básico (select, inserts,…)

**Comment by slromero-indra** [comment]
Buenas, cuando podáis, nos podéis confirmar por cuál de los caminos continuar?

**Comment by bgarcia-dgtic** [comment]
Bon dia, en els propers dies us informarem sobre quina opció seguirem.

**Comment by bgarcia-dgtic** [comment]
Bon dia,

Pareix que de moment seguirem amb la segona opció. Estem a l'espera que serveis web ens informi.

**Comment by slromero-indra** [comment]
Bon dia! Como se va a seleccionar la segunda opción, si te parece bien, podemos dar por cerrada la issue.

**Comment by bgarcia-dgtic** [comment]
Bon dia, ok d'acord
