### ISSUE TITLE
Error imagen listado en microsite totalmente nuevo

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/gusite#15]
Numero: 9
Creació: 2016-02-16 07:39:08.945000
He creado un microsite totalmente nuevo, y he querido añadir una imagen a una noticia de un listado.
Aparentemente iba bien, cuando lo he visualizado no tenía la imagen. 
He ido al backoffice y querer ver la imagen en cuestión, daba error. (adjunto imagen y error)

Tras eliminar he vuelto a insertar y ha funcionado. No se si será reproduccible.

**Comment by kitanibaladmin** [comment]
sgelabert-dgtic
2016-02-16 07:39:34.135000
- Attachments has changed:

Diff:

```

--- old
+++ new
@@ -1 +1,2 @@
 Erizo_nuevoYnoAparece.gif (170.9 kB; image/gif)
+Erizo_nuevoYnoAparece_logs.txt (6.7 kB; text/plain)

```

**Comment by kitanibaladmin** [comment]
[Erizo_nuevoYnoAparece_logs.txt](https://github.com/GovernIB/gusite/files/144317/Erizo_nuevoYnoAparece_logs.txt)

![](https://sourceforge.net/p/gusite/tickets/9/attachment/Erizo_nuevoYnoAparece.gif)

**Comment by slromero-indra** [comment]
Buenas, he intentado replicar el error y parece que funciona correctamente. Podéis darme más información por si aún persiste el error, como el tipo de listado que era (es raro pero puede que el error se deba por el tipo de listado).

También he conseguido replicar un error similar, es raro pero no sé si en algún momento ha pasado, y se produce cuando se utilizan dos JBOSS en máquinas/pcs distintos (esto puede pasar si se realiza algún cambio de máquina o bien cuando se está depurando y alguien realiza pruebas desde su máquina).
