### ISSUE TITLE
Fallos en la previsualización desde el backoffice de algunos módulos

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/gusite#153]
Se ha detectado en el entorno de dev fallos en la previsualización desde el backoffice de algunos módulos (encuestas, listados, agenda, faqs, páginas de contenido..) En todos los casos devuelve una página "Not found".
![imagen](https://user-images.githubusercontent.com/26536678/158142769-03f79b19-1446-4182-b28b-f46866a8e66c.png)
![imagen](https://user-images.githubusercontent.com/26536678/158142801-25351f79-50dc-4389-9679-dc0a6043bd0f.png)
![imagen](https://user-images.githubusercontent.com/26536678/158142833-56de29d2-0a9a-472c-bd6b-596660b0bd0d.png)
![imagen](https://user-images.githubusercontent.com/26536678/158142862-61136173-4e80-4ee1-8e43-5a751dccd1df.png)

**Comment by dmadronal-indra** [comment]
Buenas, 
comentado por teléfono:
Este tema parece un problema con el contexto sacmicrofront en dev, habría que verificar si está correctamente publicado el contexto en el apache. 

Si una vez verificado sigue fallando, lo revisamos de nuevo (en nuestros entornos parece funcionar correctamente)

**Comment by bgarcia-dgtic** [comment]
Hola,
Efectívament, era un problema del context sacmicrofront en dev.
Hem procedit a publicar aquest context i ja funciona.
Tanco la incidència
