### ISSUE TITLE
Inclusión propiedades Google Analytics 4 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#154]
A partir del 1/7/2023 dejará de estar operativa la propiedad Universal Analytics. El nuevo sistema comienza a estar activo al implementarse y no se puede migrar las estadísticas. Con lo que interesa que se configuré gusite también para las nuevas propiedades (Google Analytics 4). Actualmente hay 584 propiedades Universal Analytics Activas. Todos los microsites utilizan la última plantilla del goib aunque hay 9 temas definidos.

Entiendo que será necesario incluir un nuevo campo en gus_micros para almacenar las para almacenar las nuevas propiedades y modificar el frontal web de la plantilla genérica.

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la plantilla 2017.

En esta versión se pueden indicar varias claves de analitics separadas por ";".
la primera que se indique es la que debe corresponder con la de Google Analytics 4.

¿podéis validarlo?
