### ISSUE TITLE
Modificacions en la plantilla de la nova web del GOIB

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/gusite#159]
Arran de la primera versió desenvolupada #156, es sol·liciten les modificacions indicades per correu.

Aquestes es resumeixen en modificacions d'estils específics de determinades etiquetes de la plantilla (p, h1, h2...)

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la plantilla con lo indicado en el commit, ¿podéis revisar los cambios?
para probar los cambios, hay que actualizar el fichero de propiedades con las nuevas propiedades añadidas.
