### ISSUE TITLE
Detalles nuevo front

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/gusite#16]
Numero: 8
Creació: 2016-02-16 07:36:14.882000
Resulta que en la visualización de los componentes de los listados, para vuestro front (similar antiguo backoffice) en lugar de indicar "Títol del component", habeis utilizado el "Nom del component". Este último no premite acentos, apóstrofes etc..

Seguiréis la misma filosofia anterior.

**Comment by kitanibaladmin** [comment]
sgelabert-dgtic
2016-02-16 07:37:10.852000
- Attachments has changed:

Diff:

```

--- old
+++ new
@@ -1 +1,2 @@
 frontANTIC_componentesListados.gif (149.0 kB; image/gif)
+frontNOU_componentesListados.gif (135.8 kB; image/gif)

```

**Comment by kitanibaladmin** [comment]
sgelabert-dgtic
2016-02-16 07:37:36.873000
- Attachments has changed:

Diff:

```

--- old
+++ new
@@ -1,2 +1,3 @@
+componenteListado_lista2.gif (116.9 kB; image/gif)
 frontANTIC_componentesListados.gif (149.0 kB; image/gif)
 frontNOU_componentesListados.gif (135.8 kB; image/gif)

```

**Comment by kitanibaladmin** [comment]
![](https://sourceforge.net/p/gusite/tickets/8/attachment/frontANTIC_componentesListados.gif)

![](https://sourceforge.net/p/gusite/tickets/8/attachment/componenteListado_lista2.gif)

![](https://sourceforge.net/p/gusite/tickets/8/attachment/frontNOU_componentesListados.gif)

**Comment by dmadronal-indra** [comment]
![componentelistado_lista2](https://cloud.githubusercontent.com/assets/17270582/13966563/5ad5efda-f073-11e5-85b8-0dea9d15ba8c.gif)
![frontantic_componenteslistados](https://cloud.githubusercontent.com/assets/17270582/13966564/5adaac5a-f073-11e5-8125-a0a2cfd6a172.gif)
![frontnou_componenteslistados](https://cloud.githubusercontent.com/assets/17270582/13966565/5ade7844-f073-11e5-90c7-b4bd42ea8615.gif)

**Comment by slromero-indra** [comment]
os adjunto pantallas para que visualicéis si está correcto la información como se muestra actualmente. 
![creacion compontente](https://cloud.githubusercontent.com/assets/17451407/13980889/46fe2932-f0e1-11e5-971f-d053343fb645.png)
![creacion de contenido](https://cloud.githubusercontent.com/assets/17451407/13980892/4b21000c-f0e1-11e5-8a07-cab6b267ce03.png)
![visualizando en el front sin el estilo aplicado](https://cloud.githubusercontent.com/assets/17451407/13980903/577a3c38-f0e1-11e5-9fd0-d1734d50653e.png)
![visualizando en el front](https://cloud.githubusercontent.com/assets/17451407/13980902/57355d7a-f0e1-11e5-8ed1-3342539c61ce.png)

**Comment by slromero-indra** [comment]
La primera captura es como está creado el compontente. 
La segunda es como está creado el contenido de la página.
Las dos últimas es como se ven en el frontal. Siendo el primero sin estilos mientras el segundo se ve con el estilo nuevo (el zip del frontal 2015 subido en otra issue).
