### ISSUE TITLE
Filtració en la plantilla de GUSITE

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/gusite#161]
Al peu de la nova plantilla de GUSITE es filtra informació de la sessió. Mirar correu al respecte,

**Comment by dmadronal-indra** [comment]
buenas, hemos actualizado la plantilla,
¿Podéis revisar si sigue apareciendo el problema?

**Comment by scalafat-dgtic** [comment]
Resuelto en los casos de ejemplo que nos han pasado
