### ISSUE TITLE
Front de la Visualización Listado de encuestas.

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/gusite#17]
Numero: 7
Creació: 2016-02-16 07:34:16.732000
He creado un apartado "listado de encuestas" remite 
http://sdesapplin14:28080/sites/M1508211117261804529191/llista_encuesta_0/
y este va a "http://sdesapplin14:28080/sites/encuestas.do?idsite=6605&lang=ca&mcont=78996"

Dando como resultado "Error: No s' ha sol·licitat un microsite"

En el antiguo backoffice, sencillamente remite a la página de inicio del microsite. En ambos casos, debería ir a una página con el listado.. o no permitir en el backoficce elegir como destino "Listado de encuestas"

**Comment by kitanibaladmin** [comment]
![](https://sourceforge.net/p/gusite/tickets/7/attachment/lista_encuestas_NuevoFront_disenyoantiguo.gif)

**Comment by episano-dgtic** [comment]
han optado por remitir página inicio microsite en el nuevo front 1.2
