### ISSUE TITLE
Gestión de uris

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/gusite#21]
Numero: 3
Creació: 2016-02-16 07:20:42.429000
Hay un control para evitar el duplicado de uris y evitar que se incluyan controles extraños(acentos, espacios etc..).

El problema es que se ha realizado un control excesivamente global. Es decir, si una página se denomina "agenda" y hay otros microsites con la misma la siguiente sera agenda_0. Con lo que podemos llegar a encontrarnos agenda_0_0_0_0.

http://spreesplin4.caib.es:18080/sites/dominio_microsite/agenda_0_0_0_0_0_0/

Pese a que cada microsite tiene un dominio de partida con lo que podría haber varias páginas con el uri "agenda" 
http://spreesplin4.caib.es:18080/sites/dominio_microsite/agenda/
http://spreesplin4.caib.es:18080/sites/dominio_microsite2/agenda/

**Comment by slromero-indra** [comment]
Buenas, los cambios ya están realizados a falta de subirlos, estamos a la espera que nos den permisos

**Comment by dmadronal-indra** [comment]
detectado error al borrar página.

**Comment by episano-dgtic** [comment]
A espera deis por cerrada la incidencia.. comentaros que efectivamente la corrección de la URI del microsite ahora parece única para el microsite en cuestión. Pero si existe otro microsite con esa uri, salta un error en el servidor al grabar.

**Comment by slromero-indra** [comment]
Buenas, el problema es probable que se deba a que se había creado un índice con las uris y el idioma que tenía la restricción 'unique'. Se ha actualizado en los scripts que subirán al resto de entornos. Como en vuestro entorno ya está actualizado, necesito que paséis el siguiente script en vuestro entorno que elimina la restricción 'unique':

drop index gus_ciduri_i;
Create Index "GUS_CIDURI_I" ON "GUS_CONIDI" ("CID_CODIDI","CID_URI");

**Comment by slromero-indra** [comment]
Se está revisando el bug con el refresco de las uris cuando no se introduce (y el sistema lo introduce automáticamente) aunque se ha creado correctamente.

**Comment by slromero-indra** [comment]
Buenas, por favor, confirmad si el error se sigue produciendo. Todo el resto de problemas se da por solucionado pendiente de validar por parte del usuario.

**Comment by episano-dgtic** [comment]
Se ha solventado el problema en las páginas, ya no da un error al guardar páginas que tienen la misma uri en otro microsite. 
Pero no se ha implementado la solución en "configuración listados, recursos listados y encuestas". Con lo que no se pueden crear listados de novedades en otros microsites con la uri novetats. Ni noticias concretas con la misma uri. 

Creo que esto hace petar reincidentemente la gestión de los listados, de hecho de vez en cuando me falla y da errores al tratar de insertar un elemento a un listado.

**Comment by slromero-indra** [comment]
Ok, lo reviso y te comento lo del error de insertar un elemento de listado.

**Comment by slromero-indra** [comment]
Se está intentando replicar el error y no se está consiguiendo replicar. Por favor, se puede confirmar si el error que se comenta anteriormente ('da errores al tratar de insertar un elemento a un listado.') se solucionó con el script que se pasó y, en caso de persistir el error, que pasos se realizan para replicar el error.

Gracias!
