### ISSUE TITLE
Definir en funcionamiento de la página de contenido, concretamente la obligatoriedad de los campos en las diferentes traducciones.

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/gusite#22]
Numero: 2
Creació: 2016-02-16 07:13:18.091000
Se ha detectado (al resolver la incidencia 1628) que al crear una página, en las diferentes traducciones, se puede introducir únicamente el contenido, aunque los campos de título y uri estén vacíos, lo que provoca que no se guarde ese campo, aunque aparezca rellenado en el textarea (solo se ve que no se ha guardado si se sale de la página y se vuelve a entrar), lo que puede llevar a confusión.

Es necesario definir que comportamiento es el deseable, para poder aportar una solución al mismo.

**Comment by kitanibaladmin** [comment]
sgelabert-dgtic
2016-02-16 07:13:52.307000
En la versión anterior únicamente era obligatorio el título y en el idioma por defecto de la aplicación, en nuestro caso catalán. 
Pero ahora nos parece apropiado que debe ser obligatorios el título y la URI en los idiomas en los que esté configurado dicho microsite. Tanto para las páginas como los listados.

Ojo, que se puede cambiar los idiomas configurados del microsite en cualquier momento. No es habitual, pero se podría dar.

Otra cosa, Si te complica la cosa, que no te preocupe si un microsite está configurado únicamente en castellano y se obliga a introducir título y uri en catalán. Es un caso poco habitual.

**Comment by kitanibaladmin** [comment]
dmadronal-indra
2016-02-23 10:54:57.561000
- **status**: open --> pending
- **assigned_to**: David Madroñal --> Estela (DGTIC)
- **Priority**:  --> normal

**Comment by kitanibaladmin** [comment]
dmadronal-indra
2016-02-23 10:54:57.705000
Revision: 143
Author: dmadronal-indra
Date: martes, 23 de febrero de 2016 11:50:17
Message:
mid #22 Definir en funcionamiento de la página de contenido, concretamente la obligatoriedad de los campos en las diferentes traducciones.
- Título y uri ahora son obligatorios para el idioma por defecto.
- Para las traducciones, si se especifica algúno de los siguientes campos (contenido, título o uri), título y uri pasan a ser obligatorios.

Modified : /gusite-core/branches/gusite-1.2/moduls/microback/etc/sac-microback-messages.properties
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/src/es/caib/gusite/microback/actionform/formulario/contenidoForm.java

**Comment by dmadronal-indra** [comment]
Solicitan realizar el mismo cambio en la edición de los listados.

**Comment by episano-dgtic** [comment]
Otra cosa, respecto del funcionamiento global y otros idiomas diferentes al de por defecto. Si escriben en el título, pero la uri no lo han definido en castellano y lo está en catalán.. La idea es que se grabe la info de la uri en catalán. Ya que es preferible que no salga el aviso, ya que probablemente el usuario no se percate de la gestión de uris.

**Comment by episano-dgtic** [comment]
Veo que cuando traduces si no vas a revisarlo en castellano y tocas el título no aparece la URI. Apesar que al grabar y volver a entrar el campo está indicado.

**Comment by episano-dgtic** [comment]
Por otro lado me he dado cuenta que no se ha implementado dicha solución en los servicios que tiene la misma problemática. ( recurso listados, y configuracion listados)

**Comment by episano-dgtic** [comment]
Me he dado cuenta que hay un caso por lo menos que no controla bien del todo el tema de las uris en castellano. 
Para replicarlo crear página "pàgina a" y traducirla sin más comprobación. Volver a crear otra página idéntica "pàgina a" y traducirla. Veréis que en catalán se corrige la url pero castellano ambas páginas tienen uri "pàgina a"

**Comment by dmadronal-indra** [comment]
Verificamos que pasa en nuestro entorno,  lo revisamos.

**Comment by episano-dgtic** [comment]
Correcto en vuestro entorno. Pendiente probar nuestro
