### ISSUE TITLE
Errores relacionados IE9

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/gusite#23]
Numero: 1
Creació: 2016-02-16 07:11:56.115000
Cuando crea/modifica una página de contenido no se almacena los campos del editor texto (Pàgina PÚBLICA) y del borrador(Pàgina PROTOTIPUS). 
Tb. ocurre con el editor simplificado de los eventos de la agenda, y elementos de los listados.

No realiza ninguna operación el boton guardar de FAQs,

**Comment by kitanibaladmin** [comment]
dmadronal-indra
2016-02-16 12:55:00.762000
- **status**: open --> pending
- **assigned_to**: David Madroñal --> Estela (DGTIC)

**Comment by kitanibaladmin** [comment]
dmadronal-indra
2016-02-16 12:55:00.978000
Revision: 141
Author: dmadronal-indra
Date: martes, 16 de febrero de 2016 13:47:15
Message:
mid #1: Errores relacionados IE9
- Se añade mensaje informativo para indicar navegador obsoleto para IE9 y anteriores (se añaden los estilos pertinentes).
- Se añade hack para solventar problema con el TinyMCE (se elimina la cabecera  X-UA-Compatible para IE9 y anteriores). De esta manera IE9 se ejecuta en modo IE7, evitando el error del TinyMCE.

---

Modified : /gusite-core/branches/gusite-1.2/moduls/microback/etc/sac-microback-messages.properties
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/css/index.css
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/detalleAgenda.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/detalleContenido.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/detalleConvocatoria.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/detalleFaq.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/detalleNoticia.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/inicio.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/listaFrontTemas.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/listaMicrosites.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/listaTemas.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/listaUsuarios.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/microCabpie.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/tinymce/jscripts/tiny_mce/plugins/componentesmicros/componentes.jsp
Modified : /gusite-core/branches/gusite-1.2/moduls/microback/htdocs/tinymce/jscripts/tiny_mce/plugins/insertararchivos/archivos.jsp

**Comment by episano-dgtic** [comment]
Hemos decidido no tener en cuenta los errores del backoffice con IE11 o inferior.
