### ISSUE TITLE
Creación scripts Rollback BBDD para volver a la version 1.1 desde la 1.2

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#24]
Es sol·licita crear script de BBDD per poder redesplegar GUSITE 1.1, una vegada actualitzada la BBDD amb els scripts de GUISTE 1.2.
L'objectiu no es tant tornar enrera totes les operacions efectuades per l'script 1.2, si no més bé de disposar d'una BD compatible per 1.1 i poder tornar enrera el pas a producció de GUSITE 1.2 en cas d'errada greu.

**Comment by slromero-indra** [comment]
Buenas:

## **Para subir a la versión 1.2.1**
1.  Ejecutar el script gusite_update_schema_from_1.1.0_to_1.2.1.sql
2.  Ejecutar el script gusite_create_data_from 1.1.0 to 1.2.1.sql

## **Para bajar a la versión 1.1.0**
1.  Ejecutar el script gusite_update_schema_from_1.2.1_to_1.1.0.sql

## **Cambios en el script de la versión 1.2.1. a la 1.1.0**

Para mejorar la vuelta atrás, se tuvieron que realizar ciertos cambios para poder cambiar entre las versiones sin problemas:
1.  Se cambiaron 3 drop table, quitando sólo las constraints (las tablas seguirán existiendo pero no apuntarán sobre la tabla de microsites)
2.  Se crea un backup de microsites almacenando los campos que se cambian yendo hacia la versión 1.2.1.
Cuando se dé por buena la subida, se tendrá que ejecutar que elimine definitivamente las tablas de apoyo para realizar el rollback:
                                - DROP TABLE gus_banidi cascade constraints;
                                - DROP TABLE gus_banner cascade constraints;
                                - DROP TABLE gus_micpro cascade constraints;
                                - DROP TABLE GUS_MICROS_BACKUP;

## **Comportamiento del script de 1.2.1 a 1.1.0**

**Comentarios**:
o   Los cambios respecto a la funcionalidad de los banners (servicio 3) y de procedimientos (servicio 6) no se tira para atrás y se quedan como definitivos.
o   Los cambios respecto al bug que el servicio 100 se repitiese se quedan como definitivo.
o   Los cambios respectos a idioma no existentes (o incorrectos) se quedan como persistentes.
o   Algunos índices o FK no hace falta borrarlos, porque al borrar el campo, Oracle borra los índices y fks.
**Pasos**:
1.  Volvemos a dejar campos como posibles a null (en la 1.2.1 se fuerzan a que no estén a nulo).,
2.  Borramos las contrainst (FK) respecto a las tablas de idiomas.
3.  Borramos la auditoria y la sequencia asociada. 
4.  Borramos los campos sobre URIS y analytics asociados a las tablas de idiomas (tablas con sufijo ..IDI) 
5.  Actualizamos el campo MIC_RESTRI de los microsites (utilizando la tabla de apoyo previamente creada GUS_MICROS_BACKUP)
6.  Borramos los nuevos campos de la tabla MICROSITE
7.  Borramos las tablas asociadas a plantillas (GUS_FR_TEMA, GUS_FR_PLANTILLA, GUS_FR_VERSION, GUS_FR_PERPLA y GUS_FR_ARCHIVO) y sus secuencias.
8.  Actualizamos los campos TPN_FOTOSPORFILA y TPN_TAMPAG a un valor por defecto (en la versión 1.2.1 no son obligatorios pero sí lo son en la versión 1.1.0 produciendo un error si no tienen al menos un valor).
