### ISSUE TITLE
Recuperar la revisión de git en lugar de SVN

### ISSUE THREAD

**Issue by dmadronal-indra** [GovernIB/gusite#25]
Modificación para recuperar la revisión de git en lugar de SVN

**Comment by sgelabert-dgtic** [comment]
OK, convendria fer neteja dels fitxers que estan en el projecte i que fan referència encara al versionat svn:

/GUSITE-GIT-1.2/moduls/front/src/es/caib/gusite/front/general/Version.java
/GUSITE-GIT-1.2/svnversion.properties
/GUSITE-GIT-1.2/moduls/microback/src/es/caib/gusite/microback/Microback.java
/GUSITE-GIT-1.2/build.xml

Així com de les sortides:
META-INF/MANIFEST.MF --> SVN-revision
/GUSITE-GIT-1.2/output/moduls/version.properties
