### ISSUE TITLE
 Realización del modelo de BBDD.

### ISSUE THREAD

**Issue by dmadronal-indra** [GovernIB/gusite#26]
Crear modelo de BBDD. 
Facilitar el Modelo de BBDD en un documento.

**Comment by sgelabert-dgtic** [comment]
A més del document, es sol·licita adjuntar els arxius font del model de dades a fi de tenir-los disponibles per a futures modificacions de la BBDD.
Intentar emprar, endemés, eines de modelatge gratuïtes.

**Comment by slromero-indra** [comment]
Ya están creados los documentos pdfs del modelo de BBDD, además del fichero en PowerDesigner para modificar el modelo si fuese necesario.

La adaptación a un programa de código abierto queda postergada hasta la subida de la versión 1.2, se debe analizar todas las herramientas de código abierto y se realizará un posterior análisis para ver si alguna de estas herramientas ofrece una potencia similar a power designer.

**Comment by sgelabert-dgtic** [comment]
Els fitxers no estan ubicats en directori correcte segons les directrius del plaanibal:
http://www.plaanibal.com/c/document_library/get_file?p_l_id=11763&folderId=46917&name=DLFE-4522.pdf

Els PDFs, s'han de moure dins doc/pdf/
Els fonts d'han de deixar dins doc/

**Comment by slromero-indra** [comment]
Buenas, revisamos los documentos y actualizamos la distrución.

**Comment by slromero-indra** [comment]
Buenas, ya están realizados todos los cambios.

**Comment by sgelabert-dgtic** [comment]
- S'hauria d'agafar com a base el document "Anàlisi tècnic GUSITE 2014" i integrar-ho en el document actual "GUSITE-1.2 -Modelo BBDD"
- El model es limita a definir relacions, ja que es fa la feina, seria més útil utilitzar un altre notació que permeti especificar més informació en les relacions (FK, obligatorietat de les relacions, ...). Si el problema és la visibilitat/llegibilitat del  diagrama, llavors segmentar conceptualment el model.
- S'haurien de descriure breument les noves taules incorporades en GUISTE 1.2 i les seves relacions (el document "GUISTE 1.2-Desarrollo de temas" us pot servir de base).
-  Com a norma general i per tenir coherència amb la majoria de documentació ja generada, convindria que la documentació estigués en català. Això no vol dir que ens posem a traduir documents ja generats, s'ha d'agafar simplement com a criteri d'ara en endavant.

**Comment by rsanz-indra** [comment]
La documentación a generar tendrá la siguiente estructura:
- diagrama global
- listado de tablas con su descripción
- diagrama particular de los principales subsistemas

**Comment by rsanz-indra** [comment]
Se me pasó comentar que deberían estar los cambios en 8-12h.

**Comment by slromero-indra** [comment]
Se suben los documentos relacionados
