### ISSUE TITLE
Integrar la gestión de uris en los formularios de contacto

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#27]

**Comment by sgelabert-dgtic** [comment]
S'accepta desenvolupament de la tasca segons darrer document d'estimació enviat 31/07/2017

**Comment by bgarcia-dgtic** [comment]
Hola, referent al document "0079_DGDT_COMPONENTE_FORMULARIO_CONTACTO.pdf", he creat un formulari de contacte, però a l'hora d'inserir-lo com ha component, no hem permet fer-ho ja que no m'apareix al llistat de components. Adjunt captures de pantalla
![captura1](https://user-images.githubusercontent.com/26536678/36307689-8b64d3e0-131d-11e8-9bee-d7eb267f8101.jpg)
![captura2](https://user-images.githubusercontent.com/26536678/36307692-8dc47550-131d-11e8-9944-50f24badbbdf.jpg)

**Comment by dmadronal-indra** [comment]
Buenas,
Ese desarrollo no se llego a realizar, la tarea se paso a unplanned. adjunto enlace a la tarea [#79](https://github.com/GovernIB/gusite/issues/79).

**Comment by sgelabert-dgtic** [comment]
- Hem detectat que el títol dels formularis de contacte surt  tallat a 100 caràcters. Potencialment el camp antic podia tenir fins a 4000 caràcters.
- Endemés els enllaços ja creats per identificador de formulari de contacte han deixat de funcionar (Exemple: https://www.caib.es/sites/participacio/contacte/6598/)
- Pareix que les línies d'un formulari tipus "Títol del formulari de contacte" no es presenten. Aquestes haurien de presentar-se com un apartat/secció del formulari
- Falta una botó de previsualització d'un formulari de contacte concret.

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos actualizado la aplicación para que recupere el titulo de la linea en lugar de el nuevo campo, de esta manera no se reproducen los problemas de texto cortado. (puntos 1 y 3) 

Respecto al enlace, el error solo se reproduce si en enlace se ha añadido manualmente copiando la antigua url, si se añade a través de la aplicación funciona correctamente. 
Estamos trabajando en una posible solución que permita que los que han añadido la url manualmente puedan seguir accediendo.

Respecto al botón de previsualización, esta funcionalidad no estaba contemplada en el desarrollo, ¿se podria tratar en una tarea nueva?

**Comment by sgelabert-dgtic** [comment]
Em pareix bé com a solució temporal, ho passarem a pre-producció i ho avaluam. D'entrada veig que el camp "Nom del formulari" no ens serveis de gaire...
Em detectat error no controlat en l'alta d'un nou formulari quan no s'indica "Correu destí". S'ha de controlar l'obligatorietat d'aquest camp (quan edites un formulari existent si que ho fa).
Respecte al redireccionament, si ja no es produiran URL antigues no té sentit fer redirecció. Tal vegada es més eficient passar script de BBDD per reconvertir aquestes URLs. Ho avaluau?
Pel que fa al botó de previsualització, no és prioritari i ho podem deixar per la versió 1.5.1

**Comment by sgelabert-dgtic** [comment]
- Pendent de fer les proves en pre-producció de la solució temporal i després d'haver analitzat les possibles solucions definitives, us pas el que hem acordat:
  - Deixar el camp "Nom del formulari" com identificador a nivell de backoffice i limitat a 100 caràcters
  - Utilitzar el camp "Nom del formulari" como a mètode de generació del camp URI
  - Deixar el camp de línia "Títol del formulairi" com Títol en el frontal
  - Modificar l'script per emplenar el camp "Nom del formulari" perquè, a nivell de backoffice, ens permeti diferenciar entre formularis en aquells casos que el nom sigui molt llarg. Per exemple, truncar el nom i afegir el codi del formulari
- Pel que fa a les redireccions, d'entrada ho deixam sense implementar i modificarem manualment els enllaços amb URL antigues
- Resta per controlar l'error d'alta de formulari quan no s'indica "Correu destí"
- El botó de previsualització passarà a la versió 1.5.1

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos realizado las siguientes modificaciones:
- Actualizado el script de BBDD para que borre los datos actuales de uris y títulos y los regenere en función de lo acordado. (títulos duplicados, o más largos de 100 caracteres se le añade el código del formulario para poder identificarlos). Las uris se vuelven a regenerar en base a los títulos.  Se puede pasar directamente el script gusite_update_data_from_1.4_to_1.5.sql para actualizar la información.

- Revisado el Backoffice para que se use el título en lugar de la línea.
- Controlado el error al dar de alta un formulario sin un correo electrónico

- Para el botón de previsualización, ¿creareis una nueva tarea o lo tratamos en esta?
