### ISSUE TITLE
Homogenizar el funcionamiento de las uris y traducción del backoffice. 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#28]
Se trata de aplicar los cambios realizados en la incidencia 21 y 22, en la resta de módulos.
22# Obligación introducir título, y en caso este vacia la uri, se rellena apartir info del título. Tanto en catalán como otros idiomas. En castellano, permitir vaciar todos los campos y que no de errores. 
21# Control uri global, en lugar de por microsite particular. 

Los módulos afectados:
a) Configuración de listados
b) Recursos de listados 
c) encuestas (Este módulo no esta integrado el traductor, con lo que por el momento no es preciso #22)

**Comment by episano-dgtic** [comment]
Otras peticiones que estarán relacionadas:
La petición integrar traductor en encuestas, está en la incidencia #2 
Petición de integrar la gestión de uris a los formularios de contacto #27

**Comment by episano-dgtic** [comment]
He podido probar el pto a y c. Pero el mantenimiento de los elementos de los listados no. Me falla constantemente con "petición rebuda no correcta".
Llegando a ver que aparecen datos que aparentemente  no corresponden.
En los logs, lo de siempre.. null problemas bd ect.

**Comment by slromero-indra** [comment]
Buenas, además del error para eliminar la restricciones de unicidad del index, se ha solucionado el problema tras presionar el botón de traducir, ya están todos los cambios comiteados.

**Comment by episano-dgtic** [comment]
En vuestro entorno funciona. En el nuestro no, Commit pasado por salvador de esta mañana .. Está commitado todo?
Adjunto logs de nuestro servidor. 
[server_06042016.txt](https://github.com/GovernIB/gusite/files/206087/server_06042016.txt)

**Comment by episano-dgtic** [comment]
Perdón.. pensabamos que se había subido la última versión. Pendiente probar nuestro entorno.

**Comment by episano-dgtic** [comment]
El error al traducir se ha solventado. Pero me tras algunas modificaciones he recibido el error "petición rebuda no correcta". Con lo que todavía no hemos encontrado todos los casos provocan problemas listados.

**Comment by sgelabert-dgtic** [comment]
Es detecten nous error relacionats amb l'eliminació del titol i la URI en diferents idiomes en llistats i enquestes
Adjuntem log del servidor d'aplicacions:
- Error reproduible quan eliminam la URI d'un idioma no configurat
  [log_configuracio_llistat.txt](https://github.com/GovernIB/gusite/files/216572/log_configuracio_llistat.txt)
- Error reproduible quan gravam una URI sense titol en un idioma no configurat
  [log_enquestes.txt](https://github.com/GovernIB/gusite/files/216596/log_enquestes.txt)

**Comment by episano-dgtic** [comment]
Revisado en caibter
