### ISSUE TITLE
En el pie del microsite no se recupera correctamente el dominio

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#32]
En el pie del microsite no se muestra correctamente el dominio.
La lógica actual es:
      1) mostrar el dominio específico del microsite si existe. Sino existe -> 2
      2) Mostrar el dominio de la unidad orgánica responsable del microsite (campo "domini" del rolsac) si existe. sino existe ->3
      3) No muestra nada.. tampoco la etiqueta. 

En 1.2  cuando no hay dominio especifico del microsite 
El texto que pone es:
https://proves.caib.es/govern/organigrama/area.do?coduo=8&lang=ca
Cuando debería mostrar el campo "Domini" del la unidad orgánica en cuestión. 

Podéis ver el funcionamiento correcto en el microsite producción http://dgtic.caib.es/gestioCAIB

**Comment by episano-dgtic** [comment]
![pie_1_2](https://cloud.githubusercontent.com/assets/17451683/14250459/d1a759ea-fa7e-11e5-8f98-f48404f5c9c4.gif)

**Comment by episano-dgtic** [comment]
Aparentemente funciona. Pero para poder probarlo al 100% en vuestro entorno, deberían aparecer los datos del ROLSAC de vuestro entorno y no como acurre ahora "coorporacion ACNE". Así de paso tb. comprobaría la miga de pan con los enlaces a la web corporativa de vuestro entorno.

**Comment by ghost** [comment]
Se verifica que aparecen los datos de rolsac.

**Comment by episano-dgtic** [comment]
En nuestro entorno no funciona.

**Comment by episano-dgtic** [comment]
El problema es que hicisteis los cambios para el nuevo front, y no para el antiguo.

**Comment by dmadronal-indra** [comment]
Se han aplicado los cambios al frontal antiguo.
