### ISSUE TITLE
Errada en els formularis de contacte

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#35]
Hem detectat una errada en l'eliminació de camps en Formularis de Contacte 
Adjuntam errada del servidor d'aplicacions.
[log_formulari_contacte.txt](https://github.com/GovernIB/gusite/files/216563/log_formulari_contacte.txt)

**Comment by episano-dgtic** [comment]
El error continua ocurriendo en caibter, no sé si es que no está la última versión?
Cuando tenga que validarlo recuerda indicar validación entorno INDRA, ya que es el primer paso.
