### ISSUE TITLE
bug en encuesta

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#37]
Problema si se trata de eliminar una encuesta con preguntas que tengan respuestas de tipo usuario. 
El problema se repite tratando de eliminar la pregunta que tiene respuestas de tipo usuario, o tratando de eliminar la respuesta de tipo usuario. 

El error del backoffice:
"Error en la capa de dades : java.rmi.ServerException: EJBException:; nested exception is: javax.ejb.EJBException: org.hibernate.exception.ConstraintViolationException: could not execute update query "
Ojo si este error se puede replicar si previamente alguien ha contestado la encuesta con datos en esa respuesta de usuario. Si la encuesta no ha sido contestada se puede eliminar la encuesta, pregutna o respuesta sin problemas. 
[error_eliminarRESPUESTA.txt](https://github.com/GovernIB/gusite/files/227377/error_eliminarRESPUESTA.txt)

**Comment by mcgonzalezu-indra** [comment]
Si se borraba una encuesta o una pregunta que tenía respuestas de tipo usuario, daba un error por pantalla, ya que no se borraban los registros de la tabla RespuestaDato que se insertan cuando se envía una respuesta de tipo usuario.

**Comment by mcgonzalezu-indra** [comment]
![image](https://cloud.githubusercontent.com/assets/18311022/14776476/2754d93c-0ac7-11e6-8eac-9f4cbde109e5.png)
