### ISSUE TITLE
Bug Visualización microsite en castellano "Poliesportiu prínceps d'Espanya" 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#39]
Bug Visualización microsite en castellano "Poliesportiu prínceps d'Espanya", parece un caso aislado. ME he asegurado que estuviera traducido el microsite, el arbol de menu y los contenidos. Y pese a ello sigue dando el error 
Tb. he comprobado que la uo asociada a dicho microsite esté traducida y visible.

Estado HTTP 500 - 
javax.servlet.ServletException: javax.servlet.jsp.JspException: Cannot find bean MVS_micrositetitulo in any scope
    org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:852)
    org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:781)
    org.apache.jsp.v4.contenido.contenido_jsp._jspService(contenido_jsp.java:193)
    org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:369)
    org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:322)
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:249)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    org.apache.struts.action.RequestProcessor.doForward(RequestProcessor.java:1069)
    org.apache.struts.action.RequestProcessor.processForwardConfig(RequestProcessor.java:455)
    org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:279)
    org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
    org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:507)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    es.caib.gusite.microfront.util.EncodingFilter.doFilter(EncodingFilter.java:36)
    org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)

causa raíz

**Comment by episano-dgtic** [comment]
Comentaros que he podido previsualizarlo en castellano sin problemas.. y que el microsite no estaba visible al público. 
En el momento que he indicado el microsite visible, ya no peta en castellano. 
Hay que evitar que de el pete en el servidor, y dar una ayuda al gestor para que sepa que debe hacer para que pueda visualizarlo correctamente en ambos idiomas. 
Como he podido solventarlo cambio la prioridad a baja.

**Comment by episano-dgtic** [comment]
https://intranet.caib.es/sacmicrofront/contenido.do?mkey=M1203261259291635041630&cont=46114&&lang=es

**Comment by episano-dgtic** [comment]
En pruebas he visto claramente como replicarlo. Si añado el título en castellano funciona.. y si no está da el error. 
En producción.. pese a haberlo insertado ha tardado más en arreglarse.. en tiendo que por memorias intermedias.

**Comment by episano-dgtic** [comment]
Se debería obligar ha introducir el título del microsite si está configurado el microsite en dicho idioma. 
Similar a lo que se ha hecho con las páginas, listados etc..

**Comment by mcgonzalezu-indra** [comment]
Cuando se guarda o se modifica un microsite con Castellano u otro idioma que no sea el de por defecto marcado y sin título para ese idioma sale el mensaje "Has d'indicar el camp Títol o esborrar-lo per a l'idioma Castellano"

**Comment by mcgonzalezu-indra** [comment]
![image](https://cloud.githubusercontent.com/assets/18311022/14814983/18eb7f26-0ba9-11e6-936b-fcd899dca632.png)

**Comment by episano-dgtic** [comment]
Me parece bien la idea que propones, pero lo has implementado sólo para el castellano cuando debería ser cualquier idioma. 
En microsite "prueba URI estela" He configurado el microsite en catalán, castellano y aleman y únicamente me pide introducir el título en castellano. Tengo indicado que tb. en aleman, y puedo dejarlo sin título en dicho idioma.

**Comment by episano-dgtic** [comment]
perfect
