### ISSUE TITLE
Problema en la previsualización de contenidos en el caso del borrador de páginas para el nuevo diseño (URI)

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#40]
No es posible la previsualización del borrador de páginas para el nuevo diseño (URI), ya que usa la URI pública con lo que visualiza los contenidos "públicos". 
![previsualizacion_borrador](https://cloud.githubusercontent.com/assets/17451683/14705999/8a83e48e-07bc-11e6-8bd3-261fda98115b.gif)

**Comment by episano-dgtic** [comment]
No está bien del todo. Ahora se puede previsualizar el borrador en catalán. Pero no en el resto de idiomas. 
Si desde el borrador cambio de idioma, me dirige a la página "pública" en castellano. En cambio si le doy al borrador desde el backoffice en castellano me dirige a la versión en catalán. 
Se debería arreglar ambos casos. 

El boton del backoffice para visualizar la "versión pública" en castellano tb. le ocurre que remite a la información en catalán.

**Comment by episano-dgtic** [comment]
Ahora si se puede previsualizar los contenidos en todos los idiomas. 
Pero.. con el nuevo diseño si accedes al borrador y cambias de idioma continua remitiendo a la versión pública y no a la versión del borrador.

**Comment by dmadronal-indra** [comment]
Probado en caibter, microiste  "Prueba URI Estela"

**Comment by episano-dgtic** [comment]
Ahora si.. perfect

**Comment by episano-dgtic** [comment]
Acabo de detectar que con el nuevo entorno sites, si los contenidos son "no Visibles" no se pueden previsualizar los contenidos. 

Indica "Error: No s' ha trobat la pàgina sol·licitada "

**Comment by slromero-indra** [comment]
Buenas, solucionado el problema y comiteado. 

Aunque el error obtenido es similar a como se creó esta issue, el alcance es totalmente distinto y se debe a un problema totalmente diferente al planteado originalmente.

**Comment by sgelabert-dgtic** [comment]
Afegeix-ho bug detectat per n'Estela:
Al activar el borrador, y querer subir los cambios del editor prototipo al principal, no funciona el 1er botón. Sí el del intercambio y de principal al borrador.

**Comment by slromero-indra** [comment]
Buenas, podéis verificarnos si el último bug está solucionado?

**Comment by sgelabert-dgtic** [comment]
OK
