### ISSUE TITLE
Anàlisi de problemes greus rendiment GUSITE 1.2

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#41]
Existeixen problemes greus de rendiment sobre l'entorn de producció amb la versió 1.2 de l'aplicació.
Problemàtica detectada:
- Exhauriment del nombre de connexions contra la BBDD. S'ha de revisiar quan i perquè s'obre més d'una connexió de BBDD per petició.
- Errors JavaHeapSpace amb la descàrrega de fitxers voluminosos. Determinar perquè sobre un entorn controlat amb un sol usuari, la descarrega d'un fitxer de 44MB provoca un JavaHeapSpace del servidor amb 1GB de memòria exclusiva assignada.
- Consultes costoses sobre la BBDD. S'adjunten en la incidència plans d'execució a optimitzar. Es comprova també que hi ha consultes que no empren bind variables  (SELECT .... where archivo0_.DCM_CODI=204493) la qual cosa provoca cada vegada el recalcul del pla d'execució pel SGBBDD.
- Alguna petició sobre llistat de notícies provoca la descàrrega de gran quantitat de registres relacionats. S'adjunta pla d'execució.

**Comment by sgelabert-dgtic** [comment]
[GUSITE_execplan_big_files.zip](https://github.com/GovernIB/gusite/files/234040/GUSITE_execplan_big_files.zip)
[GUSITE_execplan_content.zip](https://github.com/GovernIB/gusite/files/234041/GUSITE_execplan_content.zip)
[GUSITE_execplan_noticies.zip](https://github.com/GovernIB/gusite/files/234043/GUSITE_execplan_noticies.zip)

**Comment by episano-dgtic** [comment]
En el entorno de pruebas os he indicado microsites que podrían servir para el juego de pruebas:

1) Para el tema archivos grandes: 
             test archivos GRANDES. 58 CES. https://proves.caib.es/sacmicrofront/index.do?lang=ca&mkey=M16 los enlaces a los ficheros de la portada. 

2) Elementos en los listados:
             test elementos listado. Institut d'Estudis Autonòmics. 
             https://proves.caib.es/sites/M08092211155013147625/ca/l/normativa-8165/?campa=yes
             ó frontal antiguo: https://proves.caib.es/sacmicrofront/index.do?lang=ca&mkey=M08092211155013147625
          En este microsite en el back-office el pop-up de recursos de sistemas, tb. carga los elementos del listado, y si mal no recuerdo no está optimizado(paginado)  con lo que seguramente tenga poco rendimiento (https://proves.caib.es/sacmicroback/recursos.do?tiny=true&id=61258&idMenu=3725)

**Comment by episano-dgtic** [comment]
Para que tengáis estadísticas de la bd en real:
         numero fichero:106002, con el tamaño acumulado entre todos 58163MB:
                >100MB 15; >50MB 53; >25MB 159; >15MB 328; >10MB 572; >5MB 1981
