### ISSUE TITLE
Controlar error en la creación de menús sin ningún dato

### ISSUE THREAD

**Issue by dmadronal-indra** [GovernIB/gusite#42]
Mostrar un mensaje de validación al intentar crear un menú sin ningún dato. Controlar que como mínimo se introduzca el idioma por defecto.
![image](https://cloud.githubusercontent.com/assets/17270582/14828682/51e6bef0-0be8-11e6-841f-7a3ed277f5ad.png)

Controlar además la visualización correcta, cuando se eliminan los textos de un menú.
![image](https://cloud.githubusercontent.com/assets/17270582/14829890/1e5739d8-0bee-11e6-9337-755533b07128.png)

**Comment by episano-dgtic** [comment]
Efectivamente ahora no permite crear un apartado de menu sin texto en el idioma por defecto. 
Pero te permite modificar uno con texto y dejarlo vacio.
