### ISSUE TITLE
Controlar error al intentar eliminar una imagen asociada a un menú

### ISSUE THREAD

**Issue by dmadronal-indra** [GovernIB/gusite#44]
Controlar error no controlado a intentar eliminar una imánen asocaiada a un menú.
![image](https://cloud.githubusercontent.com/assets/17270582/14830893/5cba7af0-0bf3-11e6-8318-7b5bb63b8331.png)

![image](https://cloud.githubusercontent.com/assets/17270582/14830854/21ee04c8-0bf3-11e6-90f0-b7a78a025176.png)

**Comment by episano-dgtic** [comment]
He probado en vuestro sistema y no he podido replicar el problema.
