### ISSUE TITLE
Aplicación mejoras de rendimiento GUSITE 1.2

### ISSUE THREAD

**Issue by pbauza-dgtic** [GovernIB/gusite#45]
Implementar mejoras acordadas que permitirán disminuir el consumo de memoria de la
aplicación y de reducir el coste de las llamadas a base de datos detectadas como problemáticas.

**Comment by pbauza-dgtic** [comment]
Documento de estimación de tarea
[0151_AplicacionMejorasRendimientoGUSITE12.pdf](https://github.com/GovernIB/gusite/files/246719/0151_AplicacionMejorasRendimientoGUSITE12.pdf)

**Comment by sgelabert-dgtic** [comment]
A continuación se detallan las mejoras acordadas con la DGDT:
1. Eliminar la comprobación si la sesión está ‘obsoleta’ o ‘dirty’ al cerrar una sesión, sólo utilizado
para mostrar un mensaje por log y provoca distintos problemas de memoria al lanzarlo.
2. Modificación del mapeo de las traducciones en las noticias de Fetch.SUBSELECT a
Fetch.SELECT
3. El almacenaje de ficheros se realizarán tanto en la base de datos como en el sistema de
archivos.
4. En la clase archivo cambiar la anotación del fichero a ‘Transient’ para que no recupere la
información.
5. Creación de una nueva clase ArchivoFull donde se mapeará y recuperará el fichero.
6. Evitar que los ficheros de la nueva clase se cacheen a través del ehcache.xml.
7. Actualización del EJB encargado del tratamiento de archivos para que almacene el fichero a
través de la nueva clase ArchivoFull y de almacenar el fichero también siempre en la base de
datos.
8. Limpiar el campo fichero de la clase Archivo donde se no utilice ni manipule un fichero para
liberar memoria (clases ArchivoController, ArchivoAction y ArchivoPubAction).
9. Revisión de la aplicación para que los diversos cambios realizados no afecten a ninguno de los
formularios de la aplicación.
10. Ejecución de las pruebas de carga antes y después de los cambios para validar los cambios
realizados.
11. Actualizar la documentación relacionada.
12. Verificar en los diferentes entornos las modificaciones realizadas.

**Comment by slromero-indra** [comment]
La solución planteada se basaba en que el código esta preparado para que en la parte web (front y back) se detecta si Archivo.datos era nulo para recuperar de Filesystem. 
Archivo.datos solo debía estar rellenado en los casos que implicaban que se guardase el fichero.
Hemos detectado que en las funciones de recuperar archivo de ArchivoFacadeEJB se recupera los datos de filesytem si estos son nulos. 
Entendemos que deberíamos hacer que estas funciones no recuperen datos de Filesystem.

**Comment by pbauza-dgtic** [comment]
@slromero-indra El funcionamiento debería ser el siguiente:
1) Siempre guardar los datos en BBDD y _filesystem_ a partir de la nueva versión
2) Definir una _property_ que indique si los datos se recuperan de BBDD o de _filesystem_.
3) Si la _property_ indica que se recuperen de BBDD, ir directamente a BBDD a recuperar el fichero (nunca a disco) y en caso de que indique que se debe recuperar de _Filesystem_ ir siempre a _filesystem_ independientemente del valor de Archivo.datos. 

De hecho, Archivo.datos siempre será nulo. Es decir, esta nueva solución, implica trabajar siempre con una versión "LITE" de Archivo. Donde Datos sea _transient_ y que el único caso en que se recuperará el valor de Datos será cuando se esté trabajando con la _property_ apuntando a BBDD. 

En dicho caso se irá a buscar Datos de directamente para retornarlo.

**Comment by pbauza-dgtic** [comment]
@slromero-indra Nota: la _property_ que indico en el punto 2) ya existe, se llama: _es.caib.gusite.archivos.almacenarEnFilesystem=N_.
