### ISSUE TITLE
Depuració log servidor aplicacions GUSITE

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#47]
Es sol·licita depurar els errors més freqüents que apareixen en el log del servidor d'aplicacions:

1.-Parameters: Invalid chunk ignored. (5641 warnings en un dia)
WARN  [org.apache.tomcat.util.http.Parameters]  Parameters: Invalid chunk ignored.
El warning dóna quan es construeix una URL malformada (amb dues barres consecutives per exemple)

2.- Error al obtenir/muntar el menu (757 errors en un dia)
ERROR [es.caib.gusite.microfront.BaseAction]  [obtenerMainMenu, 6045, cafavicon.ico ] Error:  [montarmenu, 6045, cafavicon.ico ] Error=null

3.- Error al accedir a un MS inexistent (4628 errors en un dia)
ERROR [es.caib.gusite.microfront.BaseAction](http-10.215.5.28-28080-28) No s' ha trobat el microsite amb id m10 Stack = es.caib.gusite.microfront.base.Bdbase (prepararidsite >> linea:273) 

En cas que es determini que no són un bugs d'aplicació, canviar el nivell de log o evitar imprimir l'stack-trace a fi de tenir un log més manejable.

**Comment by sgelabert-dgtic** [comment]
Respecte a l'error "Invalid chunk ignored" us pas algunes URLs on s'ha localitzat l'error:

/sacmicrofront/noticia.do?idsite=625&cont=54684&&lang=ca
/sacmicrofront/noticia.do?cont=83516&idsite=274&&lang=es
/sacmicrofront/contenido.do?cont=79378&mkey=M09071609445624996924&&lang=es

**Comment by sgelabert-dgtic** [comment]
He analitzat els logs d'Apache respecte al error del favicon i pareix que els navegadors el sol·liciten per defecte:
66.249.93.188 - - [02/Jun/2016:00:03:35 +0200] "GET /favicon.ico HTTP/1.1" 404 54 "http://www.caib.es/sacmicrofront/contenido.do?idsite=567&cont=21357&lang=ca&campa=yes" 

_"When a browser hits your web site, it will ask for a page, and it can also make a request for the favicon.ico file, as shown in these entries from my ApacheSW access.log file:
access.log entries:
127.0.0.1 - - [20/May/2007:20:55:30 -0700] "GET / HTTP/1.1" 200 44
127.0.0.1 - - [20/May/2007:20:55:30 -0700] "GET /favicon.ico HTTP/1.1" 404 209
Did you notice the 404 next to the request for /favicon.ico? That means that the server could not find the /favicon.ico file in its document root directory (ie, /htdocs/ by default)."_

Per tant, convé afegir-lo a la capçalera de les pàgines:
<link rel="shortcut icon" href="<%=request.getContextPath()%>/favicon.ico" type="image/x-ico"/>

Cal comprovar si és necessari que estigui també disponible des de l'arrel del context.

**Comment by sgelabert-dgtic** [comment]
Adjunt favicon en format png. No me'l deixa pujar en format ico
![favicon](https://cloud.githubusercontent.com/assets/17268396/15853186/4f33ee1c-2ca4-11e6-91ac-df252be75045.png)

**Comment by sgelabert-dgtic** [comment]
Respecte al punt 3. 
Es tracta d'evitar que surti el següent log en el servidor [log_gusite_ms_inexistent.txt](https://github.com/GovernIB/gusite/files/302366/log_gusite_ms_inexistent.txt)  quan hi ha una referència a un codi de MS inexistent. Es sol·licita:
- Evitar que surti l'stack-trace de Java en els mètodes involucrats :
  es.caib.gusite.microfront.home.UserRequestProcessor.processPreprocess()
  es.caib.gusite.microfront.base.DelegateBase.obtenerMicrositebyKey()
  es.caib.gusite.micropersistence.ejb.MicrositeFacadeEJB.obtenerMicrositebyKey()
- Fer que s'imprimeixi la clau de MS sencera quan s'imprimeix l'error "No s' ha trobat el microsite amb id m10". Actualment es fa un substring de 3 caràcters de Microfront.PMKEY
- La gestió d'errors de l'aplicació condueix a una pàgina pròpia on s'indica si l'error és a nivell de front, microsite o pàgina. El problema és que sempre torna un codi http 200 i hauria de tornar el següent:
  **HTTP 404**
  static public final String ERROR_MICRO_MSG = "No s' ha trobat el microsite amb id ";
  static public final String ERROR_MICRO_MSG_NULL = "No s' ha sol·licitat un microsite";
  static public final String ERROR_PAGINA_MSG = "No s' ha trobat la pàgina sol·licitada";
  static public final String ERROR_DOCU_MSG = "No s' ha trobat el document sol·licitat";
  **HTTP 403**
  static public final String ERROR_ACCES_MSG = "No disposa del ROL necessari per accedir al microsite."
  **HTTP 440**
  static public final String ERROR_SESSIO_MSG = "Ha excedit el temps màxim de sessió.";

**Comment by sgelabert-dgtic** [comment]
- Segueix sense apareixer el favicon en la pestanya del navegador
- Quan s'accedeix a un MS inexistent ara torna un 404, però en la pestanya apareix "Error de Microste
  8888888888888888888". O bé es deixa com "Error de Microste" o bé s'indica l'id de microsite inexistent passat com a paràmetre en la URL de la petició.

**Comment by slromero-indra** [comment]
Está ya arreglado el tema del favicon y del texto en la pestaña. Es importante tener en cuenta que si se prueba en un microsite con el tema2015, antes hay que volver a importar el proyecto. Hay que tener cuidado con el tema de las cookies, antes de realizar las pruebas, limpiarlas porque se suele guardar el favicon en ellas.
