### ISSUE TITLE
Activar missatge d'alerta per IE en el backoffice

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#48]
Es sol·licita activar missatge d'alerta per qualsevol versió d'IE a nivell de backoffice indicant que es un navegador no soportat

**Comment by episano-dgtic** [comment]
En vuestro entorno funciona pero en el nuestro no.. indica un error de javascript: "getInternetExplorerVersion() no está definido."
Respecto al mensaje de aviso, se debe cambiar el mensaje de en lugar de "Navegador Obsolet" por "Navegador no soportat"

**Comment by slromero-indra** [comment]
Se ha actualizado con el fichero que faltaba y actualizado el mensaje.
