### ISSUE TITLE
Error en la gestión de componentes de algunos microsites. 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#50]
[error_componentes.txt](https://github.com/GovernIB/gusite/files/315662/error_componentes.txt)
![error_componentes](https://cloud.githubusercontent.com/assets/17451683/16072771/d0351f7e-32e2-11e6-9d2f-88fe65668216.gif)
Podéis replicarlo en el microsite "Ajudes del FOGAIBA" del entorno pruebas.

Desconozco la razón por la que ocurre en este y otros microsites, en algunos casos funciona.

**Comment by episano-dgtic** [comment]
Como está esta incidencia?

**Comment by slromero-indra** [comment]
Buenas, estamos en ello, estamos realizando las últimas pruebas y lo subiremos a lo largo del día.

**Comment by episano-dgtic** [comment]
En producción sigue ocurriendo.. Os pasaremos los logs de producción. A las 8:19 he hecho un fallo controlado en el microsite de Fons Europeus.

**Comment by slromero-indra** [comment]
Buenas, si podéis, además de pasarnos el log, podéis pasarnos el microsite para exportarlo en nuestro entorno o pasarlo a vuestro entorno de pruebas (y ya nos encargamos de pasarlo al nuestro)?

Saludos!

**Comment by sgelabert-dgtic** [comment]
Adjunt log del servidor d'aplicacions en PROducció:
[log_error_pro.txt](https://github.com/GovernIB/gusite/files/361035/log_error_pro.txt)

Pareix que persisteix el problema en:
es.caib.gusite.micropersistence.ejb.ComponenteFacadeEJB.listarComponentes(ComponenteFacadeEJB.java:257)

**Comment by episano-dgtic** [comment]
He tratado exportar el microsite de Fondos y no he podido.. Pero lo he conseguido con el de Ajudes de FOGAIBA, que tb. da problemas en producción. Pese a que en pruebas va bien. 
[M10021211091530890224_20160713_111111_microsite.zip](https://github.com/GovernIB/gusite/files/361103/M10021211091530890224_20160713_111111_microsite.zip)

**Comment by slromero-indra** [comment]
Buenas, estamos revisando el error y parece que no nos da ningún error, se está seguro si está subido el último ear. Hemos visto que en el algún microsite en producción (http://www.caib.es/sites/iqpib/ca/agenda/20160728) no se observa el favicon (puede que porque no esté actualizado el tema) y en la última versión se tendría que ver, al menos en nuestro entorno se ve. En pruebas caib, he confirmado que tanto en el front nuevo (quitando el temaIndra) como en el front viejo se observa el favicon, me podéis confirmar si en producción se observa?
