### ISSUE TITLE
Error al enviar enquestes

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#52]
Hi ha un error al enviar enquestes:
`Error: javax.servlet.jsp.JspException: Cannot find bean MVS_microsite in any scope Cannot find bean MVS_microsite in any scope 
`
L'error es produeix en el mètode BdEnvioencuesta.procesaformulario() i pareix que està relacionat amb les correccions introduïdes en la incidència #38 

```
es.caib.gusite.microfront.encuesta.util.BdEnvioencuesta.procesaformulario()
12:34:20,300 ERROR [BdEnvioencuesta] String index out of range: 0
```

Adjunt log del servidor d'aplicacions 
[severlog.txt](https://github.com/GovernIB/gusite/files/315972/severlog.txt)

Per reproduir l'error:
- https://proves.caib.es/sacmicrofront/encuesta.do?lang=ca&mkey=M157&cont=1374
- Introduir algun text en el camp "Nombre"
- Enviar l'enquesta

**Comment by rsanz-indra** [comment]
Ya hemos localizado el error. Cuando lo subsanemos os avisamos.

**Comment by slromero-indra** [comment]
Hemos visto que además del problema avistado, las valores en el campo name difieren entre cada uno de los tipos (Radiobutton, Textbox y Checkbox) por lo que hay que revisarlo para unificarlo correctamente.

**Comment by slromero-indra** [comment]
Buenas, ya está solucionado la incidencia en el anterior frontal, podéis testearlo o subirlo si deseáis (juraría que encuestas en el frontal nuevo no existen). Respecto a la versión del frontal nuevo, a lo largo del día estará solucionado.

**Comment by slromero-indra** [comment]
Buenas, ya está solucionado en ambos frontales.

**Comment by episano-dgtic** [comment]
Aparentemente funciona.
