### ISSUE TITLE
Error gestion enlaces en front gusite

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#53]
1) Error en los enlaces desde el menu, debido a que se añade a la url un parámetro &uricont=URI: 
Se puede detectar fácilmente incluyendo un enlace a una web externa ex: http://www.uib.es, el sistema trata de acceder a la url final ="http://www.uib.es&uricont=URI"
2) No funcionan los enlaces en las páginas de contenidos a servicios del propio microsite (mapa, agenda, listados, otras páginas...)
Si en URL de la págian se indica "contenido.do?idsite=157&cont=17186" la url que monta es "https://proves.caib.es/sites/M157/enlaces_servicios_microsites/contenido.do?idsite=157&cont=17186" 
provocando un fallo.

Ya que debería remitir a https://proves.caib.es/sacmicrofront/contenido.do?idsite=157&cont=17186**&lang=ca** para así mendiante la gestión de URI y al detectar que es un microsite 1.3 accedamos a su correspondiente URI en 1.3="https://proves.caib.es/sites/M157/introduccio_als_microsites-17186/"

Para que lo podáis replicar fácilmente en vuestro entorno, os he creado el microsite "Enlaces con tema 1.3"

**Comment by slromero-indra** [comment]
Realizando un análisis se pensó en la posibilidad de modificar el TinyMCE para que almacenase una ruta distinta siempre que el front fuese el nuevo. Tras realizar varias pruebas, se tuvo que desechar por varias razones:   <ul><li> exigiría crear un script para modificar todos los contenidos ya creados.</li>
<li> además, en caso de cambios en la versión del front, exigiría volver a realizar los cambios hacia atrás, aumentando la complejidad. </li>
<li> cambios en la versión de tinymce exigiría posibles cambios o incompatibilidades. </li></ul>
Para no modificar el contenido de lo almacenado, se va a proceder a incluir un nuevo método que capture la url ( @RequestMethod(/URI_MICROSITE/URI_CONTENIDO/URL). Se capturaría la url y se comportaría similar a cuando un contenido tiene una url asignada. Analizándolo más a fondo hemos visto que no redirige al front antiguo sino que hay un LegacyController que capturaría la url (por ejemplo, cuando llamamos al home con 'home.do').
Mañana confirmo si se puede generar todo correctamente pero me extraña mucho la implementación generada en el nuevo front que mezcla un poco las uris del front antiguo.

**Comment by sgelabert-dgtic** [comment]
En el vostre entorn en el següent URL (http://caibter.indra.es/sites/M160621130647629/pagina_enlace_a_servicios/) els enllaços als llistats no funcionen.

Adjuntem captura de pantalla;
![enllacosllistats](https://cloud.githubusercontent.com/assets/17268396/17019763/4df06b4a-4f3e-11e6-8b23-094c49eba048.jpg)

**Comment by episano-dgtic** [comment]
En nuestro entorno de pruebas no funciona. 
https://proves.caib.es/sites/M157/ca/enlaces_servicios_microsites/
Concretamente   https://proves.caib.es/sites/M157/ca/l/noticias-8765/

**Comment by slromero-indra** [comment]
Buenas, estamos intentanto acceder a https://proves.caib.es/sacmicroback/ con el usuario:e24394731b para exportar el microsite y probarlo, pero no podemos acceder tras hacer login nos da un error de permisos

![image](https://cloud.githubusercontent.com/assets/17451407/17212592/75ce8f60-54d0-11e6-8f66-0fe8f454738a.png)

**Comment by rsanz-indra** [comment]
Estaba la contraseña caducada.

**Comment by rsanz-indra** [comment]
Se ha actualizado en caibter el tema "nuevo" con tema2015. Para probar el cambio debería importarse de nuevo el  tema.
