### ISSUE TITLE
Millora accessibilitat GUSITE

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#55]
Es sol·licita efectuar una primera revisió d'accessibilitat global de l'aplicació. Concretament es demana:
- Correccions globals a nivell del nou front de GUSITE (identificació de l'idioma, canvis d'idioma, compatibilitat de DTD, pàgina comú d'accessibilitat, ...)
-  Millores d'accessibilitat a nivell de backoffice. Internament s'ha analitzat l'accessibilitat dels editors HTML i en aquest sentit per assegurar l'accessibilitat convé complir amb les recomanacions ATAG 2.0 del W3C https://www.w3.org/TR/ATAG20/ 
  Segons aquest informe https://www.w3.org/WAI/AU/2013/ATAG2ImplementationReport.html l'editor TinyMCEv3 + pluggin AChecker és la combinació més bona per complir amb l'accessibilitat.
  Per això es planteja l'actualització de l'editor TinyMCE a la darrera versió (crec que ara tenim la 2.1) i analitzar si la validació efectuada pel pluggin AChecker pot ser suplida per TAW (ja integrat pero també desactualitzat). L'objectiu es millorar al màxim el codi generat automàticament per l'editor.

Totes les millores han de ser conformes a la normativa UNE 139803:2012 basada en l'estàndard  WGAC 2.0 del W3C,

**Comment by slromero-indra** [comment]
Cambios reflejeados en esta issue: #5

**Comment by slromero-indra** [comment]
Buenas Salvador,

Ya se ha subido todos los cambios referentes a la accesibilidad de GUSITE (incidencias #5 y #55). Todos los cambios realizados, se han efectuado sobre los html tanto del frontal nuevo como del tema 2015, siendo el resumen de  los cambios realizados:
-   Añadido el idioma en la cabecera de todas las páginas.
-   Añadido  la fecha de última actualización a la página de accesibilidad.
-   Se ha revisado todas las imágenes de los htms y se ha incluido un alt con el nombre de la imagen en aquéllas que no tenían alt. Por ejemplo, en el listado de noticias y en la imagen principal de la cabecera (en el caso de la imagen de cabecera fue un poco más complejo el cambio, se cambió la etiqueta span con background por una imagen con descripción).
-   Se ha asociado correctamente el label a los option que antes se hacía incorrectamente (por ejemplo, en agendaCalendarListado).
-   Alteraciones en los niveles de encabezado (por ejemplo, eliminar etiquetas de tipo h1/h2/h3/h4 sin texto o bien reordenar el nivel de manera correcta, esto es visible en listarfaqs.html y contacto.html).
-   Se añaden condiciones para no generar lista vacías (por ejemplo, en mapa.html)
-   Se ha revisado todas las páginas y se han sustituido los <br> y <br /> por <p></p>
-   Se añaden las etiquetas de idioma en el pie.html para el cambio de idiomas.

Además de esos cambios, hemos observado algún comportamiento incorrecto con el idioma catalán. Por ejemplo, en listarfaqs.html según la palabra utilizada en el título de la pregunta, se genera un error con el idioma (que la palabra no se encuentra en el mismo idioma de la página), este problema se observa dependiendo de si se utiliza la palabra ‘tema’ o ‘temes’ (que no los reconoce correctamente en catalán) mientras con otras palabras en català como las palabras ‘títol’ o ‘cua’ no tienen el mismo problema.

Para las pruebas de accesibilidad, hemos utilizado 2 de los microsites que se utilizan en producción, ‘Impost turisme sostenible’ y ‘Ajudes del FOGAIBA’.  Para ambos microsites, hemos realizado 3 pruebas: sólo 1 página, con 4 de amplitud y con 4 de amplitud/profundidad. En ajudes del FOGAIBA, hemos observado una gran mejora, principalmente porque carece de mucho contenido no accesible (debido a una edición incorrecta con tinyMCE) mientras que en el microsite de Impost turismo sostenible, hemos observado una mejora más leve principalmente por dos problemas: mucho contenido no accesible de tinyMCE y porque muchos enlaces apuntan a govern el cual tiene bastantes errores de accesibilitat. En resumen, el resultado es bastante bueno y, cuando realicemos el cambio a la nueva versión de tinyMCE y arreglemos el código ya generado, mejoraría bastante los resultados en ambos microsites, sobretodo en el microsite de impost.

Los pdfs con los resultados del análisis para que puedas observar las mejoras  http://caibter.indra.es/descargas/pdfs_accesibilidad.zip
Los pdfs los hemos denominado de la siguiente manera:
Los ficheros con el prefijo ANT han sido realizados con la versión anterior a los cambios.
- La que contiene sufijo _1 es sólo una página.
- La que contiene sufijo _1_4 tiene 4 de amplitud y 1 de profundidad  
- La que contiene sufijo _4_4 contiene 4 de amplitud y profundidad.

En este estado, ya están consumidas las horas previstas para los cambios vistos inicialmente pero que si seguimos probando más diversidad de microsites, seguramente salgan más cosas.

Saludos!
