### ISSUE TITLE
Bug plantilla Tema 2015 visualització servei d'agendes

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#56]
Al visualitzar les agendes amb el front NOU, plantilla 2015, obtenim un error en la visualització del servei d'agendes segons l'idioma de navegació.

Adjunt URLs en producció :
http://www.caib.es/sites/iqpib/es/agenda/20160708 --> Dóna error 500
http://www.caib.es/sites/iqpib/ca/agenda/20160708 --> OK

**Comment by sgelabert-dgtic** [comment]
Endemés quan es visualitza la pantalla de detall es perd el menú lateral.
S'adjunta captura de pantalla.
![perdida_menu_catalan](https://cloud.githubusercontent.com/assets/17268396/16911713/638de0e6-4ce0-11e6-913f-517204da504a.gif)

**Comment by episano-dgtic** [comment]
Podéis indicar donde lo habéis probado. Yo he importado el tema nuevo y lo he aplicado en vuestro entorno en "Enlaces con tema 1.3" y continua fallandoy sin aparecer el menu:
http://caibter.indra.es/sites/M160621130647629/ca/agenda/20160622

Cambiar a castellano, y da el error 500

**Comment by slromero-indra** [comment]
Buenas, está revisado y funciona ahora. El estilo que tenía aplicado tenía que tener el tema último actualizado. Cuando se prueba ahora con el enlace anterior, en catalán se ve el menu y en castellano funciona sin error. 

En otros entornos, se tiene que volver a actualizar todos los temas almacenados que utilicen el tema2015.zip.

**Comment by episano-dgtic** [comment]
El tema que actualicé fue el que estaba ubicado en "gusite/moduls/front/etc/temas/" de la rama gusite 1.2
Qué se actualizó ayer, hoy no está actualizado. Conviene que lo actualicéis. Avisamé y lo compruebo en nuestro sistema

**Comment by slromero-indra** [comment]
Buenas, hemos vuelto a descargarnos el proyecto en otro ordenador, desplegando el tema y nos funciona correctamente. Por favor, podéis probar en proves el zip de tema2015.zip en el tema que tenga "Enlaces con tema 1.3" , creo que el tema se llama IndraJulio2016. Saludos!

**Comment by episano-dgtic** [comment]
Pues en proves, supuestamente con la última versión no funciona. 
https://proves.caib.es/sites/M157/es/

**Comment by slromero-indra** [comment]
Buenas, hemos comparado el tema de indra en proves.caib.es con el que hemos subido y vemos que no es el mismo.

El problema que vemos es que hay un trozo de código que no corresponde (también hay otro html además de este cambio), en lo comiteado en github tenemos la siguiente linea:

 _<div th:if="(${MVS_contenido}==null) and (${MVS_menu_cont_notic}==null) and (${MVS_idContenido}==null **or ${MVS_idContenido}==''**)" th:with="idcontenido='-1'" th:type="java.lang.Object" th:remove="tag">_

mientras que en lo de sistraproves está la versión antigua:

 _<div th:if="(${MVS_contenido}==null) and (${MVS_menu_cont_notic}==null) and (${MVS_idContenido}==null)" th:with="idcontenido='-1'" th:type="java.lang.Object" th:remove="tag">_

¿me puedes confirmar si está bajado del zip de la rama 1.2? 
https://github.com/GovernIB/gusite/blob/gusite-1.2/moduls/front/etc/temas/zip/tema2015.zip

**Comment by episano-dgtic** [comment]
En pruebas funciona, en producción únicamente cambiando el tema no. 
Entiendo que además de cambiar el tema hay cambios del front de 1.2, así que os confirmo va en producción cuando desplegemos la última versión
