### ISSUE TITLE
Error duplicació elements de llistat amb imatges

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#57]
Es detecta un error quan s'intenta duplicar elements de llistat tipus fitxa i galeria que tinguin una imatge adjunta.
Us remet log del servidor d'aplicacions.
[log_gusite_duplicar_elemento_listado_imagen.txt](https://github.com/GovernIB/gusite/files/375680/log_gusite_duplicar_elemento_listado_imagen.txt)

**Comment by episano-dgtic** [comment]
En pruebas hemos pasado del error:
Error en la capa de dades : java.rmi.ServerException: EJBException:; nested exception is: "javax.ejb.EJBException: javax.ejb.EJBException: es.caib.gusite.micropersistence.delegate.DelegateException: javax.transaction.TransactionRolledbackException: null; nested exception is: es.caib.gusite.micropersistence.exception.FicheroVacioException"
Al error: 
"Error en la capa de dades : java.rmi.ServerException: EJBException:; nested exception is: javax.ejb.EJBException: org.hibernate.HibernateException: [clonar4Hibernate] /app/caib/gusite/arxius/0/162936/920.pdf (No existe el fichero o el directorio)"

En vuestro entorno tenéis los ficheros en base de datos o en el sistema de ficheros?

**Comment by slromero-indra** [comment]
Este error se debe a que el jboss de caibter y el que usamos nosotros en local tienen directorios diferentes donde se encuentran las imágenes. He probado desde caibter en el microsite indra a crear un nuevo elemento con imagen dentro de la galeria("Malvarrosa") y lo he duplicado.
