### ISSUE TITLE
Error de sessió al gravar llistats

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#58]
Després d'algun temps sense operar amb el sistema, s'obtenen problemes quan s'intenta gravar un nou element d'un llistat. La resta de serveis del backoffice segueix anant bé.
Adjunt log del servidor d'aplicacions.
[log_gusite_sesion.txt](https://github.com/GovernIB/gusite/files/375749/log_gusite_sesion.txt)

**Comment by rsanz-indra** [comment]
Buenas, tras realizar diversas pruebas, no fuimos capaces de replicar el error por sesión. En todas las pruebas, cuando se pierde la sesión, la aplicación se vuelve muy inestable y no permite realizar ninguna acción hasta que no se vuelve al listado de microsites.

Se ha buscado la manera de replicar el error y sólo se ha encontrado la siguiente casuística:
- Acceder a editar una noticia de un listado. 
- Salir sin guardar la noticia (pulsando el botón de volver, apareciendo en la lista de noticias del listado ).
- Generar una nueva noticia.
- Al rellenar la información y guardar se replica el mismo error.

Se ha solucionado para esta casuística.
