### ISSUE TITLE
Millora accessibilitat: Actualització versió 4 TinyMCE

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#59]
Es sol·licita l'actualització a la versió 4 de tots els editors TinyMCE simples i avançats incorporats a l'aplicació (edició de pàgines, llistats, agendes, faqs i mailing).
L'actualització inclourà l'adaptació de botons personalitzats ja inclosos dins l'aplicació (insereix arxiu, icones arxiu i insereix component) i les correccions necessàries perquè el codi generat per aquests botons sigui conforme als criteris WCAG 2.0
Endemés es limitarà l'accés al botó d'edició directa de codi HTML segons el perfil de l'usuari gestor.

**Comment by sgelabert-dgtic** [comment]
Cal actualitzar els scripts de BBDD per la versió GUSITE 1.3 
- El fitxer /GUSITE-1.3-GIT/scripts/bbdd/1.3/gusite_create_data_from 1.2.1 to 1.3.0.sql no es de creació de dades sinó que es d'estructura update_schema_from_1.2.1_to_1.3.0.sql
- Falta incorporar el camp MSU_PERMIS a la taula d'usuaris, perquè estam tenint errades d'execució:

```
2016-11-23 13:15:45,623 WARN  [org.hibernate.util.JDBCExceptionReporter] (http-10.215.9.158-28080-3) SQL Error: 904, SQLState: 42000
2016-11-23 13:15:45,623 ERROR [org.hibernate.util.JDBCExceptionReporter] (http-10.215.9.158-28080-3) ORA-00904: "THIS_"."MSU_PERMIS": identificador no vÃ¡lido
```

**Comment by slromero-indra** [comment]
Buenas, ya se han realizado los cambios:

 - Actualizado el nombre de fichero de data a schema. 
 - Incluido el campo de permisos de edición en tiny:

_ALTER table "GUS_MUSUAR" ADD (
	"MSU_PERMIS" Number(19,0)
); 
Comment on column "GUS_MUSUAR"."MSU_PERMIS" is 'Permisos para Tiny';

Por favor, cuando podáis, ejecutar el anterior script para continuar con las pruebas. Saludos!

**Comment by sgelabert-dgtic** [comment]
Configurar Editor TyniMCE v4 perquè per usuari bàsic (sense editor avançat) es bloquegi la introducció d'etiquestes <br> (mitjançant directiva invalid_elements: 'br') i que el copy&paste es faci sense format (paste_as_text: false).
Per al cas de les imatges sense alt, investigar si es possible assignar a l'atribut "alt" una descripció gènerica "desc_"+ [nomarxiu] en cas que les imatges no tinguin descripció.

**Comment by episano-dgtic** [comment]
En el testeo, he detectado un par de ptos a corregir. 
1) Respecto al editor avanzado: 
    - Al tratar de incluir un enlace a contenidos internos al pulsar en el icono no surge popup con recursos microsite.
    - Hay dos botones insertar archivo. Y en ambos únicamente permite acceder a los ficheros comunes del microsite, no a los específicos incluidos asociados a la página en cuestión.   
    - La programación inserción/edición video qué tenía en cuenta el tipo de fuente del video (quicktime, flash, se ha perdido. 
    - No aparece la paleta de colores, en los campos esperan el valor numérico del color, asociada a las propiedades de las tablas, filas y celdas.

2) Respecto al editor simplificado:
    Al tratar de incluir un enlace a contenidos internos no aparece el icono para acceder al popup con los recursos microsite

3) Cuando se elimina un componente previamente incluido en alguna página. Al visualizar dicha página, se muestra vacía, pese a que tuviera más contenidos.

4) El bloque ayuda, se debería actualizar al nuevo manual, y indicar los nuevos css.
5) Si el microsite está configurado con el nuevo frontal (sites) en la página de inicio del backoffice el bloque de estadísticas debería remitir al analytics. 
6) La versión con solar/accesibilidad es 1.3 y no la 1.2 
7) Con el rol supervisor, aparece en configuración general "plantilles del microsites" y te permite incluir y modificar, pero no eliminarlas. 
`Error de seguretat : Denied: caller with subject=Asunto: Principal: $apltest FullName:Usuari emprat pel Servei d aplicacions per testejar NIF:null Principal: CallerPrincipal(members:$apltest FullName:Usuari emprat pel Servei d aplicacions per testejar NIF:null) Principal: Roles(members:RSC_SUPER,GUS_SUPER@weblogic-pre,GUS_SUPER,RSC_SUPER@weblogic-pre,tothom) and security context post-mapping roles=Roles(RSC_SUPER,GUS_SUPER@weblogic-pre,GUS_SUPER,RSC_SUPER@weblogic-pre,tothom,): ejbMethod=public abstract void es.caib.gusite.micropersistence.intf.PersonalizacionPlantillaFacade.borrarPersonalizacionPlantillas(java.util.List) throws java.rmi.RemoteException `

Ptos a analizar o ver posibles mejoras:
* Anteriormente se podía testear la accesibilidad de todos el microsite, ahora únicamente pulsando en el test campo por campo de tipo "html". Por otro lado en la lista de microsites indica si cumple o no accesibilidad según en anterior text. 
* Como se pueden incluir más opciones de "plantillas" en el editor avanzado.

**Comment by sgelabert-dgtic** [comment]
Pareix que aquest configuració sol·licitada no està operativa:

Configurar Editor TyniMCE v4 perquè per usuari bàsic (sense editor avançat) es bloquegi la introducció d'etiquestes 
(mitjançant directiva invalid_elements: 'br') i que el copy&paste es faci sense format (paste_as_text: false).

**Comment by episano-dgtic** [comment]
Probando la última versión me ha dejado salvador, faltan un par de cosas:
 
Respecto al editor avanzado:             
        La programación inserción/edición video qué tenía en cuenta el tipo de player del video (flash, quicktime, windowsmedia, real media) se ha perdido, poniendo fuentes alternativas descarga players.
        Ex: código genera el antiguo=> http://www.caib.es/sites/eines/ca/video/
         En vuestro editor => https://appsproves.caib.es/sites/M157/ca/video/
       
    Respecto al editor simplificado:
        Al tratar de incluir un enlace a contenidos internos no aparece el icono para acceder al popup con los recursos microsite


    Cuando se elimina un componente previamente incluido en alguna página. Al visualizar dicha página, se muestra vacía, pese a que tuviera más contenidos.

    Si el microsite está configurado con el nuevo frontal (sites) en la página de inicio del backoffice el bloque de estadísticas debería remitir al analytics.
   
    El bloque ayuda, se debería actualizar al nuevo manual, y indicar los nuevos css.

Ya diréis cosas de los ptos a analizar.

**Comment by slromero-indra** [comment]
Buenas, respecto al editor de video, en las nuevas versiones de tinymce, el tipo de player ha desaparecido (supongo que es por la adaptación a html 5), seguiremos buscando si hay posibilidad de agregarlo.

Sobre el bloque de ayuda, por favor, se debería generar una nueva issue ya que no es una cosa que podamos realizar en pocos minutos y no tiene mucho que ver con esta issue.

En cuanto a google analytics, ya hemos comiteado el cambio para que aparezca el enlace a google analytics en vez de los dos enlaces de vore les estadístiques.

Respecto al problema de eliminar un componente, estamos intentando replicarlo porque no somos capaces de reproducir el error.

**Comment by episano-dgtic** [comment]
1) Os he replicar el problema del componente en vuestro entorno. Concretamente en la página:
http://caibter.indra.es/sites/M161103080140629/ca/pagina_con_un_componente_se_elimina/
Para ello, se crea un listado, y el componente asociado. Se crea una página y se añade el componente con texto adicional. Y posteriormente se elimina el componente. 
Veréis que muestra la página vacia, entiendo porque se da un error al tratar de ver el componente eliminado. 
2) Crearemos una nueva incidencias para el bloque de ayuda.
3) OK al tema del video

4) No habéis indicado nada respecto: 
Ptos a analizar o ver posibles mejoras:
    Anteriormente se podía testear la accesibilidad de todo el microsite, ahora únicamente pulsando en el test campo por campo comprueba el "html". Por otro lado en la lista de microsites indica si cumple o no accesibilidad según en anterior text.
    Como se pueden incluir más opciones de "plantillas" en el editor avanzado.

**Comment by slromero-indra** [comment]
Buenas, sobre la incidencia del componente, en un primer análisis parece que se produce porque el controlador encargado de obtener produce un error que provoca la página vacío. Igualmente, el problema tiene poco que ver con esta incidencia que está asociada a la actualización del tinymce y se debería crear una nueva issue donde incluir los cambios.

Respecto a la inclusión de plantillas, las plantilla se añaden ahora mismo de manera estática, por ejemplo, la plantilla "Taula corporativa" está definida en "tinymce/templates/tabla.htm". Si se quieren añadir más plantillas, se puede hacer de varias maneras:

- Nos pasáis el html que deseáis añadir (podéis utilizar el htm de Taula corporativa como base) y lo añadimos y nos especificáis en los formularios donde deseáis que lo añadimos (si es unos formularios en concretos o en todas las páginas que tengan el tinymce).

-  Los añadimos de manera dinámica con un nuevo formulario donde poder añadir un html o ver la posibilidad de generarlos dinámicamente con el tinymce. Habría que ver cómo enfocar la mejora y generar el respectivo documento de estimación.


Mientras que el problema de testear toda la accesibilidad, como ya se comentó con Salvador, debería de implementarse una nueva mejora que debería enviar hacia todos los contenidos y enviarlos al servicio http://achecker.ca como realiza el tinymce. Si os parece oportuno, podríamos realizar un documento de estimación.

**Comment by episano-dgtic** [comment]
okey con lo de los componentes.. te lo indico en la incidencia #65 , que tiene que ver con como trata el frontal de sites los componentes.

**Comment by sgelabert-dgtic** [comment]
Afegeix-ho incidències detectades per n'Estela en quant a l'editor:
1. En el editor aparece duplicado el botón de Elimina el formato Tx
2. No tiene repercusión en el frontal/backoffice de gusite los cambios de algunas propiedades de la tabla, pese a que si indique las características en el código html. Concretamente:
     - Espacio entre celdas (cellspacing) , sin repercusión frontal 
     - Margen interno (cellpadding), sin repercusión visual en backoffice y frontoffice
1. El botón de insertar/editar imagen del anterior tiny permitía más opciones. Cambiar la justificación del texto(vertical,medio o bajo) justificación de la imagen( izquierda, derecha,  float izquierda, float derecha etc... )
1. Antes había un botones más (ancla) , y en el editor enalce te permitía elegir la ancla. 
1. La opción de Formats, en el anterior editor aparecían las distintas opciones del css. Ahora deberían aparecer la combinación tema y css, ó sólo css en caso usen antiguo backoffice. 

Endemés copio aquí comentari anterior que s'ha passat per alt:

6. Configurar Editor TyniMCE v4 perquè per usuari bàsic (sense editor avançat) es bloquegi la introducció d'etiquestes (mitjançant directiva invalid_elements: 'br') i que el copy&paste es faci sense format (paste_as_text: false).
7. Per al cas de les imatges sense alt, investigar si es possible assignar a l'atribut "alt" una descripció gènerica "desc_"+ [nomarxiu] en cas que les imatges no tinguin descripció.

**Comment by slromero-indra** [comment]
Contestación sobre los puntos:
1- comitado
2- Esto es debido a un estilo incluido en el fichero de estilos encargado de eliminar los margin y padding de todos los elementos para facilitar la maquetación haciendo uso de CSS. Para modificar estos valores es recomendable hacer uso de estilos CSS ya que en las nuevas versiones de html estos atributos ya no son soportados. Si quereis podemos eliminar este estilo para que no afecte a las tablas y permita el uso de estos atributos. ¿quereís que lo eliminemos? 
3-En este caso el tiny ha dejado de soportar estos atributos(https://www.tinymce.com/docs/plugins/image/#qwherearetheadvancedimageoptions) e insta a hacer uso de CSS.  hemos incorporado la pestaña de herramientas avanzadas de imágen que permite modificar los estilos.
4-comitado
5- Existía un problema al cargar multiples ficheros css en el tiny y este cambio ya está comitado. Los estilos que se cargan son:
       -- tiny_estils.css 
       -- si el microsite dispone de css propio --> además se carga el archivo de css del microsite
       --sino  si el patron es diferente de negro --> además se carga el estilo-patron correspondiente ( azul, rojo, verde, etc..)
6- Esta petición está contemplada ya en el código. Actualmente a nivel de usuario se indica si puede modificar el editor o no, y esto se puede configurar para cualquier tipo de usuario, ¿quereis que modifiquemos el comportamiento? por otro lado hemos visto que está configurado para setear el parametro "paste_as_text" a false cuando debería estar a true para que tenga el comportamiento deseado (pegar sin formato). ya hemos comitado el cambio.
7- Hemos investigado este tema y es posible insertar un valor en el campo alt al seleccionar una imágen desde resources (al seleccionar la imágen desde el pop-up).  hemos comitado estos cambios.

**Comment by slromero-indra** [comment]
Buenas, podéis verificarnos el punto 2?

**Comment by sgelabert-dgtic** [comment]
A quin CSS et refereixes tiny_estils.css, no ? Preveis algun efecte colateral amb l'eliminació?

**Comment by slromero-indra** [comment]
Afecta a varios ficheros, aparte del que indicas, también a estils.css y bootstrap.min.css como mínimo. Habria que verificar si afecta a alguno mas. 

Al estar definido en librerias externas, puede traer efectos no deseados en el comportamiento de bootstrap, y habria que revisar los diferentes diseños / temas  para asegurarnos de a que afecta, ya que son definiciones sobre elementos generales (table, td, th ...)

Lo más recomendable, en lugar de eliminar estos estilos, es no hacer uso de esas propiedades de tabla, y para modificar el aspecto, asignar estilos a las tablas a través de css asignando una determinada clase.
