### ISSUE TITLE
Millora accessibilitat: Actualització mòdul anàlisi d'accessibilitat

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#60]
Es sol·licita actualitzar/canviar el mòdul de validació d'accessibilitat TAW incorporat a l'aplicació perquè validi segons les especificacions WCAG 2.0 del W3C.
La tasca inclourà un anàlisi de les alternatives i la implantació de la solució seleccionada.

**Comment by slromero-indra** [comment]
Está incluido en la tarea 59, es el plugin achecker agregado al tinymce 4.

**Comment by sgelabert-dgtic** [comment]
Deix el tiquet obert, perquè caldrà netejar el codi relacionat amb el validador TAW antic
