### ISSUE TITLE
Millora accessibilitat: Correcció de contingut no accessible

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#61]
Es sol·licita implantar un sistema de correcció automàtica del codi a nivell de microsite que permeti millorar l'accessibilitat dels sites segons els criteris WCAG 2.0.
Les mesures de correcció automàtica que es preveu implantar són:
- Alternatives textuals. Imatges sense alt o amb un text no vàlid
- Agrupació estructural. Us incorrecte d'etiquetes HTML
- Carència de `caption` en etiquetes tipus table o iframe
- Estructuració adequada de la pàgina. Anidament correcte i ordenat  d'encapçalaments.
- Eliminar etiquetes buides.

**Comment by sgelabert-dgtic** [comment]
Adjunt informe d'accessibilitat d'un microsite problemàtic.
[www.caib.es_201703030923.pdf](https://github.com/GovernIB/gusite/files/816622/www.caib.es_201703030923.pdf)

En l'informe s'observen:
 - Alternatives textuals. Imatges amb un text no vàlid. Per això, us proposam que es modifiqui el popup d'afegir arxiu perquè sol·liciti una descripció obligatòria de l'arxiu. 
 - Agrupació estructural. Us incorrecte d'etiquetes HTML
 - El peu de pàgina on apareix la informació de contacte hauria d'estar agrupat dins una etiqueta textual `<p></p>`

**Comment by sgelabert-dgtic** [comment]
URL pel Servei de Diagnòstic : http://administracionelectronica.gob.es/comunidades/verPestanaMas.htm?idComunidad=21#.W1ru79UzZpg

**Comment by episano-dgtic** [comment]
Hemos detectado que hay páginas generadas dinámicamente 'no válidas" en el test de accesibilidad del Observatorio del ministerio de hacienda (adjunto el pdf con la evaluación generado).
[lista_de_paginas_201808211124.pdf](https://github.com/GovernIB/gusite/files/2374347/lista_de_paginas_201808211124.pdf)

 Concretamente se trata de:
1) Listados de galería de fotos  (página 20) http://www.caib.es/sites/eines/ca/l/fotos/?mcont=103127
2) Encuestas   (página 21) http://www.caib.es/sites/eines/ca/encuesta/preguntes_sobre_la_web_del_govern_intranet_web_de_administracions_digitals_y_sede_electronica-1374/?mcont=103125
3) Formularios de contacto (página 14) http://www.caib.es/sites/eines/ca/fcontacto/complet_formacio_per_rolsac_dimarts_21_de_febrer_/?mcont=7704

Por otro lado si se crean apartados en el menu, que van directamente a un documento adjunto, se consideran válidas pero dan una nota muy baja 5,7 www.caib.es/sites/eines/f/45506 (página 8 y 9)

En los parámetros analizados donde globalmente no puntuamos o muy bajos aunque no invalida las páginas son:
		 1) el factor 1.14 "Compatibilidad" con 2,20 de media, principalmente debido a la calidad CSS
		 2) el factor 2.3 Sección de accesibilidad con una media de 0. "La Declaración de Accesibilidad del portal no especifica la fecha de la última revisión de la accesibilidad del sitio"

Habría que corregir lo necesario en el código generado para evitar todos estos casos

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado varias actualizaciones y deberían dejar de aparecer estos indicadores. hay 2 temas a puntualizar:
- En el caso de los enlaces directos desde el menú, no tenemos claro porque aparecen en el informe, parece que los trata como si fuesen un html, cuando son ficheros. no tenemos claro que acciones tomar.
- Referente a la sección 2.3, actualmente la página dispone de un enlace a la página de accesibilidad (se encuentra dentro del menú lateral), por lo que no debería estar dando problemas, en los casos en los que falla parece tratarse de enlaces a ficheros, los cuales no tienen este enlace.

hemos intentado pasar el test, pero al parecer no tenemos acceso por lo que no podemos validarlo. ¿podéis verificar si los cambios surten efecto?

**Comment by dmadronal-indra** [comment]
Buenas hemos añadido una mejora sobre el tema2017.
