### ISSUE TITLE
Detalles Front

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#62]
En el pie del nuevo tema, aparece Govern de les IllesBalears, falta indicar un espacio.
Si en los eventos de la agenda de un día, hay más de uno, aparece dos veces la clasificación de la actividad. 
![chorraditas](https://cloud.githubusercontent.com/assets/17451683/17473217/917dd252-5d4f-11e6-9b71-373dac3335c7.gif)

**Comment by episano-dgtic** [comment]
Otro detalle de funcionamiento.. 
Si elegis un evento de septiembre o octubre, y luego pulsais la flecha de volver atrás del navegador.. en el calendario indica el mes del evento que elegisteis, pero el mes del calendario es el de agosto. 
http://www.caib.es/sites/iqpib/es/agenda/
![error_indicaoctubre pero apareceagosto](https://cloud.githubusercontent.com/assets/17451683/17473369/6d619e02-5d50-11e6-816e-9fb549fd6706.gif)

**Comment by episano-dgtic** [comment]
Otro detalle de diseño. Las imagenes con otros navegadores (chrome, por ejemplo) se ven más pequeñas
http://www.caib.es/sites/M1608180939491843200308/89101/
[mic_20160818_9352_microsite.zip](https://github.com/GovernIB/gusite/files/424364/mic_20160818_9352_microsite.zip)

![mic_chrome](https://cloud.githubusercontent.com/assets/17451683/17765864/95559640-6528-11e6-81ce-adc578e76567.gif)
![mic_firefox](https://cloud.githubusercontent.com/assets/17451683/17765862/9541e1ae-6528-11e6-8368-ad10712cd11f.gif)

**Comment by episano-dgtic** [comment]
Se ha colado un inma. En la cabecera de los formularios de contactos. 
![inma_en form_contacte](https://cloud.githubusercontent.com/assets/17451683/18195269/bbfe3a54-70ea-11e6-9207-59f57b1de5b8.gif)

**Comment by episano-dgtic** [comment]
En castellano los componentes de los listados muestra la información en catalán. Aunque al pulsar accedemos en castellano.
http://www.caib.es/sites/igualtat/es/inici/
![componente_encastellano](https://cloud.githubusercontent.com/assets/17451683/18196134/f168420c-70ef-11e6-993d-68c63b4d9094.gif)

**Comment by slromero-indra** [comment]
Buenas, estamos trabajando en la incidencia. Podría ser recomendable ir creando cada vez una incidencia nueva para los nuevos requerimientos, ya que si no se alargará esta incidencia y se incrementará en horas.

**Comment by slromero-indra** [comment]
Están todos los cambios realizados menos el referente al calendario. Se ha visto que el problema sólo se ha observado en Chrome por un funcionamiento propio del navegador (lo hemos repetido en firefox y el funcionamiento parece el correcto). Se ha excedido las horas mínimas y resolver el problema en chrome podría implicar un coste mayor de tiempo.

**Comment by slromero-indra** [comment]
Analizando hemos observado que la diferencia es que firefox, al pulsar el botón de volver cachea todos los datos anteriores (de ahí a que mantenga los datos) mientras que chrome vuelve a acceder y calcular los datos.

Hemos probado lo siguiente sin resultados satisfactorios:
- Actualizamos el mvc-servlet para que no cachee.
- Aprovechamos para forzar mediante código una actualización en texto utilizando el onready y onload pero en ambos casos no funcionaba (excepto si se introducía un retraso antes de actualizar el texto)
- Analizamos la posibilidad de generar el calendario de manera distinta pero se nos iba de horas.

Si se revisa el código cuando está erróneo, se observa que el select está correcto (marca septiembre como selected) pero muestra octubre.

`<select onchange="mostrarCalendari();" name="agendaSelect" id="agendaSelect" style="font-weight: bold;">`
`<option value="1">Ago 2016</option>`
 `<option selected="selected" value="2">Sep 2016</option>`
  `<option value="3">Oct 2016</option>`
  `<option value="4">Nov 2016</option>`
`</select>`

**Comment by episano-dgtic** [comment]
He comprobado que se ha arreglado:
 1) Inma de los formularios de contacto. 
2) Aparezca varias veces el tema de un evento en la agenda
3) calendario de la agenda muestre correctamente

Falta
a) Govern de les IllesBalears en el pie del tema personalizado 2015
b) los componentes de los listados tipo ficha no se muestran en castellano. Aunque al pulsar accedemos en castellano.

Si precisáis desglosar en múltiples incidencias hacedlo. Yo pensaba que eran temas muy pequeños y no implicaban muchas horas. Y como todas hacían referencia a temas de diseño, me parecía bien agrupar.

**Comment by slromero-indra** [comment]
Habría que actualizar el tema personalizado del site, se ha actualizado "nuevo" en caibter.

**Comment by episano-dgtic** [comment]
Sigue sin funcionar: 
 los componentes de los listados tipo ficha no se muestran en castellano. Aunque al pulsar accedemos en castellano.
Si no puedes reproducirme dime cosas

**Comment by slromero-indra** [comment]
Buenas, estamos intentando replicar el problema y no somos capaces. Hemos probado lo siguiente:
- Creado una lista de tipo fitxa (con ambos idiomas).
- Generado dos elementos noticias para la fitxa (con ambos idiomas)
  - Asociado a un elemento menu

Lo hemos probado en nuestro entorno y en local con ambas ramas.
URL español --> http://caibter.indra.es/sites/uri_aleman/es/l/lista_fitxa_62/
URL catalán -->  http://caibter.indra.es/sites/uri_aleman/ca/l/lista_fitxa_62/
                       o  http://caibter.indra.es/sites/uri_aleman/llista_de_elements_fitxa/

Seguramente el error sea otro y no lo estemos replicando. Por favor, nos puedes ayudar a replicar el problema. Saludos!

**Comment by episano-dgtic** [comment]
El problema ocurre con los COMPONENTES que se incluyen en las páginas. 
http://caibter.indra.es/sites/uri_aleman/es/componente_lista_ficha/

Qué muestra los datos en catalán pese a que esté traducido en castellano. Si bien es cierto que si vas al animal en cuestión ya si se ve en castellano. 

Se reproduce:
Creas un listado de tipo ficha e introduces todo en catalan y castellano. Creas el componente asociado a dicho listado y lo incluyes en una página. 
Mira como se muestra el componente en castellano.

**Comment by episano-dgtic** [comment]
El problema de cambio de tamaño para el chrome sigue sin estar resuelto. Y nos impide cambiar todos los microsites al nuevo frontal. 

Podéis reproducirlo incluyendo en cualquier página el siguiente código html. 

```
<h1>Logotips de: Presid&egrave;ncia Illes Balears - Presid&egrave;ncia Illes Balears<br /></h1>
<p>
<table border="0" cellpadding="10" cellspacing="10" width="95\%">
<tbody>
<tr>
<td style="text-align: center;">
<p><img alt="PRES_IB-05.png" src="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212190&amp;id=212190" width="210" /></p>
</td>
<td style="text-align: center;">
<p style="text-align: center;"><img alt="PRES_IB-06.png" src="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212191&amp;id=212191" width="210" /></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center;"><a href="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212194&amp;id=212194">Acrobat</a> <a href="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212190&amp;id=212190">png</a> svg</p>
</td>
<td>
<p style="text-align: center;"><a href="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212194&amp;id=212194">Acrobat</a> <a href="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212191&amp;id=212191">png</a> svg</p>
</td>
</tr>
<tr>
<td style="background-color: #3d3d3f;">
<p style="text-align: center;"><img alt="PRES_IB-07.png" src="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212192&amp;id=212192" width="210" /></p>
</td>
<td style="text-align: center; background-color: #3d3d3f;">
<p style="text-align: center;"><img alt="PRES_IB-08.png" src="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212193&amp;id=212193" width="210" /></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center;"><a href="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212194&amp;id=212194">Acrobat</a> <a href="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212192&amp;id=212192">png</a> svg</p>
</td>
<td>
<p style="text-align: center;"><a href="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212194&amp;id=212194">Acrobat</a> <a href="http://www.caib.es/sites/mic/presidencia_illes_balears/archivopub.do?ctrl=MCRST7945ZI212193&amp;id=212193">png</a> svg</p>
</td>
</tr>
</tbody>
</table>
</p>
```

En pruebas, la url: https://proves.caib.es/sites/M157/imagen_chrome/

**Comment by episano-dgtic** [comment]
Otra que no funciona 2) Aparezca varias veces el tema de un evento en la agenda. El problema se replica si el segundo evento del día pertenece a otro tipo de actividad. 
http://www.caib.es/sites/eines/ca/agenda/20161028

**Comment by slromero-indra** [comment]
Es importante tener en cuenta que a pesar de los cambios comiteados, el código copiado tiene un pequeño problema. El width está incorrectamente introducido por lo que, dependiendo del navegador, interpreta la información de manera distinta (para chrome son 95px mientras que en firefox son 95%). Se debe editar y quitar la barra del código:

![image](https://cloud.githubusercontent.com/assets/17451407/19806730/f57f7d5c-9d1c-11e6-9b51-a9ddbe65fe20.png)

**Comment by episano-dgtic** [comment]
La incidencia de "inma" en los formularios de contacto se solventa para el tema "nuevo", pero para el tema por defecto sigue apareciendo. 
http://www.caib.es/sites/eines/contacte/199/?mcont=7704

**Comment by episano-dgtic** [comment]
El problema del calendario(página agenda y en componente agenda), referente a la indicación del mes sigue ocurriendo, y no ocurré únicamente en chrome sino en mozilla y explorer . Ahora se ve más claro. 
Si accedéis a http://iqpib.caib.es se muestra el componente con el mes de febrero pero la etiqueta muestra es la de diciembre del 2016.
Tb. ocurre en la página de la agenda
http://www.caib.es/sites/iqpib/ca/agenda/?mcont=87623

**Comment by slromero-indra** [comment]
Para probarlo es necesario actualizar el tema2015 en la instancia de gusite:
https://github.com/GovernIB/gusite/blob/gusite-1.3/moduls/front/etc/temas/zip/tema2015.zip

**Comment by episano-dgtic** [comment]
Lo siento.. pero hay un caso en el que no se refresca bien la cabecera del calendario. 

Si tengo eventos en febrero y marzo, eligo un evento de marzo y pulso atrás del navegador.. me muestra el calendario de febrero pero con la cabecera de marzo. 
Si pulsas "atrás" del evento sin problemas, aunte te mande al calendario de febrero, al menos indica que es el mes de febrero.

**Comment by slromero-indra** [comment]
Para probarlo es necesario actualizar el tema2015 en la instancia de gusite:
https://github.com/GovernIB/gusite/blob/gusite-1.3/moduls/front/etc/temas/zip/tema2015.zip

**Comment by episano-dgtic** [comment]
Otro pto que se ha detectado con en nuevo front coorporativo o con el tema personalizado de sites, es que si el microsite se configura con una cabecera/pie personalizada hace caso omiso y no se muestran.  
(Configuración->Cabecera/pie->personalizada)

![cabecera_sites_basico](https://cloud.githubusercontent.com/assets/17451683/23899302/e6dd0dce-08b4-11e7-8be7-de247b27e942.gif)
![cabecera_sites](https://cloud.githubusercontent.com/assets/17451683/23899303/e6df9ba2-08b4-11e7-850b-e0f6be66b2d5.gif)

**Comment by episano-dgtic** [comment]
Otro pto. La página de los listados y componentes, sólo tienen en cuenta la fecha de caducidad de los elementos, no la hora concreta.  De modo que si una noticia caduca el 16/03/2017 a las 9:00 sigue apareciendo hasta el cambio de día 17/03/2017.

**Comment by sgelabert-dgtic** [comment]
Revisau el detealls que falten i comprovau que estigui consolidat tot sobre el branch 1.3?
Gràcies

**Comment by slromero-indra** [comment]
Buenas, 
El tema de la cabecera y pie, a priori parece que afecta solo al tema2015 (en local parece funcionar para el front por defecto), aunque miraremos de realizar más validaciones en el resto de entornos para asegurarnos.
Revisaremos el caso de la cabecera y pie para el tema2015, y el tema de las fechas en los listados y los componentes, en cuanto lo tengamos implementado lo consolidamos sobre la rama 1.3

**Comment by slromero-indra** [comment]
Buenas ya están los cambios consolidados sobre la rama 1.3, además se ha sincronizado la rama 1.4 para que incluya todas estas correcciones.

para verificar el tema de la cabecera y pie es necesario importar el [tema2015 ](https://github.com/GovernIB/gusite/raw/gusite-1.3/moduls/front/etc/temas/zip/tema2015.zip)de la rama 1.3

**Comment by sgelabert-dgtic** [comment]
He importat el  [tema2015](https://github.com/GovernIB/gusite/raw/gusite-1.3/moduls/front/etc/temas/zip/tema2015.zip)  sobre l'entorn de PREproducció i persisteixen els errors de n'Estela pel que fa a la capçalera i peu personalitzats (no els té en compte). A més pareix que l'aplicació del nou tema sobre els microsites no va bé. Podeu provar-ho voltros mateixos a https://appsproves.caib.es/sites/eines/ca/presentacio-17101/?campa=yes

He intentat importar el microsite "Eines de gestió de les nostres webs" amb el que testeig sobre caibter però em dóna "La petició rebuda no és correcta.". L'adjunt per si voleu intentar replicar l'entorn de proves http://tn.caib.es/tME3uK98

**Comment by slromero-indra** [comment]
Buenas,
Después de verificar el desarrollo y ver que en nuestro entorno funcionaba correctamente, hemos analizado a fondo el microsite y detectando que tiene una personalización de la plantilla para la cabecera, la cual sobrescribe la actual plantilla, por eso no aparece correctamente.  Si se elimina / modifica esa personalización empieza a aparecer correctamente la cabecera.  ¿podéis verificarlo?

**Comment by sgelabert-dgtic** [comment]
Ho he provat sobre caibter amb el microsite "4a Jornada d'Administració Digital a la CAIB" i efectivament funciona correctament.

Tot i això el microsite "Eines de gestió de les nostres webs" no veig que tingui CSS particular i sobre l'entorn de PRE segueix sense presentar-m'ho bé. Ho podeu provar a https://appsproves.caib.es/sacmicroback/microEdita.do?accion=general&refresco=si&idsite=6045
Casos:
- Amb capçalera personalitzada, sense CSS i sense aplicar tema2015 [frontal-eines-NoTema2015.zip](https://github.com/GovernIB/gusite/files/1025062/frontal-eines-NoTema2015.zip)
- Amb capçalera personalitzada, sense CSS i aplicant tema2015 [frontal-eines-tema2015.zip](https://github.com/GovernIB/gusite/files/1025070/frontal-eines-tema2015.zip)

**Comment by slromero-indra** [comment]
Buenas, 
hemos intentado acceder a la configuracion del microsite, pero parece que no accedemos al mismo (el titulo es " Eines de gestió de les nostres Webs mod"). Hemos revisado los pantallazos que adjuntais, y creemos que falta revisar la configuración de "plantillas del microsite" que es donde se personalizan las plantillas, ¿podeis verificar si en esa configuración aparece alguna definicion de la cabecera?  
![imagen](https://cloud.githubusercontent.com/assets/17451407/26397819/d41a8842-4077-11e7-9413-5890e9049619.png)

**Comment by sgelabert-dgtic** [comment]
El microsite és "Eines de gestió de les nostres Webs" sense el mod
He eliminat la plantilla de "Plantilles del microsite" i ara apareixen les capçaleres i peus ! Pensava que les plantilles s'aplicaven des de Configuració General --> Aparença.
Si l'aplic però el tema2015 des d'Aparença, segueix sense veure's bé. Cal que l'apliqui també ha plantilles del microsite ?
![image](https://cloud.githubusercontent.com/assets/17268396/26398581/37462dac-407a-11e7-9393-94121e9f408a.png)
Hauré de dir a n'Estela que em faci un curs ...

**Comment by slromero-indra** [comment]
Finalmente hemos podido acceder a la configuración del microsite (faltaba asignarlo al usuario), hemos probado a importar nuevamente el tema (hemos creado uno nuevo) y lo hemos asignado al microsite, parece que ya se ve correctamente. Hemos tenido que importar el tema 2 veces, porque la primera nos ha pasado lo mismo (al asignarlo no se cargaban los estilos correctos), una vez asignado el tema al microsite y ver que no cargaba correctamente los estilos, hemos vuelto a importar el tema sobre el creado anteriormentey al acceder al frontal aparecía correctamente. Hemos probado en nuestro entorno y la importación de temas parece funcionar a la primera. 
   
![imagen](https://cloud.githubusercontent.com/assets/17451407/26402581/413ab9a2-408b-11e7-8639-35d1cc4357da.png)
