### ISSUE TITLE
Canviar logotip i favicon en els frontals del projecte

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#63]
Es sol·licita canviar el logotip de la capçalera i el favicon del projecte actual pels que li corresponguin segons les directrius del nou MIC.
Adjunt arxius a canviar.
![favicon](https://cloud.githubusercontent.com/assets/17268396/18541624/9b5e9370-7b26-11e6-8cb7-a1b686d403f4.png)
![governillesbalears](https://cloud.githubusercontent.com/assets/17268396/18541625/9b6068bc-7b26-11e6-8ce2-ba41c5c52f81.png)

**Comment by episano-dgtic** [comment]
He visto que lo habéis cambiado para version  2015, intranet, microsite publico segunda versión. Pero falta:
1) "microsite público, primera versión"
2) Versión 2015, con el tema personalizado (Cambiarlo en la cabecera y el pie)

En http://mic.caib.es/sacmicrofront/contenido.do?mkey=M160729102345629&lang=CA&cont=90260
Podéis descargar la versión del logo pensado para fondo oscuro/grises.

**Comment by slromero-indra** [comment]
Se actualiza la imagen para el "microsite público, primera versión".
Hay que actualizar el tema personalizado para poder visualizar el cambio en cabecera y pie.

**Comment by sgelabert-dgtic** [comment]
No sé amb quin criteri decidiu canviar el logos que venen definits en el MIC. El MIC no defineix logotips horitzontals i, obviament, noltros no som qui ni ens correspon la tasca de definir-los.
Crec que en el tiquet s'especifica clarament els logos que s'han de canviar. Si pel motiu que sigui teniu algun dubte per la resolució, per favor, consultau-nos-ho.

**Comment by slromero-indra** [comment]
Modificamos para usar los logos del MIC.
Tenemos las siguientes dudas:
- Para los backs (rolsacback y sacmicroback) habrá que hacer más grande la cabecera y meter el logo en un cuadrado con fondo blanco para que se distinga.
- Para los microsites con versión "microsite público, primera versión" con cabecera en azul habrá también que hacer más grande la cabecera y meter el logo en un cuadrado con fondo blanco para que se distinga.
- Para seucaib hay que ver si se tiene que arreglar que se sobrepongan las imágenes sobre la miga de pan (p.e. https://www.caib.es/seucaib/es/200/personas/tramites/tramite/2699229)

**Comment by episano-dgtic** [comment]
El logo de la intranet no es el corporativo.

**Comment by slromero-indra** [comment]
Buenas, estamos revisando, cuando te refieres al logo de la intranet, te refieres al del back? Hemos revisado y el logo sale arriba.

![image](https://cloud.githubusercontent.com/assets/17451407/19244516/e07f9bb6-8f1c-11e6-9539-5f433ae4dae5.png)

**Comment by episano-dgtic** [comment]
No, la intranet se refiere cuando en configuración general eliges "Microsite intranet"

**Comment by slromero-indra** [comment]
Buenas, gracias por la aclaración, ya está cambiado en ambas ramas. Saludos!

**Comment by episano-dgtic** [comment]
Os recuerdo que no debéis modificar el logo coorporativo. En la intranet se muestra una nueva versión, no oficial de dicho logo.

**Comment by slromero-indra** [comment]
Buenas, ya está actualizado las imágenes de la intranet con el logo corporartivo. Saludos!
