### ISSUE TITLE
Adaptar plantilla tema 2015 al nou MIC

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#64]
Es sol·licita crear un nou tema "tema2016" basat en "tema2015" i adaptar-lo al nou Manual d'Identitat Corporativa. Concretament es sol·liciten implementar únicament aquest canvis:
- Canviar capçalera i peu perquè segueixin les mateixes directrius de redisseny de la web corporativa (WEBCAIB).
- Canviar font de la lletra (bariol/dosis)
- Canviar logotips.

**Comment by episano-dgtic** [comment]
Comentaros por otro lado que, en el tema sites (no aparecen las opciones configuradas en el backoffice en el pie/cabecera)

**Comment by sgelabert-dgtic** [comment]
Podem reprendre de nou aquesta tasca en base al darrer disseny de la web corporativa acceptat per DGCOM
Tot i això, a banda de crear un tema nou que estengui de tema2015, convé canviar també la plantilla per defecte.

**Comment by slromero-indra** [comment]
Buenas,
hemos subido una versión inicial que no contiene cambios a nivel de código. ([tema2017](https://github.com/GovernIB/gusite/raw/d584a556f042fc3336ee5697667bc2ec6b84dd12/moduls/front/etc/temas/zip/tema2017.zip)).
- Esta versión se puede probar sin necesidad de actualizar la aplicación, aunque algunos literales no contienen traducción.
 - Iniciamos las mejoras para permitir indicar los enlaces a través de propiedades, y actualizaremos los literales necesarios.

**Comment by slromero-indra** [comment]
Buenas,
Se ha subido una nueva versión que incluye la traducción de los literales y la recuperación de los enlaces a través del fichero de properties.
Para probar esta nueva version del  [tema2017](https://github.com/GovernIB/gusite/raw/25f929dc15f4fa80795557b684fee52a1b692f95/moduls/front/etc/temas/zip/tema2017.zip) es necesario actualizar la aplicación, el tema y el fichero de properties.
Ya podeis proceder a validar el desarrollo.

**Comment by sgelabert-dgtic** [comment]
Quan en les propietats feis referència a "Propiedades tema2017 {0} sustituye el idioma" entenc que {0} és un placeholder que es substitueix per l'idioma de navegació ?

**Comment by slromero-indra** [comment]
Correcto, el "{0}" se sustituirá por los siguientes valores en función del idioma en que se cargue la página:
- Castellano: es
- Catalán : ca
- Inglés: en
- Francés: fr
- Alemán: de

Solo se debe indicar si es necesario.

**Comment by sgelabert-dgtic** [comment]
He importat el tema2017 que adjuntau en aquest tiquet sobre la versió (d584a55) de GUSITE i l'he aplicat sobre un microsite en concret i genera  errors javascript.
![image](https://user-images.githubusercontent.com/17268396/30542307-2bf80432-9c7f-11e7-80f5-ca23c8617cbb.png)
He importat el microsite i el tema sobre caibter perquè ho pogueu reproduir (http://caibter.indra.es/sites/xarxes/ca/pagina_inicial/?campa=yes)
Per favor, donau-li prioritat perquè ens ho reclamen des de la DGCOM

**Comment by slromero-indra** [comment]
Buenas,
Hemos incluido el fichero "files/jquery-1.12.4.min.js" al zip . Se ha actualizado la nueva version del [tema2017 ](https://github.com/GovernIB/gusite/raw/b0fd4bfd113a5dab3b7597238dfad9ba784b260b/moduls/front/etc/temas/zip/tema2017.zip
)(la que implica actualizar el código de gusite), pero la versión sin dependencias de código debe ser actualizada a mano. La adjuntamos aquí: [tema2017.zip](https://github.com/GovernIB/gusite/files/1311006/tema2017.zip).

Se ha probado a actualizar el "tema2017-mic-dgtic" y ha dejado de mostrar los errores.

**Comment by sgelabert-dgtic** [comment]
- Cal parametritzar les URLs a les xarxes socials FB,Twiter, Instagram i Youtube via propietats de sistema
- La informació que surt de la plantilla no és correcta. Adjunt captura de pantalla.
![infoplantilla2017](https://user-images.githubusercontent.com/17268396/30632002-c9455e52-9de6-11e7-828b-fe45158deaf8.jpg)

**Comment by sgelabert-dgtic** [comment]
- El següent microste de l'entorn de PREproducció presenta sempre el menús desplegats https://appsproves.caib.es/sites/directorimitjans/ca. Convendria revisar-ho perquè per defecte es presentin plegats.

**Comment by slromero-indra** [comment]
Buenas, revisamos la parametrización de las url de las redes sociales.
Referente a la información de la plantilla, os referís a la codificación de los caracteres (GUSITE 1.2: Versió 2015)?  si es así este valor se extrae directamente de la BBDD, podeis revisar el valor de la tabla GUS_FR_TEMA es correcto? esta tabla solo contiene este registro. Lo hemos revisado en caibter y aparece correctamente.

Referente al https://appsproves.caib.es/sites/directorimitjans/ca, aparecen desplegados porque esos menús se han configurado como fix-obert, si se desea que aparezcan por defecto plegados deberian configurarse como carpeta. Si eliminamos esa opción apareceran por defecto plegados pero se perdera esa funcionalidad, es decir, no se podrá elegir si debe aparecer abierto o cerrado por defecto. ¿Quereis que en la plantilla 2017 eliminemos esta funcionalidad y aparezcan siempre plegados por defecto?(si hay una opción del menú seleccionada aparecerá desplegado)
![imagen](https://user-images.githubusercontent.com/17451407/30633774-2bfcfc98-9ded-11e7-90d4-1dbf6b70d69e.png)

**Comment by slromero-indra** [comment]
Buenas, ya hemos actualizado el tema con las propiedades de las redes sociales. lo podeis validar descargando el [tema2017](https://github.com/GovernIB/gusite/raw/283a745b94aa2c932cbe3ee47cc6c538a3b227c2/moduls/front/etc/temas/zip/tema2017.zip)

Habesi podido revisar el tema de la BBDD?
Referente a los menús en el tema2017, omitimos la funcionalidad "Fix Obert/Carpeta" para que aparezcan siembre plegados?

**Comment by sgelabert-dgtic** [comment]
- Ok al tema enllaços a les xarxes socials. Passaré el canvi a PREProducció i us dic coses si hi ha res de nou.
- He enviat consulta per veure els valors de l'entorn de PREproducció a Sistemes, sobre el tema del versionat. Entenc que quan s'importa el tema s'hauria d'actualitzar aquest valor, no?
- El comportament del menú que m'indiques és correcte. Desconeixia aquesta opció.

**Comment by slromero-indra** [comment]
Ese valor no se actualiza, es el nombre de la versión de la plantilla. Este valor se añadió a través de los scripts de BBDD al pasar a la versión 1.2, y por lo que hemos visto no se actualiza a través de la aplicación.

**Comment by sgelabert-dgtic** [comment]
El camp FTE_VERSION és buit a l'entorn de PREproducció, entenc que deu agafar un valor per defecte.
Hauriem d'afegir aquest camp a la pantalla perquè fos gestionable via aplicació.

**Comment by sgelabert-dgtic** [comment]
L'aplicació de la plantilla2017 a llistats tipus galaria de fotos provoca que les imatges surtin tallades, amb la plantilla2015 efectuva un escalat. Us adjunt captures de pantalla.
**Plantilla 2015**
![image](https://user-images.githubusercontent.com/17268396/31703015-d1a47b78-b3da-11e7-91e4-39c755f4fd28.png)
**Plantilla 2017**
![image](https://user-images.githubusercontent.com/17268396/31703046-030547b0-b3db-11e7-9292-1b6a43597a46.png)
URL microsite: http://www.caib.es/sites/infografies/ca/l/infografies/

**Comment by sgelabert-dgtic** [comment]
Per altra banda, s'hauria d'afegir l'icona Intranet a la toolbar superior, seguint la mateixa lògica que webcaib

**Comment by sgelabert-dgtic** [comment]
Ens adverteixen que les icones de les xarxes socials del peu de pàgina no estan centrades.
GUISTE (no centrat):
![image](https://user-images.githubusercontent.com/17268396/31704990-f6c6641c-b3e3-11e7-8521-49ee3659591b.png)
WEBCAIB (ok):
![image](https://user-images.githubusercontent.com/17268396/31705051-32a65ef6-b3e4-11e7-940e-d4591521cc67.png)

**Comment by slromero-indra** [comment]
Subido una nueva versión que actualiza los problemas con los iconos de redes sociales y las imágenes. Deberéis subir de nuevo el tema2017.zip para ver los cambios.

**Comment by sgelabert-dgtic** [comment]
Es suficient amb aplicar el tema o cal actualitzar l'ear ?
Per altra banda, resta per incorporar la icona de la Intranet a la toolbar superior

**Comment by slromero-indra** [comment]
Es suficiente con aplicar el tema sólo (no hace falta subir de nuevo el ear). Miramos el tema del icono de intranet, debe estar siempre visible o debe mirar como en webcaib si tiene la cookie? En caso de ser la segunda opción, se deberá de hacer cambios en el ear para agregar el parámetro.

**Comment by sgelabert-dgtic** [comment]
Ok ara ho provam, matxacarem l'actual.
Repecte a l'icona intranet cal emular el comportament de WEBCAIB, és a dir, només ha d'apareixer si t'has autenticat a la Intranet

**Comment by slromero-indra** [comment]
Respecto a la detección de la intranet, hemos realizado pruebas (accediendo a la intranet de pruebas y accediendo luego a microsites) y revisado el código (toda referencia a intranet se refiera más a un estado del microsite más privado que exige acceder con un usuario) y no hemos observado ninguna referencia a una comprobación como se realiza en WEBCAIB (comprobando si tiene la cookie de la intranet).

Si te parece correcto, procederemos a importar en la medida de lo posible el código de WEBCAIB para comprobar si tiene el usuario la cookie de la intranet y a mostrar en dicho caso el icono de la intranet.

**Comment by sgelabert-dgtic** [comment]
ok

**Comment by slromero-indra** [comment]
Incorporado la intranet en el plugin. Se debe volver a subir el zip para revisar el cambio.

Para las pruebas, se debe entrar al site con el tema2017 antes y después de entrar a la intranet logeado.

**Comment by slromero-indra** [comment]
Hemos incorporado la url de la intranet por propiedades:

es.caib.gusite.enlaces.intranet=http://intranet.caib.es/?lang={0}

**Comment by sgelabert-dgtic** [comment]
Cada paraula del títol dels formularis de contacte apareix en majúscula quan en el backoffice apareix en minúscula. S'hauria de mantenir el format del backoffice. Adjunt captures de pantalla.
**Títol front:**
![image](https://user-images.githubusercontent.com/17268396/32091041-b47ea27a-baf2-11e7-84ef-f548f9ad5481.png)
**Títol back**
![image](https://user-images.githubusercontent.com/17268396/32091023-9bef9732-baf2-11e7-93fe-628c98638860.png)

**Comment by slromero-indra** [comment]
Actualizado para que no realice un capitalice en el formulario de contacto. Habría que volver a subir el zip del tema2017.

**Comment by slromero-indra** [comment]
La DG de Transparència  solicitaba una serie de cambios sobre el tema para adecuarse a sus requisitos. Para satisfacer los requisitos sería recomendable:

- Incluir menú principal en horizontal: Se incluiría una opción en la pestaña Configuración/General del microsite que por defecto sería vertical. Al pasar a la opción horizontal hay que tener en cuenta que los menús principales estarían contraídos y que no se podría quedar la opción del menú seleccionada. 

- Emulación de botón estilo WEBCAIB. Se incluiría una opción en el menú superior de tinymce para incluir un botón con el aspecto. El aspecto se parecería a los botones del siguiente enlace: http://www.caib.es/govern/indexadm.do?lang=ca

- Emulación de la lista estilo WEBCAIB. Mediante la utilización de los componentes y de las listas, incluiríamos las opciones necesarias para poder incluir una lista con el estilo de webcaib. El aspecto se parecería a alguna de las listas de la página (informació, organització, serveis o transparencia): http://www.caib.es/govern/organigrama/area.do?coduo=2&lang=ca

¿Os parece correcto el planteamiento?

**Comment by sgelabert-dgtic** [comment]
Sí, és correcte.  Els canvis es poden envestir però separadament en tasques independents. La plantilla només hauria d'aplicar estils MIC a les noves funcionalitats desenvolupades.

**Comment by sgelabert-dgtic** [comment]
S'ha localitzat una errada de presentació en el detall dels elements del llistat tipus Fitxa. Pareix que es presenta la informació en columnes: http://www.caib.es/sites/activitats/ca/presentacio-29650/
Adjunt captura de pantalla.
![image](https://user-images.githubusercontent.com/17268396/33200987-102cd97e-d0f7-11e7-8416-1a4369cabb59.png)

**Comment by slromero-indra** [comment]
Hemos actualizado la plantilla para que únicamente se muestre una columna.

**Comment by sgelabert-dgtic** [comment]
He fet el commit únicament sobre la 1.5, mentre que aquest tiquet és de la 1.4.
Ho podeu consolidar, per favor ?

**Comment by slromero-indra** [comment]
Hemos incorporado los cabios en la rama 1.4
