### ISSUE TITLE
Problema conversión url front antiguo al front nuevo por falta parámetro idioma

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#66]
Resulta que google ha indexado en algunos casos microsites sin referencias al idioma (faltandolé el parámetro lang):
http://www.caib.es/sacmicrofront/contenido.do?idsite=157&cont=17186

Al pulsar, salta un error que indica que falta el parámetro lang. La url se convierte a: 
http://www.caib.es/sites/contenido.do?idsite=157&cont=17186

Podéis corregir que si no se indica en la front antiguo el idioma, tome el idioma por defecto de la configuración del backoffice. 

Por otro lado, si se referencia el idioma(lang=ca) en front antiguo se reconvierte a:
http://www.caib.es/sites/eines/introduccio_als_microsites-17186/
en lugar de : 
www.caib.es/sites/eines**/ca/**introduccio_als_microsites-17186/

**Comment by slromero-indra** [comment]
Se han realizado varios casos, se ha observado que en la clase LegacyController.java, la que se encarga principalmente de reescribir entre el front viejo y el nuevo,  ningún parámetro de idioma tiene valor por defecto. Por tanto, es probable que este problema también se pudiera de dar en otras entidades (agenda, noticias...).

Pruebas realizadas (se puede ver en caibter):

# **CONTENIDO:**

**CA**
http://caibter.indra.es/sites/contenido.do?idsite=41&cont=127  
Genera --> http://caibter.indra.es/sites/indra/ca/sub_b12/

**ES**
http://caibter.indra.es/sites/contenido.do?idsite=41&cont=127&lang=es
   Genera --> http://caibter.indra.es/sites/indra/es/sub_b12/

# **AGENDA:**

**CA**
http://caibter.indra.es/sites/agendas.do?idsite=41
   Genera --> http://caibter.indra.es/sites/indra/ca/agenda/

**ES**
http://caibter.indra.es/sites/agendas.do?idsite=41&lang=es
   Genera --> http://caibter.indra.es/sites/indra/es/agenda/

# **NOTICIA:**

**CA**
http://caibter.indra.es/sites/noticia.do?idsite=41&cont=93
    Genera --> http://caibter.indra.es/sites/indra/ca/n/program1/

**ES**  
http://caibter.indra.es/sites/noticia.do?idsite=41&cont=93&lang=es
    Genera --> http://caibter.indra.es/sites/indra/es/n/programador1/

# **FAQS:**

**CA**
http://caibter.indra.es/sites/faqs.do?idsite=41 
    Genera --> http://caibter.indra.es/sites/indra/ca/faq/

**ES**  
http://caibter.indra.es/sites/faqs.do?idsite=41&lang=es
    Genera --> http://caibter.indra.es/sites/indra/es/faq/

Además, se ha observado un error no comentado en el tema2015 en listarfaqs.html , al entrar en un faq, se produce un error (falta cerrar una etiqueta dd). Se ha aprovechado y se ha solucionado también ese error. El error que producía:
     _**org.xml.sax.SAXParseException; lineNumber: 70; columnNumber: 7; The element type "dd" must be terminated by the matching end-tag "</dd>".**_
