### ISSUE TITLE
Problema visualización del nuevo front con ie11

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#67]
Resulta que aquí en el govern tenemos instalado el ie11 con comptabilidad ie7 y hace que se visualice mal:

![problema_gusite_ie11](https://cloud.githubusercontent.com/assets/17451683/20524818/9f3d3c46-b0bc-11e6-8638-8393d9f8028d.gif)

**Comment by sgelabert-dgtic** [comment]
Cal forçar el mode de compatibilitat mitjançant l'etiqueta :
```
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```
Perquè funcioni, aquesta etiqueta ha d'estar col·locada just després de l'etiqueta head --> title:

```
<head> 
<title> ....</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
 ...
</head>
```

**Comment by slromero-indra** [comment]
Buenas, ya se ha comiteado los cambios. Es importante tener en cuenta que algunas veces da problemas por el historial, si se ve que no funciona borrar el historial, revisar que esté la url en la lista de compatibilidad y volver a probar.
