### ISSUE TITLE
Incorporar captcha als formuaris de contacte

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#72]
Amb l'objecte d'evitar l'spam sobre les adreces de correu associades als formularis de contacte de l'aplicació, es sol·licita la incorporació d'un camp "captcha" que es validi como passa prèvia a l'enviament del formulari.

**Comment by slromero-indra** [comment]
Buenas, se va a optar por la utilización de simplecaptcha (http://simplecaptcha.sourceforge.net/) por las características que tiene: accesible, código abierto y compatible con java.

**Comment by episano-dgtic** [comment]
En el caso de que no se rellene la captcha o se equivoque el usuario al rellenarlo, se vuelve a cargar el formulario con los campos vacios. Debería mantener los datos indicados por el usuario.

**Comment by slromero-indra** [comment]
Buenas, esto supondría un cambio de funcionamiento en como se está gestionando el formulario (antes de meter el captcha si daba un error no mantenía los datos). Lo más conveniente sería una issue específica para este tema porque sino en esta se pasará de horas.

**Comment by episano-dgtic** [comment]
No sé a qué te refieres.. porque la única manera de que antes diera un error, es que se estuviera reiniciando microsites, o no funcionara la utilidad. 
Los formularios actualmente no tienen control de errores en la entrada de campos, sino únicamente el control en la obligatoriedad de los campos. Y si estos estaban completados, se limita a enviar el formulario, sino se rellenan te avisa que debes rellenar x campos.

Un control muy sencillo es si no se rellena la captcha, no puedas enviar el formulario. Si te refieres a que la persona se ha equivocado al rellenar la capctha acepto tu comentario.

**Comment by sgelabert-dgtic** [comment]
El literal associat a la captcha sempre surt amb castella amb independència de l'idioma de navegació 
![image](https://cloud.githubusercontent.com/assets/17268396/25615826/a9c3a884-2f39-11e7-9b29-37cb5de1a6ac.png)

**Comment by slromero-indra** [comment]
Hemos corregido el problema del idioma. El problema era más complejo que simplemente añadirlo en los ficheros de localización.

Si se vuelve a conectar a la página del microsite (sin actualizar GUSITE), veremos que en el footer la palabra 'Accessibilitat' estará siempre en catalán, cuando en todas páginas se lee correctamente según el idioma. Este se debe a que el idioma se obtiene desde la clase UriLocaleResolver que lo calcula a partir de la URI. El problema es que la URL en contacte no es igual que todo el resto de páginas. En todas las páginas el idioma está en la URL (sino es el catalán) mientras que en Contacto el idioma depende de si llamamos a 'contacto' (castellano), 'contacte' (catalán) o 'contact' (inglés).

**Comment by sgelabert-dgtic** [comment]
El camp "Rellene el captcha" segueix sense traducció en català ("Empleni el captcha")
https://appsproves.caib.es/sites/M170111145046629/contacte/4998/

Per altra banda, no m'agrada gens el canvi /contacte /contacto però bé, intentarem reprendre el tema de la gestió d'URIs amb el formularis de contacte per la versió 1.4 (la tasca està estimada)

**Comment by slromero-indra** [comment]
Buenas, hemos revisado el sacmicroback y hemos observado que la versión subida no es la última, está la https://github.com/GovernIB/gusite/commit/6809886 (versión de hace dos días) cuando debería ser la versión https://github.com/GovernIB/gusite/commit/7093369 (la versión de ayer). Por favor, cuando podáis subir de nuevo la última versión de la rama 1-3.

El microsite https://appsproves.caib.es/sites/M170111145046629/contacte/4998/ no tiene tema por lo que no hay que hacer nada para comprobar si está correcto tras subir la nueva versión. Si se quisiera probar con un microsite con tema, hay que actualizar el tema2015 y volverlo a importar para que se vean los cambios.

Saludos!
