### ISSUE TITLE
Bug breadcrumb UA presidència

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#73]
El link de la UA de presdiència en el breadcrumb de l'aplicació genera una url inexistent de webcaib
http://www.caib.es/govern/presidencia.do?lang=ca
Corregir-ho perquè la UA de presidència funciona com la resta d'UA:
http://www.caib.es/govern/organigrama/area.do?lang=ca&coduo=2

Adjunt captura de pantalla amb exemple.
![bugbreadcrumbpresidencia](https://cloud.githubusercontent.com/assets/17268396/21801972/3134f70a-d724-11e6-86a6-9d3187efeb3a.jpg)

**Comment by sgelabert-dgtic** [comment]
La URL configurada ara és http://www.caib.es/govern/presidencia.do?lang=ca&coduo=2 quan la que us demavem es http://www.caib.es/govern/organigrama/area.do?lang=ca&coduo=2. És a dir, no volem un tractament especial per la UA de Presidència.

**Comment by slromero-indra** [comment]
Buenas, perdón por el malentendido, se ha quitado cualquier referencia a presidencia.do y simplificado el código. Al quitar que se llame a presidencia.do, también se ha quitado la propiedad de jboss-service.xml _es.caib.gusite.codigoUO.presidencia_ la cual ya no se utiliza.
