### ISSUE TITLE
Bug exportació/eliminació MS sense continguts

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#74]
Es sol·licita controlar l'error que es genera quan s'intenta exportar o eliminar un microsite sense continguts.
Teniu un exemple a CAIBTER: http://caibter.indra.es/sacmicroback/index.do?idsite=343
Si creau un pàgina, llavors sí que funciona.

**Comment by slromero-indra** [comment]
Buenas, estamos realizando pruebas y parece que se produce una serie de problemas debido a un conflicto entre librerías del ear y el jboss. Parece que la librería javaassist tiene un conflicto la versión incluida del ear (3.16) con la versión de jboss (3.12) y en nuestras primeras pruebas parece que borrando la versión incluida en el ear soluciona el problema. Lo más problemático es que en el application.context no se incluye la librería. Eliminar el jar de javaassist en el ear solucionará este problema pero podría provocar algún error en otra librería si utilizaba la v3.16.

Se ha observado que en el application.context de gusite incluye muy pocas librerías pero por contra el número de librerías incluido en el ear es enorme (comparado con las incluidas en el application.context). Ese número de librerías incluidas de más producirá seguramente diversos conflictos y se debería realizar una limpieza en profundidad para excluir las librerías no necesarias o ya aportadas por jboss. 

Se debería introducir una nueva issue como la incluida en su vez en rolsac (cuando se realizó una limpieza de las librerías cuando pasó a modo isolated sobre jboss 3).

**Comment by slromero-indra** [comment]
No está ningún fichero comiteado a la espera de revisar si falla algo o por si no os parece correcto el planteamiento.

**Comment by sgelabert-dgtic** [comment]
Heu provat d'inicialitzar prèviament les col·leccions que es recuperen amb el Microsite ? Segurament la que peta és la de Menú. Ho dic perquè si hi ha menu, llavors no dóna l'error.

En quant a les llibreries, si l'ear és isolate no hauria de fer ús de la 3.12 del jboss si no de la  3.16 de l'ear. Imagin però que el javassist té dependències amb les llibreries d'Hibernate, les quals no estan empaquetades i s'utilitzen les del jboss. I d'aquí les incompatibilitats ... És així?

Mirau en primera instància si inicialitzant les col·leccions es soluciona l'error. Si no hi trobeu remei o la cosa es complica he obert tiquet per neteja/revisió de llibreries, però avisau-nos abans d'envestir la tasca,

**Comment by rsanz-indra** [comment]
No es cuestión de inicializar colecciones, ya que el error lo da al cargar el objeto, o sea antes de poder hacer nada con las colecciones:
MicrositeCompleto site = (MicrositeCompleto) session.get(MicrositeCompleto.class, id);
Aquí da un ClassCastException, por lo que no se puede inicializar a posteriori ninguna colección del objeto.

El error de ClassCastException del proxy de javassist que da, aparece documentado en varios casos como una duplicidad de librerías de javassist y efectivamente una vez se ha dejado una sola librería no ha dado el error. Es raro que solo pase cuando esta esa colección vacía, pero no se puede hacer nada sobre la colección, ya que como se ha comentado antes el error se produce en la carga inicial del objeto.

La teoría como comentas indica que al ser isolated debería tener preferencia la librería del ear, pero también esta haciendo algo raro el despliegue, ya que casi todas las librerías en la carpeta lib del ear no están referenciadas en el application.xml, por lo que a priori tampoco deberían cargarse. La librería javassist del ear no aparece en el application.xml.

En mi opinión debería hacerse una limpieza de jars también para Gusite como se hizo con Rolsac y dejar el application.xml coherente con la carga de librerías que se necesita. En cuanto a la versión de javassist entiendo que se debería usar la de JBoss, que es la que tiene la dependencia con sus librerías de Hibernate. Quedaría comprobar si existe alguna dependencia con esa librería el resto de librerías que emplea Gusite, una vez se limpien y se dejen las que toca.

**Comment by rsanz-indra** [comment]
Según parece JBoss5 carga todos los jars que están en el directorio lib del ear

**Comment by sgelabert-dgtic** [comment]
Ok. Per estar segur doncs, esperarem a tenir resolt el tiquet #75 abans de passar-ho a producció.

**Comment by episano-dgtic** [comment]
Funciona la importación microsites sin contenidos.
