### ISSUE TITLE
Eliminació de llibreries no utilitzades en el projecte

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#75]
En relació amb la incidència #74 es sol·licita revisar la compatibilitat i les llibreries obsoletes incorporades en el projecte, tant del respositori de codi, com les que s'empaqueten dins l'ear, a fi de deixar només les estrictament necessàries.

**Comment by slromero-indra** [comment]
Actualmente vemos que en el directorio de deploycaib existe el ear de librerías.
Entendemos que el objetivo es que se elimine este ear de librerías y todos los ears se carguen de forma isolated. @sgelabert-dgtic

**Comment by sgelabert-dgtic** [comment]
No és correcte, ja no empram 00librerieas.ear en cap projecte. 
Les aplicacions són totes isolate, GUSITE entre elles.

**Comment by rsanz-indra** [comment]
Eso es lo que comentamos, que el ear de librerias no debe estar y todas las aplicaciones isolated.
Ese ear se nos habrá quedado como histórico dentro de nuestra instalación, lo eliminamos.
