### ISSUE TITLE
Errada log org.apache.catalina.log pas a producció 

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#76]
Tenim errada greu per el pas a producció de la versió 1.3 de l'aplicació, en qüestió minuts es generen GB de log org.apache.catalina.log
Adjunt logs per correu electrònic

**Comment by rsanz-indra** [comment]
No hemos recibido el log todavía...

**Comment by slromero-indra** [comment]
Buenas, viendo el siguiente error:

85.119.193.100 - - [14/Feb/2017:09:18:17 +0100] "GET /sites/M10100513285123935078/ca/portada_4-62368/tinymce/jscripts/tiny_mce/plugins/tipoarchivos/images/pdf.gif HTTP/1.1" 500 56895

Sería muy interesante si pudierais exportar el microsite con la uri M10100513285123935078 para poder importarlo en nuestro entorno y así poder replicar el mismo error.

**Comment by slromero-indra** [comment]
Solventado en el commit https://github.com/GovernIB/gusite/commit/ee9593d8bd3a17f43fc44ba5369c176540cf6ae7

**Comment by episano-dgtic** [comment]
Ahora no aparece el error en los logs, pero siguen si aparecer alguna iconografia que en el antiguo backoffice existía. EX: icono de libre/open office (<img alt="Manual usuari sistema EXSANCI-TAXES (Helium).odt" src="imgs/archivos_prev/odt.gif" />)
https://proves.caib.es/sites/M207/ca/manuals_exsanci-taxes_helium-56543/

**Comment by slromero-indra** [comment]
Buenas, vamos a revisar el problema, por favor, podéis exportar el microsite y pasárnoslo por si es un problema en el microsite.

**Comment by episano-dgtic** [comment]
No es un problema del microsite.. en el antiguo backoffice se permitía insertar esta iconografía y con el nuevo front no aparecen algunas posibilidades iconos ni en el gestor (en el editor de html, con el tercer icono insertar icones) ni en el frontal.  
Si pongo dicho microsite con antiguo diseño, el icono aparece: 
https://proves.caib.es/sacmicrofront/contenido.do?mkey=M207&lang=CA&cont=56543


Te paso el código html de dicha página. 
```
<p>&nbsp;</p>
<p><b>Manuals aplicaci&oacute; Exanci-Taxes Helium</b>:</p>
<p><a href="archivopub.do?ctrl=MCRST207ZI146144&amp;id=146144"><img alt="Manual usuari sistema EXSANCI-TAXES (Helium).odt" src="imgs/archivos_prev/odt.gif" /></a><a href="archivopub.do?ctrl=MCRST207ZI153552&amp;id=153552">Manual usuari sistema EXSANCI-TAXES (Helium).odt</a></p>
<p><a href="archivopub.do?ctrl=MCRST207ZI145855&amp;id=145855"></a></p>
<p><img alt="Manual Gesti&oacute; Documental EXSANCI-TAXES.odt" src="imgs/archivos_prev/odt.gif" /><a href="archivopub.do?ctrl=MCRST207ZI144877&amp;id=144877">Manual Gesti&oacute; Documental EXSANCI-TAXES.odt</a></p>
```

**Comment by episano-dgtic** [comment]
Salvador me comenta que habéis subido más iconografía.. pero no habéis modificado el editor para que el gestor pueda incluirlos.

**Comment by slromero-indra** [comment]
Buenas, lo que se modificó fue el nombre de la carpeta contenedora de las imágenes, la iconografía continua siendo la misma, por lo que no ha sido necesario modificar el editor. 
En este último commit se ha añadido el icono que daba problemas.
