### ISSUE TITLE
Millora component llistats: tipus mapa

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#77]
Es sol·licita incorporar una nova tipologia de llistat als existents anomenada "Mapa" que permeti el geoposicionament de cada element del llistat sobre un mapa de GoogleMaps. Aquesta modificació requereix:
- Introduir dos camps nous "latitud" i "longitud" a la pantalla d'element de llistat. Valorar la incorporació d'alguna utilitat per adquirir visualment les coordenades (veure utilitat "Coordenades" del manteniment d'edificis ROLSAC)
- Modificar el frontal perquè, mitjançant l'API de GoogleMaps es posicioni l'element sobre el mapa.
- Al clicar sobre el punt del mapa, s'ha d'obrir una finestra emergent amb la informació del llistat que inclourà el títol, descripció HTML, document i imatge associada (en cas d'existir)

**Comment by sgelabert-dgtic** [comment]
El fitxer scripts/bbdd/1.4/gusite_update_schema_from_1.3_to_1.4.sql conté sentències DML. Cal traspassar els inserts en un nou fitxer scripts/bbdd/1.4/gusite_update_data_from_1.3_to_1.4.sql
Endemés cal incorporar l'script scripts/bbdd/1.4/gusite_create_schema.sql

**Comment by slromero-indra** [comment]
Hemos realizado los cambios indicados (llevar los inserts a un fichero update_data y crear el fichero create schema), y para no perder la coherencia, hemos creado el fichero gusite_create_data.sql, con todos los inserts necesarios.

**Comment by slromero-indra** [comment]
Buenas, hemos visto que habéis subido la versión 1.4 a proves, pero parece que falta la propiedad es.caib.gusite.key.google.maps=keyGoogleMaps en el jboss-service. Es necesario añadir esta propiedad para poder validar esta issue.

**Comment by sgelabert-dgtic** [comment]
Actualitzada la propietat.
- En el document d'estimació es detallava que s'afegiria una opció "Añadir Botón para acceder a una ventana que permita capturar la latitud y longitud", la pantalla permetria "cercar adreça", "centrar mapa", "acceptar coordenades", "esborrar coordenades" i "tornar". No veig aquesta utilitat
- Hi ha un error no controlat quan es canvia d'idioma sense que el llistat tingui traducció [log_mapa.txt](https://github.com/GovernIB/gusite/files/1094299/log_mapa.txt)
- Sobra la darrera / de la URL de redirecció cap al mapa https://appsproves.caib.es/sites/M170111145046629/ca/l/test2/?mcont=67738.
- Cal eliminar del frontal el peu "1 a 3 de 3 - ". Endemés el titol del mapa surt massa aferrat a la barra del cercador (aquest error passa amb altres elements). 
Adjunt captura de pantalla
![mapa](https://user-images.githubusercontent.com/17268396/27429448-6697893e-5745-11e7-9a27-da66bfdf23e2.jpg)
- El els llistat tipus fitxa veig que heu optat per integrar-ho dins una pàgina de microsites enlloc de fer un popup. Ho podem deixar així.  Ja que hi som podríem fer que aparegui el subtitol i la imatge si existeixen. A més convé incloure en el backoffice el botó per la captura de coordenades en llistat tipus fitxa

**Comment by slromero-indra** [comment]
Buenas
1.  Respecto a este punto, no entendemos por qué no os aparece, solo debería ocultarse si no encuentra la propiedad que os indicábamos, entendemos que habéis reiniciado el jboss y borrado los temporales, ¿es correcto? lo hemos validado nuevamente y a nosotros nos aparece. ¿Podéis facilitarnos el ear generado y el fichero de propiedades usado para verificarlo en nuestros entornos?

2. El error de traducción es un tema que ya se daba en los otros tipos de listado, si no existe la traducción del nombre del listado aparece el error indicado al intentar el cambio de idioma. Entendemos que haceis referencia a ese error. En este caso creemos que debería tratarse en una incidencia especifica, así no hacemos depender la validación de este desarrollo a la resolución de un tema preexistente. os parece bien?

3. Entendemos que os referís a la "/" existente después de test2 ¿correcto? La construcción de la URL es la misma para todos los tipos de listado, y no hemos modificado este comportamiento. Modificarlo afectará a todos los listados. ¿Queréis que modifiquemos la manera de montar la url para que no aparezca la "/" del final? Convendría tratarlo en una issue separada por la misma razón que el punto 2. 

4. Eliminaremos el pie tal como indicas, y referente al tema del título, existen varias opciones, una de ellas es modificar el ancho del buscador para que no quede tan pegado al contenido, ya que todos los listados tienen la misma posición del título. os parece adecuado?

5. Añadiremos el subtítulo y la imagen al consultar una ubicación, entendemos que deben aparecer dentro del popup del mapa ¿es correcto?

**Comment by slromero-indra** [comment]
Buenas, hemos realizado las modificaciones de los puntos 4 (hemos eliminado el pie y reducido ligeramente el ancho del buscador) y 5 (hemos incluido el subtitulo y la imagen en el popup)

Quedamos a la espera de que nos indiqueis que hacer sobre los puntos 1,2 y 3.

**Comment by sgelabert-dgtic** [comment]
Respecte al punt 1, he comprovat que hi ha la propietat definida i hem esborrat temporals i reiniciat de nou el servidor sobre l'entorn de PRE. El problema persisteix.
Podeu provar-ho amb https://proves.caib.es/sacmicroback/index.do?idsite=5906

**Comment by slromero-indra** [comment]
Gracias, nos podeis facilitar el ear y el fichero de propiedades? no conseguimos reproducirlo en nuestros entornos, a ver si así conseguimos replicarlo.

**Comment by sgelabert-dgtic** [comment]
Remet informació sol·licitada per correu
També he enviat la darrera versió a commitada sobre la branca 1.4 a PRE. Dilluns ho tornaré a provar amb aquest nou ear.

**Comment by slromero-indra** [comment]
Buenas, 
hemos revisado los archivos adjuntos, y hemos detectado el origen del problema. Al parecer el fichero de propiedades contiene un carácter especial justo antes de la propiedad, a primera vista parece un espacio, pero si se cambia la codificación o se activa la función de mostrar todos los caracteres se aprecia que no lo es. Una vez corregido el fichero os debería empezar a funcionar correctamente.

Quedamos a la espera de que nos indiquéis que hacer sobre los puntos 2 y 3.

![imagen](https://user-images.githubusercontent.com/17451407/27482799-25fb8ad6-5823-11e7-82b1-a713211e9589.png)

**Comment by sgelabert-dgtic** [comment]
Sistemes diu que no hi ha cap caràcter previ (ha eliminat els espais previs). En qualsevol cas, després del deseplegament de la versió https://github.com/GovernIB/gusite/commit/71a8cab ja apareix el popup de coordenades tant en llistats tipus Fitxa com en tipus Mapa
