### ISSUE TITLE
Deshabilitar opció cercador del menú Configuració General

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#78]
Actualment no s'emmagatzemen els canvis en el cercador efectuats en Configuració General (Aparença) per usuaris amb rol GUS_SUPER. Donat que tampoc poden indexar el microsite, es sol·licita dehabilitar aquesta opció de Configuració General per el rol GUS_SUPER.

**Comment by slromero-indra** [comment]
Ya sé quita la opción si se tiene el rol GUS_SUPER. Al quitarlo, se produce que hay dos filas con el mismo color (ambas blancas), si queréis dedico más tiempo en cambiar el fondo del color dependiendo del rol. Saludos!

**Comment by sgelabert-dgtic** [comment]
El camp "Visible el menú corporatiu? " tampoc emmagatzema els canvis  amb rol GUS_SUPER. Ho podeu revisar?

**Comment by sgelabert-dgtic** [comment]
A més amb el rol GUS_SYSTEM ha desaparegut també l'opció "Desitges cercador? >	 Sí    No"
![image](https://cloud.githubusercontent.com/assets/17268396/25482046/43638a92-2b50-11e7-88df-31ff5e64cf86.png)

**Comment by slromero-indra** [comment]
Buenas,
Ya debería verse correctamente, lo hemos validado en nuestro entorno y aparecen las opciones solo para GUS_ADMIN y GUS_SYSTEM

**Comment by sgelabert-dgtic** [comment]
No entenc perquè heu eliminat l'opció "Visible el menú corporatiu?" amb el rol GUS_SUPER. Se us demanava revisar perquè no emmagatzemava valor, no que l'ocultéssiu

**Comment by slromero-indra** [comment]
Buneas,
Cuando comentasteis que lo revisaramos entendimos que habia que tratarlo igual que la opcion de buscador.
Actualmente estas dos opciones están filtradas a nivel de código para que se almacene el valor solo en el caso de que el usuario tenga el rol system o admin. esta restricción está en \moduls\microback\htdocs\microGeneral.jsp
¿En que casos deberían aparecer estas dos opciones? ¿en que casos deberian almacenarse sus valores? ¿Ocultamos la opcion del buscador y mostramos la del menu corporativo para usuarios super y oper?

**Comment by sgelabert-dgtic** [comment]
He rellegit la incidència i crec queda ben clar. Se us demana que oculteu el camp cercador de rol GUS_SUPER, a partir d'aquí se us demana que reviseu perquè hi ha vegades que no s'emmagatzemen els valors en els camps que apareixen en cada rol. 
Em resum:
- GUS_SUPER, GUS_OPER --> Que aparegui "Visible el menú corporatiu?" i que guardi valor, que s'oculti "Desitges cercador?"
- GUS_SYSTEM, GUS_ADM --> Totes les opcions visibles i que guardin valor.
