### ISSUE TITLE
Bug redirecció pàgines de contingut eliminades 

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#81]
S'ha detectat un error quan es fa referència a un contingut (pàgina) inexistent accedint al nou front /sites des de /sacmicrofront, segurament perquè s'ha esborrat:
Exemple de redirecció correcte:
http://www.caib.es/sacmicrofront/contenido.do?idsite=48&lang=CA&cont=13529 --> http://www.caib.es/sites/ordenaciolaboral/ca/a_b_c-13529/
Exemple redirecció incorrecte:
http://www.caib.es/sacmicrofront/contenido.do?idsite=48&lang=CA&cont=953 --> http://www.caib.es/sites/contenido.do?idsite=48&lang=CA&cont=953
Podriem mirar de controlar-ho?

**Comment by slromero-indra** [comment]
Buenas, se ha añadido al tag gusite-1.3.1. y a la rama 1.3. 

Cuando se visitaba una página cuyo contenido había desaparecido, se producía el siguiente error (un error 500 no controlado).

![image](https://cloud.githubusercontent.com/assets/17451407/24543159/d9048234-15fe-11e7-9150-aaa193ead702.png)

Se controla el error y ahora se devuelve un error controlado. Por ejemplo --> http://caibter.indra.es/sites/contenido.do?idsite=41&lang=CA&cont=12127 (se puede cambiar el valor cont=12127 por cualquier otro aleatorio para provocar el mismo error)

![image](https://cloud.githubusercontent.com/assets/17451407/24542988/08689110-15fe-11e7-92b6-488552e1da1c.png)

Saludos!

**Comment by sgelabert-dgtic** [comment]
OK amb el control i la redirecció cap a la pàgina d'error, però està retornant un 200 quan hauria de retornar un 404.
Això ja es va tractar al tiquet https://github.com/GovernIB/gusite/issues/47#issuecomment-224244382

**Comment by slromero-indra** [comment]
Actualizado y comiteado los cambios tanto a gusite-1.3 como al tag gusite-1.3.1.

Ahora al conectarse a http://caibter.indra.es/sites/contenido.do?idsite=41&lang=CA&cont=12127
devuelve un 404.

![image](https://cloud.githubusercontent.com/assets/17451407/24550763/d6773306-161f-11e7-863d-6f4245958dab.png)

Hay que tener en cuenta un detalle importante, existe una clase FrontController.java que tiene un método getForwardError que se encarga, según los parámetros de entrada, de generar el contenido para el jsp errorGenerico.jsp. Al ser un error controlado, se genera un status 200.

Para generar un error 404 o similares, se hemos tenido que tocar el HttpServletResponse y forzar mediante el setStatus(CODIGO_ERROR). El problema es que en ningún momento (menos en lo cambiado justo ahora para cuando el contenido no existe) se producía un cambio en el status. Eso implica, que cualquier llamada al getForwardError genera un status 200. 

Si se desea, se podría resumen y ver todos los casos posibles (son muchos los sitios donde se utiliza) y obligar a pasar un código y HttpServletResponse para que se genere un código (403, 404, 501, etc) cuando se pasa por este método.

**Comment by sgelabert-dgtic** [comment]
Pensava que això havia quedat resolt al #47 ...
Enlloc de parxes pàgina a pàgina, no podem modificar el mètode `es.caib.gusite.front.general.bean.ErrorMicrosite.ErrorMicrosite() `perquè retorni l'error http corresponent en funció del string d'error? Torna a copiar aquí el que vaig indicar a https://github.com/GovernIB/gusite/issues/47#issuecomment-224244382
HTTP 404
static public final String ERROR_MICRO_MSG = "No s' ha trobat el microsite amb id ";
static public final String ERROR_MICRO_MSG_NULL = "No s' ha sol·licitat un microsite";
static public final String ERROR_PAGINA_MSG = "No s' ha trobat la pàgina sol·licitada";
static public final String ERROR_DOCU_MSG = "No s' ha trobat el document sol·licitat";
HTTP 403
static public final String ERROR_ACCES_MSG = "No disposa del ROL necessari per accedir al microsite."
HTTP 440
static public final String ERROR_SESSIO_MSG = "Ha excedit el temps màxim de sessió.";

**Comment by slromero-indra** [comment]
Respecto a la incidencia 81 y 47, no es posible tratar el error como se realiza en jsp, sino que debe ser controlado desde Java Spring (no es posible desde thymeleaf). En el caso del contenido es nulo, antes de redirigir a la página de error (this.getForwardError), lo que se hace es marcar la salida con un 404 (response.setStatus).

La manera correcta de hacerla sería modificar todos los métodos en Spring que utilicen el getForwarError, obtener también el HttpServletResponse y pásarselo al constructor getForwarError como un parámetro extra (de esa manera, todos los métodos que lo utilicen deberían pasársela) controlándose el código del status desde ese método a partir del texto que se pase de error. Realizar este cambio no es difícil pero SÍ es muy costoso (se debería tocar en todos los Controller que se llame a este método y no son pocos)

Se podría investigar, si te parece bien, si es posible obtener el HttpServletResponse desde el getForwardError (así sólo se deberia tocar en la clase ErrorMicrosite) pero le hemos dedicado un tiempo a investigar y parece que la única manera de conseguirlo es desde donde te hemos comentado antes, dedicamos más tiempo si es posible obtenerlo desde aquí o realizamos ya los cambios?

**Comment by sgelabert-dgtic** [comment]
El que us proposava es precisament la segona opció (modificar ErrorMicrosite). Tirau per aquí i si el tema es complica em tornau a dir coses.

**Comment by slromero-indra** [comment]
Hemos buscado más información sobre la segunda opción y no hemos visto solución posible más que pasar como parámetro el HttpServletResponse. Además, habría que ver que código de error pasar en cada caso. 

Hemos visto las invocaciones y hay unas 130. 

Salvo que uséis el código de error para algo, de cara al usuario no es relevante. Ya nos indicáis que hacemos.

**Comment by sgelabert-dgtic** [comment]
Avaluau cost de la tasca. Movem la incidència per la versió 1.4

**Comment by sgelabert-dgtic** [comment]
Ok, podeu envestir la tasca segon document d'estimació

**Comment by slromero-indra** [comment]
Buenas, para comprobar y validar las pruebas hemos utilizado un batería de pruebas para ver si el código de status cambia correctamente (las pruebas para producir un error no controlado y que se vea el código 500 se pueden realizar en tiempo de depuración por lo que no podemos añadir una URL para testearlo).


## Front 
	
AgendaController    --> caibter.indra.es/sites/indra2/ca/agenda/20190301 (404) Microsite inexistente

ArchivoController --> caibter.indra.es/sites/indra2/f/66666 (500) No está controlado el error porque no se puede (es un gestor de archivos, devuelve los archivos)
	
ContenidoController --> caibter.indra.es/sites/indra/ca/c/6666666 (404)  Contenido inexistente
							caibter.indra.es/sites/indra2/ca/c/6666666 (404) Microsite inexistente

CercadorController  --> caibter.indra.es/sites/indra2/cercar/		  (404)  Microsite inexistente
						
Contacte 			--> caibter.indra.es/sites/indra2/ca/contacto/ (404) Microsite inexistente

Encuestas 			--> caibter.indra.es/sites/indra2/ca/encuestas/ (404) Microsite inexistente

Faq 				--> caibter.indra.es/sites/indra2/ca/faq/   (404) Microsite inexistente

Noticia				--> caibter.indra.es/sites/indra/ca/n/afsdasdf (404) Contenido inexistente				
							caibter.indra.es/sites/indr2a/ca/n/afsdasdf (404) Microsite inexistente
		
QSSI				-->  caibter.indra.es/sites/indra/ca/qssi/12/ (404) Contenido indexistente
							 caibter.indra.es/sites/indra2/ca/qssi/12/ (404) Microsite inexistente		
							
## Front - LegacyController			
			
ENCUESTAS:
caibter.indra.es/sites/agenda.do?idsite=666&cont=12 (404) Microsite inexistente
	
CONTENIDO:
caibter.indra.es/sites/contenido.do?idsite=41&cont=12  (404) Contenido indexistente
caibter.indra.es/sites/contenido.do?idsite=6666&cont=12 (404) Microsite inexistente
	
CONTACTO:
caibter.indra.es/sites/contacto.do?idsite=41&cont=12 (404) Contenido indexistente
caibter.indra.es/sites/contacto.do?idsite=6666&cont=12 (404) Microsite inexistente
	
ENCUESTAS:
caibter.indra.es/sites/qssi.do?idsite=666&cont=12 (404) Microsite inexistente
	
FAQ:
caibter.indra.es/sites/faq.do?idsite=666&cont=12 (404) Microsite inexistente
	
NOTICIA:
caibter.indra.es/sites/noticia.do?idsite=41&cont=12 (404) Contenido indexistente
caibter.indra.es/sites/noticia.do?idsite=666&cont=12 (404) Microsite inexistente
	
QSSI:
caibter.indra.es/sites/qssi.do?idsite=41&cont=12 (404) Contenido indexistente
caibter.indra.es/sites/qssi.do?idsite=666&cont=12 (404) Microsite inexistente

**Comment by sgelabert-dgtic** [comment]
- ArchivoController --> Quan es sol·licita un arxiu inexistent retorna un 200 (https://proves.caib.es/sites/enlaces/f/6666). Retorna un 500 quan es sol·licita un arxiu d'un microsite inexistent (https://proves.caib.es/sites/indra2/f/6666), en canvi l'accés a un microsite inexistent retorna correctament un 404 (https://proves.caib.es/sites/indra2/)

**Comment by slromero-indra** [comment]
Buenas, hemos actualizado el archivoController para que setee el status a 404 cuando no existe microsite o archivo mientras cuando el error no sea controlado devuelva un 500 (por ejemplo, se podría producir intentando obtener un archivo por filesystem que ha sido borrado manualmente).

Ejemplo: 
  http://caibter.indra.es/sites/indra2/f/6666666  (404 - Microsite no existe)
  http://caibter.indra.es/sites/indra/f/6666666    (404 - Fichero no existe)
  http://caibter.indra.es/sites/indra/f/6666          (500 - El fichero fue borrado manualmente por filesystem)

**Comment by sgelabert-dgtic** [comment]
Només una cosa perquè no redirigiu a la pàgina d'error de l'aplicació en lloc de pesentar directament el 404
Resposta actual:
![image](https://user-images.githubusercontent.com/17268396/28458618-b56d1584-6e0a-11e7-9024-0f30b90db683.png)
Reposta que haria de donar:
![image](https://user-images.githubusercontent.com/17268396/28458665-db3e8090-6e0a-11e7-99a5-9f3d86167583.png)

**Comment by slromero-indra** [comment]
Lo miramos, el único problema es que la entidad de retorno de ArchivoController (entidiad responseEntity) es distinta a todo el resto de controller (entidad ModelAndView).

**Comment by sgelabert-dgtic** [comment]
Veig que aquest canvi també està a la 1.4. Correcte ?

**Comment by slromero-indra** [comment]
Si, está en ambas ramas (gusite 1.4 y 1.5), si quieres quitamos el commit de alguna de las ramas.
