### ISSUE TITLE
Optimització del mètode obtenerEncuesta()

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#82]
S'han detetctat problemes greus de rendiment amb el mètode d'obtenció d'enquestes `es.caib.gusite.micropersistence.ejb.EncuestaFacadeEJB.obtenerEncuesta(Long)`

Es sol·licita revisar el funcionament de la capa de persistència per aquest mètode i si és necessari crear els índexos de BBDD per optimitzar la recuperació.

**Comment by slromero-indra** [comment]
Buenas Adjuntamos el documento SQL que contiene la creación de los Indices sobre las tablas de encuestas. 
Podéis verificar que solventan el problema del rendimiento? 
[IndecesEncuestas.sql.txt](https://github.com/GovernIB/gusite/files/959018/IndecesEncuestas.sql.txt)

**Comment by sgelabert-dgtic** [comment]
- Commitau aquest fitxer com oracle_create_index.sql dins el directori /scripts/bbdd/1.3/oracle
- Analitzar possibilitat d'eliminar `refresh() `   del mètode `es.caib.gusite.micropersistence.ejb.EncuestaFacadeEJB.obtenerEncuesta()` perquè el backoffice segueixi funcionant.  Si no és possible evitar que es faci un `refresh()` des dels frontals /sacmicrofront i /sites

**Comment by slromero-indra** [comment]
Referente al punto 1, vemos que en versiones anteriores, los indices, se han añadido en el mismo fichero de update (ej: "[gusite_update_schema_from_1.1.0_to_1.2.1_part3.sql](https://github.com/GovernIB/gusite/blob/gusite-1.3/scripts/bbdd/1.2/oracle/gusite_update_schema_from_1.1.0_to_1.2.1_part3.sql)"), preferis crear un fichero nuevo para la versión 1.3 tal como indicas o añadimos el contenido al fichero "gusite_update_schema_from_1.2.1_to_1.3.0.sql"?

Revisaremos el tema del `refresh()`

**Comment by sgelabert-dgtic** [comment]
Ok, crear doncs un gusite_update_schema_from_1.3.1_to_1.3.2.sql que inclogui els indexos.

Per altra banda, s'hauria d'incloure també l'alter table d'aquí https://github.com/GovernIB/gusite/issues/51#issuecomment-285646789. Crec que és un canvi posterior a la versió 1.3.1 que tenim a producció, no? Si es així no hauria d'estar a gusite_update_schema_from_1.2.1_to_1.3.0.sql

Revisau per favor que en aquest fitxer hi hagi tots els canvis de BBDD necessaris per desplegar la 1.3.2 correctament.

**Comment by slromero-indra** [comment]
Lo revisamos.

**Comment by slromero-indra** [comment]
Buenas,
Hemos creado el fichero de update de bbdd y realizado las modificaciones para que no sea necesario el refresh desde el backoffice. 

Por otro lado hemos detectado que si en la encuesta, la primera pregunta contiene en primer lugar una respuesta de tipo de usuario da un error. ¿Os parece adecuado que creemos una nueva incidencia para tratar esta problemática?

**Comment by sgelabert-dgtic** [comment]
No he estat capaç de reproduir l'error. Aquí teniu un exemple:
https://appsproves.caib.es/sites/M170111145046629/ca/enquesta/
Tampoc apareix cap error a nivell de log del servidor d'aplicacions.

**Comment by slromero-indra** [comment]
Buenas,
Lo hemos revisado de nuevo,  y parece que solo ocurre con la versión antigua de microsites, lo deberíais poder reproducir indicando en la versión  "Microsite públic, segona versió" accediendo a la encuesta, rellenando el dato y enviando.
