### ISSUE TITLE
Bug enviament enquestes frontal /sacmicroback

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#83]
En el tiquet https://github.com/GovernIB/gusite/issues/82#issuecomment-300572236, s'ha detectat un bug en microsites tipus "Microsite públic segona versió" quan s'envia en primer lloc una preguta tipus usuari.
Adjunt log del servidor d'aplicacions [bugEnviamentEnquesta.txt](https://github.com/GovernIB/gusite/files/1024654/bugEnviamentEnquesta.txt)

**Comment by slromero-indra** [comment]
Buenas, 
Hemos realizado unas modificaciones para tratar de solventar la incidencia, ¿lo podéis verificar?

Por otro lado, hemos detectado 2 problemáticas más relacionadas con las encuestas:
1. En Microsite public segona versió, si una pregunta contiene respuestas de tipo usuario, al responderlas y enviar, parece que no se contabilizan en el cálculo del número total de veces que se ha respondido a esa pregunta, y las de tipo ficha solo cuentan si están situadas antes que las de tipo usuario, lo que provoca que los porcentajes no aparezcan correctamente.  En el nuevo frontal, sí que se contabilizan las de tipo ficha, pero no las de tipo usuario.
![image](https://cloud.githubusercontent.com/assets/17451407/26454234/cd6a2bca-4166-11e7-963e-597ca3e174eb.png)

2. Si una pregunta tiene una única respuesta y es obligatoria, el frontal no permite realizar el envío, aunque se conteste (tanto si es de tipo usuario como si es de tipo ficha), aparece siempre un popup indicando falta completar la pregunta. (esto ocurre tanto en Microsite public segona versió, como en el nuevo frontal)
![image](https://cloud.githubusercontent.com/assets/17451407/26454305/0a294eb0-4167-11e7-8589-1fb27bc15b52.png)


¿Queréis que tratemos estos puntos?

**Comment by sgelabert-dgtic** [comment]
He enviat a preproducció la primera correcció. En validar-ho continuam amb la resta de bugs (necessit que funcioni el primer bug per reproduir els altres)

**Comment by sgelabert-dgtic** [comment]
Ok, tractau en aquest mateix tiquet els dos erros detectats:
- Compteig total de resultats
- Bug enviament d'enquestes amb una única reposta obligatòria

**Comment by sgelabert-dgtic** [comment]
Ens sol·liciten corregir el següent error ortogràfic en català
![enquestes](https://cloud.githubusercontent.com/assets/17268396/26822367/14d09804-4aaa-11e7-9ced-4274f70a0b14.jpg)

**Comment by slromero-indra** [comment]
Respecto al punto 1, Realizaremos las modificaciones oportunas para que si las respuestas de tipo usuario si se contestan, se usen para calcular el  valor de "respostes totals".
Respecto al punto 2,  Realizaremos las modificaciones necesarias para que si una pregunta solo tiene una respuesta, solo muestre el popup si no se marca la respuesta.

Respecto a los temas ortográficos usaremos los literales siguientes en función del numero de respuestas:

- No pot contestar més d'1 resposta
- No pot contestar més  de 2 respostes

**Comment by sgelabert-dgtic** [comment]
ok

**Comment by sgelabert-dgtic** [comment]
Podeu donar-li prioritat, m'agradaria poder incorporar aquest canvi en el pas a PROducció de demà.
Gràcies

**Comment by slromero-indra** [comment]
Estamos  terminando de validar los cambios, en breve los subimos.

**Comment by slromero-indra** [comment]
Se han actualizado los 3 puntos indicados

- Compteig total de resultats
- Bug enviament d'enquestes amb una única reposta obligatòria
- Modificación de literales en funcion del número máximo
Es necesario actualizar el tema215, para que los microsites que hagan uso de este tema muestren los literales correctos.
