### ISSUE TITLE
Problemes visualització IE 11

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#85]
Ens remeten problemes de visualització amb l'IE 11 de microsites versió 2015 amb la plantilla per defecte.
Adjunt captura de pantalla:
![captura 2](https://user-images.githubusercontent.com/17268396/27122782-09b6cb30-50ec-11e7-9aa4-3d0079610820.png)

Microsite d'exemple, http://mic.caib.es

**Comment by slromero-indra** [comment]
Buenas, estamos tratando de reproducir el problema y no lo logramos, hemos probado el enlace indicado y aparece correctamente (entendemos que el error es el solapamiento del icono con el texto), hemos probado en varios pc, y a modificar el tamaño de la ventana, y a intentar reproducirlo en local, pero no lo logramos, ¿nos podéis indicar que casuística seguís para poder reproducirlo? ¿cuál es la versión concreta del navegador?
![imagen](https://user-images.githubusercontent.com/17451407/27341114-95b2bf0a-55dc-11e7-84b5-8391dd8761ba.png)

**Comment by sgelabert-dgtic** [comment]
Pareix que el problema es deu una altra vegada al mode de compatibilitat de l'IE. Tot i que es IE11 està actuant com a IE7
![captura](https://user-images.githubusercontent.com/17268396/27468382-c7ada9fc-57e9-11e7-877d-522c9f4eeac2.png)

Cal forçar la capçalera perquè <meta content="IE=edge" http-equiv="X-UA-Compatible">

**Comment by slromero-indra** [comment]
Buenas, 
hemos añadido la etiqueta meta para que se fuerce la última versión de IE, ¿lo podéis verificar?
