### ISSUE TITLE
Controlar els errors en la traducció de llistats

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#87]
Controlar els errors en els elements de llistat que apareixen quan no existeix traducció d'algun camp obligatori segons el tipus de llistat

**Comment by slromero-indra** [comment]
Buenas,
Hemos revisado este tema y nos surge la duda de como queréis que controlemos el error.
Parece que únicamente se reproduce si no se indica la traducción para el **nombre** del listado (configuració--> General-->llistats--> listado a editar), retornando un error 500.
Al no existir la traducción para el título de la página, existen varias opciones:
- Que se quede en la misma página, sin mostrar ningún dato
- Que se quede en la misma página mostrando el título del idioma por defecto u otro mensaje que indique la falta de traducciones.
- Controlar el error para que retorne el error 500 (o el código que nos indiquéis) y un mensaje indicando que faltan traducciones.

¿Os parece adecuada alguna de las opciones? ¿proponéis alguna otra?

**Comment by sgelabert-dgtic** [comment]
Pel que fa al front, per ser coherents amb la resta de l'aplicació hauria de retornar un 404.

**Comment by slromero-indra** [comment]
Buenas,
Se han realizado los cambios para que retorne error 404 si la traducción del nombre del listado no existe.
