### ISSUE TITLE
Modificar URL accés a llistats

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#88]
Es sol·licita modificar la construcció de la URL d'accés a elements de llistat perquè no apareigui la darrera / de la URL de redirecció. 
Exemple: https://appsproves.caib.es/sites/M170111145046629/ca/l/test2/?mcont=67738.

**Comment by slromero-indra** [comment]
Buenas,
Tenemos alguna duda con respecto a este tema. Por lo que hemos visto, actualmente todas las URI se montan como estructuras de directorios, (todas acaban con /), que suele ser la recomendación cuando se usan URL amigables, en algunos casos se añaden parámetros extra, como por ejemplo el caso del **mcont**, que indica si el elemento mostrado tiene correspondencia con el menú lateral.
Entendemos que la problemática viene porque se está mostrando la barra final "/" cuando se incluyen parámetros adicionales. ¿es correcto?
Respecto a esto existen varias opciones, cada una podría aplicarse a todas las URI del nuevo frontal, o solo a las URI de acceso a los elementos de los listados:
- Revisar que las URL que incluyan parámetros adicionales no incluyan la barra final
- Eliminar todas las barras finales de todas las URL (las que incluyen parámetros adicionales y las que no)

¿Nos podéis indicar si alguna de las opciones os parece adecuada? ¿Alguna otra?

**Comment by sgelabert-dgtic** [comment]
Revisar que las URL que incluyan parámetros adicionales no incluyan la barra final

**Comment by sgelabert-dgtic** [comment]
Una cosa més, en llistats tipus notícia s'afegeix el paràmetre mcont sense ser necessari... Per exemple, les dues adreces següents resolen correctament:
https://proves.caib.es/sites/M170111145046629/ca/n/proves_carcel_1/?mcont=67230
https://proves.caib.es/sites/M170111145046629/ca/n/proves_carcel_1/

És a dir, si l'element del llistat té URI personalitzada (per defecte se'n genera una sempre) no cal afegir el paràmetre

**Comment by slromero-indra** [comment]
Buenas,
Las uris se usan para acceder al listado, y el campo mcont para indicar a que opción del menú lateral pertenece y mantenerlo seleccionado/marcado. Si se accede sin este campo se pierde la referencia a la opción del menú seleccionada, ya que las opciones del menu tienen su propia uri , por lo que no aparecerá marcada en el menú lateral. A priori entendemos que el campo es necesario. ¿os parece adecuado mantener el funcionamiento actual?

**Comment by slromero-indra** [comment]
Buenas ya se han realizado los cambios.
ahora si la url incluye parámetros, no se muestra la barra final.

**Comment by slromero-indra** [comment]
Se ha corregido un problema al cargar los formularios de contacto. Hemos probado nuevamente con todos los componentes y no hemos detectado ningún otro error. 
Ya se puede validar el desarrollo.
