### ISSUE TITLE
Bug presentació codi HTML en FAQs

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#89]
En microsites tipus "microsite intranet" el frontal sacmicrofront no interpreta el codi HTML de les preguntes/respostes.
Adjunt captures de pantalla.
/sacmicrofront
![bugfaqs](https://user-images.githubusercontent.com/17268396/27574137-68dccc08-5b15-11e7-942a-f6596c26998e.jpg)
/sacmicroback
![bugfaqs-back](https://user-images.githubusercontent.com/17268396/27574239-cfc0a624-5b15-11e7-9bc9-ac85f07b0803.jpg)

**Comment by slromero-indra** [comment]
Buenas, 
Hemos corregido la problemática, ¿lo podéis validar?
