### ISSUE TITLE
Controlar error usuari amb rol però no donat d'alta en l'aplicació

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/gusite#9]
Numero: 15
Creació: 2016-02-16 07:59:00.281000
Controlar l'error que genera l'accés d'un usuari que té rol d'aplicació assignat GUS_xxx, però no s'ha donat d'alta en la gestió d'usuaris de l'aplicació.
Adjunt l'error del servidor d'aplicacions.

**Comment by kitanibaladmin** [comment]
[BUG_usuari_sense_alta.txt](https://github.com/GovernIB/gusite/files/144323/BUG_usuari_sense_alta.txt)

**Comment by episano-dgtic** [comment]
Para comprobar en vuestro entorno debo eliminar el acceso a mi usuario "u100748" pero falla. 
Aunque si he podido crear un usuario tonto, asignarle microsites y eliminarlo posteriormente. 

Luego el servidor ha caído.. o estábais haciendo cambios. 

Cuando esté activo, miraré de borrar el usuario de David Madroñal Sánchez (u83491) y luego me aseguraré de volverlo a dar de alta.

**Comment by episano-dgtic** [comment]
Comprobado para david.. perfecto. Aunque interesaría ver que problema hay con la eliminación de mi usuario "u100748"
