### ISSUE TITLE
Bug plantilla 2015 responsive 

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#90]
Cal revisar la plantilla "tema2015" perquè visualitzi correctament els elements per a dispositiu mòbil.
Ara mateix està tallant texts i altres elements com les agendes. Adjunt captura de pantalla del site http://www.caib.es/sites/iqpib/ca/inici/?campa=yes

![responsivetema2015](https://user-images.githubusercontent.com/17268396/27581915-67e461ac-5b2f-11e7-94d0-9b770938b4af.jpg)

**Comment by slromero-indra** [comment]
Buenas,
Hemos estado revisando la incidencia, haciendo varias pruebas, y a priori parece que no es problema de la plantilla. Por lo que parece han introducido un contenido maquetado con tablas con ancho fijo, lo que provoca la casuística de la incidencia.
¿Nos podéis facilitar la exportación del microsite para que verifiquemos si este es el problema?

**Comment by sgelabert-dgtic** [comment]
Ho he exportat i són 277MB, amb aquestes dimensions la importació segurament us petarà...
No podeu accedir a producció https://intranet.caib.es/sacmicroback ? Puc mirar d'autoritzar-vos al microsite

**Comment by slromero-indra** [comment]
Buenas, 
Parece que no tenemos permisos, al identificarnos nos da un error ("No té accés a l'aplicació" ). Si nos otorgais permisos podemos tratar de revisarlo.

**Comment by slromero-indra** [comment]
Buenas, 
Al parecer han realizado la maquetación del contenido con tablas, y por eso no se comporta como responsive.  Para realizar una maquetación responsive mediante columnas podrían hacer uso de las directrices de bootstrap http://getbootstrap.com/css/#grid, esto funcionaría para la versión 2015 de los microsites (tanto la versión por defecto como el tema 2015).
¿Debemos revisar algo más con respecto a esta incidencia?


![imagen](https://user-images.githubusercontent.com/17451407/27678332-2797b8d8-5cb5-11e7-84d7-0d1cc1531175.png)
