### ISSUE TITLE
Bug en formularis de contacte

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#91]
Hi ha un bug ens els formularis de contacte quan s'intenta introduir un camp on el títol és un " " (espai) o bé té el caràcter "#" (parrilla).
Comprovar que aquest error no es reprodueixi en altre tipus de recursos

**Comment by slromero-indra** [comment]
Buenas 
hemos corregido este problema, hemos realizado diversas pruebas sobre otros componentes y no hemos detectado nada parecido.
