### ISSUE TITLE
Bug cercador de continguts SOLR

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#92]
Després d'haver reindexat un microsite hi ha errades amb la pàgina de resultats:
- Els enllaços es construeixes amb un context /sites de més, per exemple, https://intranet.caib.es/sites/sites/eines/ca/introduccio_al_rolsac-3630  quan el correcte seria https://intranet.caib.es/sites/eines/ca/introduccio_al_rolsac-3630
- Els percentatges de rellevància supera en alguns casos el 100%. 
Adjunt captura de pantalla
![bugs-cercador](https://user-images.githubusercontent.com/17268396/28069048-492a79b2-6648-11e7-953a-d82d70217a0a.jpg)

**Comment by slromero-indra** [comment]
Buenas, respecto al problema del score, ya se comentó en su día su complejidad. Como se comenta en el foro principal  ( https://wiki.apache.org/lucene-java/ScoresAsPercentages ), no es posible la obtención de un porcentaje.

Se realizó una aproximación a partir de la fórmula de edismax que no es lo suficiente correcta, se utilizó el valor 3 como 100% debido a la formula edismax es:  
   searchText_IDIOMA^2.0 searchTextOptional_IDIOMA^0.2 
 
A partir de aquí se pueden realizar dos cambios:
 - SOLR devuelve el score máximo obtenido en la consulta. Se puede utilizar como el valor 100%. Esto evitaría que ningún resultado sobrepasase el 100% pero no es del todo real. 
 - Mantener el funcionamiento actual e incrementar el máximo teórico (para marcar el 100%) y poner también un máximo de 100% no sobrepasable por solrapi.

**Comment by sgelabert-dgtic** [comment]
Respecte a l'score màxim de SOLR, el primer resultat tendria sempre el 100% ?

**Comment by slromero-indra** [comment]
Si utilizásemos la primera aproximación sí.

Normalmente, solr devuelve un valor numérico por debajo de 1.0, se puede utilizar el 1.0 como el 100% siempre que ningún valor lo sobrepase y, en caso de hacerlo, utilizar el maxscore como el 100%.

El maxscore varía en cada consulta, es siempre el máximo resultado devuelto, no el máximo teórico.

**Comment by sgelabert-dgtic** [comment]
Ok, ido apliquem aquesta aproximació

**Comment by slromero-indra** [comment]
El problema con las urls ya está solucionado. Respecto a solr, se va a proceder a realizar lo siguiente:
 - Se va a incrementar solrapi de la versión 1.0.0 a la 1.0.1
 - Se incorporará los siguientes cambios:
       * El 100% lo marca el valor 1.0
       * Si el maxscore es mayor al 1.0, el 100% lo marca el maxscore
 - Se actualizará las librerías solrapi en seucaib, gusite, webcaib. Como el cambio es sólo para el score, sólo le afecta a GUSITE (por lo que el resto de proyectos no hace falta volver a desplegarlo).
