### ISSUE TITLE
Bug presentació llistat tipus mapa amb IE

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#93]
Tenim problemes amb la visualització de llistats tipus mapa amb IE:
- Amb IE-11 corporatiu (mode compatibilitat Egde), no carrega el mapa:
![capturaie](https://user-images.githubusercontent.com/17268396/28155370-adf9430c-67ae-11e7-982c-99d92b248389.png)

- Amb IE-Edge, carrega el mapa però no mostra els punts:
![capturaie-edge](https://user-images.githubusercontent.com/17268396/28155406-e201bc6a-67ae-11e7-9f75-566538172bd4.jpg)

Podeu veure un exemple a http://www.caib.es/sites/atenciociutadania/ca/l/oficines/

**Comment by slromero-indra** [comment]
Buenas,
Estamos tratando de reproducir el problema con IE 11 pero no lo logramos, ¿podéis indicarnos la versión exacta de IE? ¿estáis accediendo desde un puesto que pueda tener restringidos algunos accesos (vpn, proxy, etc ...)?¿os sucede en todas las maquinas? 
Referente a IE-Edge, no hemos podido validarlo, en cuanto podamos os decimos algo.

![image](https://user-images.githubusercontent.com/17451407/28356806-9dbe1002-6c69-11e7-80be-61478518f675.png)

**Comment by sgelabert-dgtic** [comment]
- La versió és 11.0.9600.18738. 
- Totes les màquines internes passen per proxy per sortir a Internet
- Ho hem provat amb diverses màquines i passa el mateix
Adjunt captura de pantalla amb la versió i les errades de consola. Pot ser que la JPS introdueixi algun <p></p> no tancat ?
![map_ie11-versio11 0 9600 18738](https://user-images.githubusercontent.com/17268396/28452880-e8e72726-6df4-11e7-81db-4d4c79f8b2a3.jpg)

He afegit a n'Àlex com usuari a gestor del microsite en PROducció per si li voleu donar una ullada al codi d'usuari.

**Comment by sgelabert-dgtic** [comment]
Amb Chrome Versió 59.0.3071.115 (64 bits), no apareixen el punts
![map-chrome-59 0 3071 115](https://user-images.githubusercontent.com/17268396/28453105-04589e26-6df6-11e7-9c2f-ccf9ca8aa42f.jpg)

**Comment by slromero-indra** [comment]
Buenas, 
estamos tratando de acotar el problema, pero en nuestras maquinas, con las mismas versiones, tanto de Chrome como de Explorer funciona correctamente. No creemos que se trate de un problema del contenido, porque a nosotros también nos aparecería el error. Hemos probado desde un móvil Android con varios navegadores y un Iphone, y también aparece el mapa y los puntos, (se muestra el mapa con las 65 oficinas). ¿Podéis revisar si en Chrome, en la pestaña de Network, os están llegando todos los ficheros correctamente?  nos podéis facilitar un pantallazo de esa pestaña (si se ordena por status se aprecia mejor si retorna algún error) adjuntamos un pantallazo similar.
![imagen](https://user-images.githubusercontent.com/17451407/28454042-06436992-6dfa-11e7-86b6-39b307cfdbfc.png)

**Comment by sgelabert-dgtic** [comment]
Ho he tornat a provar amb Chrome i ara sí que m'ha carregat ....
Centrau-vos amb IE11 i FireFox ESR 45 que són els navegador corporatius

**Comment by slromero-indra** [comment]
Ok, podéis facilitarnos la misma información del Explorer? Una captura de pantalla con la pestaña Red (hay que pulsar play y a continuación CTRL+F5) y ordenarlo por Resultado , además necesitaríamos el   xml obtenido de "Exportar el tráfico capturado".  A ver si con esta información podemos averiguar que está ocurriendo.
![image](https://user-images.githubusercontent.com/17451407/28461957-4f7f7db6-6e19-11e7-8087-85881053e662.png)

**Comment by sgelabert-dgtic** [comment]
![image](https://user-images.githubusercontent.com/17268396/28462360-338a7078-6e1b-11e7-885a-cb29720dbddd.png)

[NetworkData.zip](https://github.com/GovernIB/gusite/files/1165388/NetworkData.zip)

**Comment by slromero-indra** [comment]
Buenas, por lo que aparece en la imagen, el js de google maps no se carga correctamente, por alguna razón está en estado pendiente, por lo que es probable que ese sea la fuente del problema.  Lo que no tenemos claro es si es debido a alguna configuración del internet explorer o a un baneo del proxy.  ¿Podeis intentar a llamar desde el explorador a la url de google maps?

**Comment by slromero-indra** [comment]
Por otro lado hemos probado a acceder desde edge y no nos ha dado problemas, entendemos que el problema será algo similar al que os ocurre en IE 11 :
![image](https://user-images.githubusercontent.com/17451407/28511300-e58404d2-704c-11e7-8698-6d4ed52d2760.png)

**Comment by sgelabert-dgtic** [comment]
Pareix un problema amb l'script de configuració dels proxy per al navegador IE. El departament de seguretat ho està revisant

**Comment by slromero-indra** [comment]
¿buenas sabeis algo de este tema? debemos revisar alguna cosa más?

**Comment by sgelabert-dgtic** [comment]
La persona que s'encarrega del tema està de vacances. L'error es reprodueix aletoriament sobre algunes màquines de l'entorn CAIB. Pensam que està relacionat amb el proxy. Us mantindré informats

**Comment by sgelabert-dgtic** [comment]
S'han enrutat les peticions a l'API de Google per un altre proxy-caib i s'ha solucionat el problema amb IE11
