### ISSUE TITLE
Manteniment del servei d'URIs basades en clau de microsite 

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#94]
Es sol·licita efectuar una redirecció (http-301) de la URL per defecte basada en el camp GUS_MICROS.MIC_CLAVE quan el microsite canvia cap una URL personalitzada (GUS_MICROS.MIC_URI).
L'objectiu és minimitzar els errors "No se encuentra microstie/Contenido no encontrado" quan s'efectua un canvi de la URI per defecte.

Incorporar solució descrita en el tiquet https://github.com/GovernIB/gusite/issues/80#issuecomment-318629262

**Comment by slromero-indra** [comment]
Buenas ya están disponibles los cambios para que podais validarlo.
