### ISSUE TITLE
Error presentació "Annexar Arxiu" en Microsites tipus Intranet

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#97]
En Microsites tipus Intranet, el frontal no presenta el camp per annexar arxiu en els formularis de contacte.
Amb microsites tipus public, segona versió sí que apareix.
Adjunt captura de pantalla d'un microsite públic on funciona correctament
![image](https://user-images.githubusercontent.com/17268396/29069723-5ceb27d0-7c3c-11e7-8b41-9a436e7ea395.png)

**Comment by slromero-indra** [comment]
Buenas se han realizado los cambios

**Comment by sgelabert-dgtic** [comment]
Podríeu consolidar aquests canvis per la 1.4.2 ?
Gràcies

**Comment by slromero-indra** [comment]
Buenas, ya lo teneis disponible en la rama 1.4.
